### ISSUE TITLE
Level up the Ember Experience

### ISSUE THREAD

**Issue by gossi** [storybookjs/storybook#10074]
Storybook is gaining attraction from Ember developers (I am one of them) and I'd like to improve the experience for those ember devs jumping onto storybook. Here are areas in which I see can it should need some love (and in that order):

1. Code Stability
2. Documentation
3. Addons

## Code Stability

Getting storybook to work with ember shouldn't be much more than running `ember install ember-cli-storybook`. However to make this work seemless it needs some love.

Second thing is to get the properties table going. This is using the docs exporter from `ember-cli-addon-docs` at the moment but isn't a pleasent thing to do yet. I started an issue emberjs/rfcs#591 that hopefully leads into a proper RFC with code that generates generic documentation format that can be consumed by storybook.

## Documentation

The docs should be written from the perspective of an ember developer. Here is what I see as topics:

Basic Topics:
- How to install storybook for ember: ember install ember-cli-storybook  and that's it :wink: (most likely this requires code changes)
- How to write stories in CSF and MDX format

Advanced Topics:
- What are decorators and how to use them with ember
- How to set it up with Typescript

Monorepo Topics:
- How to use ember and storybook in  a monorepo setup
- How to set it up with Typescript

PS: Monorepo support comes with `storybook@v6` for ember!

## Addons

Storybook has great addons that are not easy to use with ember at all.

I really, really like the addon toolbar coming with v6 and I wrote down [how to implement this from ember side](https://discordapp.com/channels/486522875931656193/495120652534153227/685059952150052874) - however maybe this implementation is more broad and can serve as a link between ember and storybook in a generic fashion - I dunno.

## Collaboration

I would consider this issue as a _user story_ - feel free to break out tasks, link them here, so they stay in context ❤️

**Comment by jonniebigodes** [comment]
@gossi i've been hoping to expand the storybook tutorial to ember for quite some time and also some other frameworks aswell but this was put on the "back burner" for a bit of time as the existing documentation needed some tweaks. If you're ok with this i'll be working on the ember tutorial and i would like for you to proof read and help me fine tune the the pr, so that it gets the deserved attention. Sounds good?

**Comment by dbendaou** [comment]
Could we deactivate stale bot on this issue ?

**Comment by shilman** [comment]
Done 👍

**Comment by jonniebigodes** [comment]
@gossi sorry for the delay. I've moped up the documentation for the the intro to storybook with ember in [here](https://github.com/chromaui/learnstorybook.com/pull/306) and here is the [preview](https://deploy-preview-306--tender-kilby-05eed0.netlify.app/intro-to-storybook/ember/en/get-started/), feel free to provide feedback

**Comment by bfitch** [comment]
Hi @jonniebigodes. I gave the updated instructions, in the preview linked above (https://deploy-preview-306--tender-kilby-05eed0.netlify.app/intro-to-storybook/ember/en/get-started/), a try and I'm still not able to load any stories. Here is a screenshot of the dev tools error:

![Screen Shot 2020-06-22 at 5 05 21 PM](https://user-images.githubusercontent.com/577208/85335326-d4737d80-b4aa-11ea-8737-5e9dfa89119a.png)

I also got an `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'content' of undefined` error while running `yarn run storybook-dev` that I already created an issue for [here](https://github.com/storybookjs/ember-cli-storybook/issues/42)

Any suggestions?

**Comment by bfitch** [comment]
Sorry that screenshot is not very clear. The error output is:
```
render.js:38 Uncaught TypeError: _global.window.require is not a function
    at Object../node_modules/@storybook/ember/dist/client/preview/render.js (render.js:38)
    at __webpack_require__ (bootstrap:848)
    at fn (bootstrap:150)
    at Object../node_modules/@storybook/ember/dist/client/preview/index.js (index.js:14)
    at __webpack_require__ (bootstrap:848)
    at fn (bootstrap:150)
    at Object.<anonymous> (index.js:55)
    at Object../node_modules/@storybook/ember/dist/client/index.js (index.js:59)
    at __webpack_require__ (bootstrap:848)
    at fn (bootstrap:150)
```

**Comment by jonniebigodes** [comment]
@bfitch if you don't mind i'll take a look at it tomorrow. Do you mind waiting a bit?

**Comment by bfitch** [comment]
@jonniebigodes No problem. Have a good night!

**Comment by gossi** [comment]
@bfitch can you extract this into its own issue? We've seen this popping up in discord the last week. Nice opportunity or bringing people together here

**Comment by bfitch** [comment]
Thanks @gossi. I added the issue linked above.

**Comment by dbendaou** [comment]
About the topic issue, I think it would be cool to add some words about `services`/`Ember objects`/`model`/`store`?
It possible to make them work, though it's a bit hacky, I think it could be cool talk about it.
WDYT ?

**Comment by dbendaou** [comment]
By the way, I found that if you add  [babel-plugin-ember-modules-api-polyfill](https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill) and because it's already declared as a module [there](https://github.com/storybookjs/storybook/blob/next/app/ember/src/server/framework-preset-babel-ember.ts#L19) it will make ember import works 🎉 

Maybe we can make it to be added by default with the installation ? Or at least document this somewhere
