### ISSUE TITLE
Knobs broken for Vue  components

### ISSUE THREAD

**Issue by piemasters** [storybookjs/storybook#11238]
**Describe the bug**
The Knobs addon was working perfectly in v6 beta-21, but is no longer functioning correctly after upgrading to beta-25. 

Using knobs on standard web elements works fine, but when passing as props to Vue components all values are being converted to strings and I receive the following error: `Invalid prop: type check failed for prop "orange". Expected Boolean, got String with value "false".`

I've also found that in some cases with components with only string props, no error is thrown but the default values within the component are used instead of the knobs and updating the knobs does not trigger any update (although knobs not used as props to Vue components continue to work).

I've tried both CSF and MDX story formats and both result in the same errors.

**To Reproduce**

Vue component
```
<template>
  <div :class="{ 'orange-spinner': orange }" />
</template>

<script>
import Vue from "vue";
export default Vue.extend({
  name: "TestSpinner",
  props: {
    orange: {
      type: Boolean,
      default: false,
    },
  },
});
</script>
```

Story
```
import { Story, Preview, Meta } from "@storybook/addon-docs/blocks";
import { withKnobs, boolean } from "@storybook/addon-knobs";
import TestSpinner from "./Spinner";

<Meta title="Components/Experimental/Spinner" component={TestSpinner} />

## Default

<Preview>
  <Story name="Base">
    {{
      components: { TestSpinner },
      props: {
        orange: {
          type: Boolean,
          default: boolean("Orange", false),
        },
      },
      template: `
    <TestSpinner :orange="orange" />
  `,
    }}
  </Story>
</Preview>
```

**Comment by shilman** [comment]
FYI, we’ve released addon-controls in 6.0-beta. Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
- [Walkthrough: Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

Please upgrade and try them out today!

**Comment by shilman** [comment]
Is this still a problem?

**Comment by piemasters** [comment]
Not sure if this issue still exists in the latest version of knobs, but I've fully transitioned over to controls and this is no longer an issue so happy for it to be closed.

**Comment by ryan-ludwig** [comment]
We're still seeing this issue with any knob that passes in an object on v6.0.12.  Error is
```
[Vue warn]:Invalid prop: type check failed for prop "myProp". Expected Object, got String with value "{
    myKey: {},
    someOtherKey: {},
}"
```

**Comment by shilman** [comment]
@ryan-ludwig please consider upgrading to controls in 6.0

- [Controls documentation](https://storybook.js.org/docs/react/essentials/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

**Comment by jowilhnson** [comment]
This seems to still very much be an issue. So perhaps the documentation should be clearer that knobs is no longer fully supported with Vue, may cause silent failures, and that moving to Controls is strongly suggested. 

Because this happened with migration to Storybook 6, I assumed I'd somehow messed something up in the migration and just kept referring back to the migration docs which make no mention of this. I fully planned to try out Controls, but first just wanted to get my existing setup migrated. Knowing I needed to switch to Controls right away would have saved a lot of time and frustration.

**Comment by shilman** [comment]
Yup. We have a few things to add to args/controls in 6.2 and then we're going to deprecate knobs.
