### ISSUE TITLE
Controls with decorator always remount from root

### ISSUE THREAD

**Issue by jwoo0122** [storybookjs/storybook#12255]
**Describe the bug**
With decorator, when you change some args by controls, all DOM inside iframe are remounted and so css transition not working

**To Reproduce**
https://github.com/jwoo0122/storybook-test
1. Clone this repository.
2. npm run storybook
3. Access localhost:6006
4. Go to Button story, and toggle primary in control panel.

**Expected behavior**
CSS transition should works.

**Screenshots**
This is the expected behavior (tested without decorator).
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/29848729/91302138-f78b1800-e7e0-11ea-8fcf-3c218a77ac9b.gif)

And this is an actual behavior (tested with decorator).
![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/29848729/91302224-19849a80-e7e1-11ea-8ffe-e20f9676486d.gif)

**Code snippets**
Decorator used to test is this. You can find this in Button.stories.js from the repo I wrote into 'To Reproduce' section.
```ts
Story => <Story />
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Edge: 84.0.522.63
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.18 => 6.0.18 
    @storybook/addon-controls: ^6.0.18 => 6.0.18 
    @storybook/addon-essentials: ^6.0.18 => 6.0.18 
    @storybook/addon-links: ^6.0.18 => 6.0.18 
    @storybook/node-logger: ^6.0.18 => 6.0.18 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.18 => 6.0.18 
```

**Additional context**
jwoo0122/storybook-test is configured by the step below.
```
npx create-react-app storybook-test
cd storybook-test
npx -p @storybook/cli sb init
npm i -D @storybook/addon-controls
```
And add decorator to Button.stories.js and preview.js (global decorators).

**Comment by jwoo0122** [comment]
Still reproduced in 6.0.20

**Comment by shilman** [comment]
Possibly related: https://github.com/storybookjs/storybook/issues/10616

@tmeasday can you take a look?

**Comment by tmeasday** [comment]
@jwoo0122 FYI it does work if the decorator is `Story => Story()`.

I have no idea why React is doing this. My only explanation is that from React's perspective, `<Story/>` is changing when the args change. 

My mental model of `<Story />` is that React creates an element of the form `{ type: Story, props: {} }` -- and when it does the VDOM diff to decide whether to recreate the DOM node it simply considers the equality of the `type` field. The `Story` function *doesn't* change when the args change, so I am missing something (you can put a break point in `_renderMain` to see that).

**Comment by rajuashok** [comment]
Is there a workaround for this? Right now when I add this to `preview.js` all transitions break:

```js
export const decorators = [
  (Story) => <ThemeProvider theme={light}><GlobalFonts/><Story/></ThemeProvider>
]
```

**Comment by rajuashok** [comment]
Ah nvm, figured it out. This fixes it:
```js
export const decorators = [
  (Story) => <ThemeProvider theme={light}><GlobalFonts/>{Story()}</ThemeProvider>
]
```

**Comment by hzhu** [comment]
@tmeasday @shilman 

I'm not sure there is a workaround for this issue.

I've forked @jwoo0122's example and updated the decorator to `Story => Story()` [here](https://github.com/hzhu/storybook-test/commit/c0fd033c45fa4ed20f99f5d70e533a43f342c4e7#diff-27d30fac32c8fa6352defcdcb101e93cL11). But the transition is still broken. Here's a [demonstration](https://storybook-test-primary.netlify.app/?path=/story/example-button--primary) of the working transition driven by state _versus_ a broken transition driven by Storybook control.

**Comment by Rvtea** [comment]
It is interesting that I found this issue that I was searching for some param to control the behavior of 'controls' to remount the component rather then re-render as I have a feature component need to re-mount to have the correct behavior. 

And currently I am using the existing decorator behavior to reach that purpose via the behavior that current issue raised, but I know this is "temporary solution" after fixed. So I am wondering if we could provide a param to control the behavior of `re-mount` or `re-render` ?

**Comment by tmeasday** [comment]
@Rvtea so you want the component to remount whenever a control value changes?

**Comment by Rvtea** [comment]
> @Rvtea so you want the component to remount whenever a control value changes?

@tmeasday 
Yes, I would like that level control capability, could you consider adding that support? Use a single boolean value to control that would be great.

**Comment by tmeasday** [comment]
@Rvtea -- I'm not sure, it seems contrary to what most users want when it comes to controls.

One workaround you could try to force a remount (in React at least) is something like:

```js
const Template = (args) => <Component {...args} key={Math.random()} />
```

**Comment by migueloller** [comment]
@rajuashok's workaround breaks context used in Stories since calling `Story()` is different from doing `<Story />`

**Comment by tmeasday** [comment]
@migueloller it's been a while since I looked closely at this (https://github.com/storybookjs/storybook/issues/12255#issuecomment-684505829) but I said:

> The Story function doesn't change when the args change, so I am missing something (you can put a break point in _renderMain to see that).

That seems to run contrary to what you've observed there. Any chance of trying to put some breakpoints in and see if you can figure out where the "change" happens?

**Comment by migueloller** [comment]
@tmeasday, yeah I'll look into it. Also, I wanted to provide a simple repro so y'all could see it in action:

```tsx
import React, { useEffect } from 'react'
import { Meta, Story } from '@storybook/react/types-6-0'

export default {
  title: 'Sandbox',
  argTypes: { count: { name: 'count', type: 'number' } },
} as Meta

type ExampleProps = { count: number }

function Example({ count }: ExampleProps): JSX.Element {
  return <>Example {count}</>
}

const Template: Story = ({ count }) => {
  useEffect(() => {
    console.log('mounted')

    return () => {
      console.log('unmounted')
    }
  }, [])

  return <Example count={count} />
}

export const Default = Template.bind({})
Default.args = { count: 0 }
```

This story will re-mount every time the `count` arg is changed either in docs or the actions tab. Also, one can set up state in a decorator and that will cause the same behavior. Since decorators technically aren't React components, though, it shouldn't be safe to use hooks there.

**Comment by migueloller** [comment]
@tmeasday, also, I tried putting a breakpoint on the component to see if I could find `_renderMain` in the stack frames but had no luck. Where is `_renderMain` located?

**Comment by migueloller** [comment]
Also, to give some color as to how we ran into this issue, we use decorators to allow providing a GraphQL schema for stories that use `@apollo/client`. These resolvers are exposed via hooks (i.e., `useResolvers`) because they hold internal state so that queries and mutations can interact with that state. This means that we need to call `useResolvers` and then provide them via a decorator using a component we've named `SchemaProvider`. It looks something like this:

```tsx
const resolvers = useResolvers()

return <SchemaProvider resolvers={resolvers}>{children}</SchemaProvider>
```

Now, we started doing this to get it working with this re-mounting issue:

```tsx
const decorators = [
  Story => {
    const resolvers = useResolvers()

    return <SchemaProvider resolvers={resolvers}>{Story()}</SchemaProvider>
  },
]
```

Note the `{Story()}` instead of `<Story />`. The issue is that because `Story()` is being called as a function instead of being rendered as an element, then context isn't being provided properly. But using `<Story />` causes the re-mounting issue. So we're at an impasse. The way we work around if for now is by doing this:

```tsx
function WithSchema({ children }: { children: ReactElement }) {
  const resolvers = useResolvers()

  return <SchemaProvider resolvers={resolvers}>{children}</SchemaProvider>
}

const decorators = [Story => <SchemaProvider resolvers={resolvers}><Story /></SchemaProvider>]
```

It's worth pointing out that I realized that since decorators aren't React components one shouldn't be using hooks in there. So the `WithSchema` wrapper seems necessary regardless.

Maybe I'm missing something here. Would love to be pointed in the right direction @tmeasday

**Comment by tmeasday** [comment]
@migueloller -- try searching for `_renderMain` in the vendors bundle in the preview:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/132554/108983837-663f2480-76e3-11eb-987c-9db0398f6bb8.png">

`Story` in there is the fully decorated story.

Another spot to put a break point would be in the `defaultDecorateStory` function (in the same file).

PS a couple things:

1. In your [example](https://github.com/storybookjs/storybook/issues/12255#issuecomment-784257442) you don't have a decorator. Are you sure we are looking at the same issue here?

2. You said:

> The issue is that because Story() is being called as a function instead of being rendered as an element, then context isn't being provided properly.

I don't get this bit, because doesn't your component ultimately get rendered as a JSX element by the `Template` function? Are you trying to access the context higher up in the tree (i.e. another decorator or the template itself)? I'm not sure if that's a good idea?

**Comment by migueloller** [comment]
@tmeasday, with regards to your responses:

> In your example you don't have a decorator. Are you sure we are looking at the same issue here?

Yeah, good catch. I was just trying to have the minimal amount of code for reproduction and it wasn't necessary to have a decorator to cause the remounts. Adding a decorator, either `Story => Story()` or `Story => <Story />`, keeps it remounting anyway so I left it out.

> I don't get this bit, because doesn't your component ultimately get rendered as a JSX element by the Template function? Are you trying to access the context higher up in the tree (i.e. another decorator or the template itself)? I'm not sure if that's a good idea?

You might want to use a hook in the `Template` function (e.g., to have some state), but if `Story` in the decorator is called like `Story()` instead of `<Story />` then you're basically calling the hook in the decorator, which isn't a React component and is bad.

It's also worth noting that this example does not have any remount issues when state changes (no args change):

```tsx
import React, { useState, useEffect } from 'react'
import { Meta, Story } from '@storybook/react/types-6-0'

export default {
  title: 'Sandbox',
  decorators: [Story => <Story />],
} as Meta

type ExampleProps = { count: number }

function Example({ count }: ExampleProps): JSX.Element {
  return <>Example {count}</>
}

const Template: Story = () => {
  const [count, setCount] = useState(0)

  useEffect(() => {
    console.log('mount')

    return () => {
      console.log('unmount')
    }
  }, [])

  return (
    <>
      <Example count={count} />
      <button onClick={() => setCount(c => c + 1)}>increment</button>
    </>
  )
}

export const Default = Template.bind({})
```

But this one does have issues, and it behaves similarly to changing args:

```tsx
import React, {
  createContext,
  Dispatch,
  SetStateAction,
  useState,
  useContext,
  useEffect,
} from 'react'
import { Meta, Story } from '@storybook/react/types-6-0'

const CountContext = createContext<[number, Dispatch<SetStateAction<number>>]>([0, () => {}])

export default {
  title: 'Sandbox',
  decorators: [
    Story => {
      const [count, setCount] = useState(0)

      return (
        <CountContext.Provider value={[count, setCount]}>
          <Story />
        </CountContext.Provider>
      )
    },
  ],
} as Meta

type ExampleProps = { count: number }

function Example({ count }: ExampleProps): JSX.Element {
  return <>Example {count}</>
}

const Template: Story = () => {
  const [count, setCount] = useContext(CountContext)

  useEffect(() => {
    console.log('mount')

    return () => {
      console.log('unmount')
    }
  }, [])

  return (
    <>
      <Example count={count} />
      <button onClick={() => setCount(c => c + 1)}>increment</button>
    </>
  )
}

export const Default = Template.bind({})
```

Of course, if one changes `<Story />` to `Story()` then then the remounting doesn't happen, but now the provider's value isn't used since the story isn't being rendered as an element.

Anyway, I think we can all agree that it's a bad idea to use context in a decorator, and it's also a bad idea to do `Story()` instead of `<Story />` in a decorator because `Story` is a React component and so it's not meant to be called (?). Although this is the assertion I'm least unsure of and would love to know the stance of the Storybook team on this. All the docs use `<Story />` as if `<Story />` is a React component so that's what I'm assuming.

So, the issue at hand is that changing args remounts the story and using `Story()` isn't a good solution for all the reasons discussed above. As for taking a look at `_renderMain`, I'm running into a different bug where my addons aren't showing and so I'm not able to change the args. The only way I'm able to change args is in the "Docs" tab but that doesn't seem to use `_renderMain` since the breakpoint won't trigger. One can test the re-mounting issue with the example I have above, also making this addition show clearly that `Story` is changing:

```diff
 import React, {
   createContext,
   Dispatch,
   SetStateAction,
   useState,
   useContext,
   useEffect,
 } from 'react'
 import { Meta, Story } from '@storybook/react/types-6-0'
 
 const CountContext = createContext<[number, Dispatch<SetStateAction<number>>]>([0, () => {}])
 
 export default {
   title: 'Sandbox',
   decorators: [
     Story => {
       const [count, setCount] = useState(0)

+      const lastStory = useRef(Story)
+
+      if (lastStory.current !== Story) {
+        console.log('Story changed')
+
+        lastStory.current = Story
+      }
+
       return (
         <CountContext.Provider value={[count, setCount]}>
           <Story />
         </CountContext.Provider>
       )
     },
   ],
 } as Meta
 
 type ExampleProps = { count: number }
 
 function Example({ count }: ExampleProps): JSX.Element {
   return <>Example {count}</>
 }
 
 const Template: Story = () => {
   const [count, setCount] = useContext(CountContext)
 
   useEffect(() => {
     console.log('mount')
 
     return () => {
       console.log('unmount')
     }
   }, [])
 
   return (
     <>
       <Example count={count} />
       <button onClick={() => setCount(c => c + 1)}>increment</button>
     </>
   )
 }
 
 export const Default = Template.bind({})
```

Maybe you have some pointers on how I can fix the addons issue so that I can step through what's happening in `_renderMain`?

**Comment by tmeasday** [comment]
@migueloller 

> it wasn't necessary to have a decorator to cause the remounts.

It should be! Otherwise we are talking about a different issue to this one (which is totally possible, I'm not sure). Perhaps you should try starting with a simple create-react-app project or something (that would likely help with the addons problem)

> You might want to use a hook in the Template function (e.g., to have some state), but if Story in the decorator is called like Story() instead of <Story /> then you're basically calling the hook in the decorator, which isn't a React component and is bad.

Well, I am not advocating for a "tell people to use `Story()` rather than `<Story/>`" approach as a long term solution here, but the entire decorated story *is* rendered as a react component in `_renderMain`, so I don't think this statement is correct.

---

Your example with use state in a decorator is interesting. I think we should unpack that further. Let me try and unpack what's going across SB's stack (which is a bit hard to understand I'm sure) and see if that helps you get further (I only have a few mins, sorry!):

1. You pass the `bind()`-ed `Template` into SB via exporting it from your CSF file. We can think of that as a simple React functional component. This is referred to as `original` in the story store.

2. SB's story store wraps the `original` in its decorators and some context passing logic and stores that as `unboundStoryFn`.

3. When the story is actually selected in SB's UI (or re-rendered as a result of args changing), `_renderMain` will take that `unboundStoryFn` and render it using `ReactDom.render()`

Steps 1&2 only happen once so the `unboundStoryFunction *is not changing*. That's the bit I don't get (why react thinks it should remount it). My suspicion is that what we are doing wrong is that in step 2. when we "wrap" the component in the decorators we somehow create a situation where a new function is created on each call to the `unboundStoryFn`.

**Comment by tmeasday** [comment]
Wow, I can't believe I had this whole conversation with your @migueloller and had forgotten I'd submitted this PR already: https://github.com/storybookjs/storybook/pull/13049. Sorry to have led us down a wild goose chase.

**Comment by migueloller** [comment]
@tmeasday, hah very nice

**Comment by tmeasday** [comment]
> To fix issue with stories remounting when re-rendering. The issue was the way the decorateStory function created a new "bound" story function each time you called it.

At least my feeling about what the problem was correct 🤣

**Comment by shilman** [comment]
I think we'll probably merge it first thing in 6.3-alpha unless @tmeasday thinks we should jam it into 6.2

**Comment by tmeasday** [comment]
Yeah I guess it would be a bad idea to merge it at this late point given the potential for unintended consequences

**Comment by tmeasday** [comment]
@Varedis 

>  I'm worried about what it may have changed without noticing.

I think if it was going to break something it would be an obvious "missing hook" style of error.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.15 containing PR #14692 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tmeasday** [comment]
Got there in the end!

**Comment by migueloller** [comment]
@tmeasday, awesome! Thanks so much for you work on this ❤️

**Comment by gpxl-dev** [comment]
Hit this issue because I have a story that always seems to re-render when I change one of the props via a control - it's breaking my animation.

I've bumped to 6.3 rc-9 but it's still happening. I'm wondering if it's because I'm using a suspense decorator needed for `react-i18next`, I think:

```jsx
// Suspense needed for i18n.
export const decorators = [
  (story, context) => {
    return (
      <Suspense fallback="Loading...">
        <div className="flex">{story(context)}</div>
      </Suspense>
    );
  },
];
```

**Comment by gpxl-dev** [comment]
@tmeasday - what is the best way to work out why my component is re-mounting? I thought it might be because of the decorator but it happens regardless... Doesn't happen if I change a prop in my actual app, but does when I change it via a storybook control...

**Comment by tmeasday** [comment]
Ok, sounds like a separate issue @gpxl-dev, perhaps worth opening a ticket. See if you can reproduce it down to a simple example.

**Comment by erosenberg** [comment]
@tmeasday @gpxl-dev - I am having the exact same issue on the docs page.
Here is an example with an async call. It infinitely keeps re-rendering on the DocsPage, but works perfectly normally on the Canvas page. I'm trying to render a Story with data using a decorator that makes an API call for the data.

Storybook Version: `v6.4.0-alpha.32`

```
import React, { useEffect, useState } from 'react'
import { useArgs } from '@storybook/client-api'

export default {
  title: 'Example Component',
  component: ExampleComponent,
  decorators: [ExampleDecorator],
  parameters: {
    docs: {
      source: {
        type: 'dynamic',
        excludeDecorators: true,
      },
    },
  },
}

const getBooks = (id) => fetch(`api/books/${id}`).then(res => JSON.parse(res))

const Container = (props) => {
  const { children } = props
  const [data, setData] = useState({ books: [] })

  useEffect(async () => {
    const response = await getBooks
    setData(response)
  }, [])

  return React.cloneElement(children, { data })
}

export const ExampleDecorator = (Story, props) => {
  const [newArgs, updateArgs] = useArgs()

  return (
    <Container>
      {data => {
        const { books } = data
        if (books.length < 0) return

        useEffect(() => {
          updateArgs({
            ...props.args,
            data: books.list,
            title: books.title
          })
        }, [])

        return (
          <>{Story(newArgs)}</>
        )
      }}
    </Container>
  )
}

const ExampleComponent = (args) => <>{args.title}</>

const Template = (args) => <ExampleComponent {...args} />

const ExampleStory = Template.bind({})
ExampleStory.args = {
  title: ''
}
```

**Comment by tmeasday** [comment]
Hi @erosenberg FYI I think for this async data fetching situations, we have [loaders](https://storybook.js.org/docs/react/writing-stories/loaders).

However, I think you are seeing a real bug there. Can you create a reproduction and open a new issue pleasee?

**Comment by shilman** [comment]
@erosenberg - see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce) if it's helpful ☝️

**Comment by shawngustaw** [comment]
Just wanted to chime in to say this was causing me headaches on 6.1.X and upgrading to 6.3.8 fixed it 👍. Big thanks to everyone involved in the fix!

**Comment by dacevedo12** [comment]
It seems this bug still happens in the docs tab

**Comment by fauxparse** [comment]
I'm still seeing this too on 6.4.19

**Comment by tmeasday** [comment]
This issue was for the Canvas tab, I believe https://github.com/storybookjs/storybook/issues/11657 is the best issue for the docs tab.

**Comment by Juice10** [comment]
I'm not using decorators directly but I'm having the same issue in Canvas (and Docs) with Storybook 6.5.4.
Issue with repro repo: https://github.com/storybookjs/storybook/issues/18313

**Comment by Kureyko** [comment]
Same issue in 6.5.6 version and canvas. When using `useArgs` hook and updating state, it breaks animations/transitions.
Tried this https://github.com/storybookjs/storybook/issues/12255#issuecomment-697956943 and also setting `features.modernInlineRender` to `true` and `false`. Nothing solves this issue.

**Comment by tmeasday** [comment]
@Kureyko are you also using Vue? This thread really concerned an issue with React (which is why using JSX `<.../>` in a decorator triggered it). @Juice10 has opened an issue regarding Vue3 which may be relevant to you.

**Comment by chkp-michaelo** [comment]
Still happens on @storybook/react@7.6.10

Switching any tool causes DocsPage / MDX page to completely re-render, even without decorators.

I'd like to demo/test seamless change of theme / language of components without reload - and this issue prevents this.

preview.js:
```
export default {
   globalTypes: {
    theme: {
      name: 'Theme',
      description: 'App Theme',
      defaultValue: 'default',
      toolbar: {
        icon: 'eye',
        items: [
          { value: 'default', title: 'Default' },
          { value: 'dark', title: 'Dark' },
        ],
      },
    }
  }
};
```
