### ISSUE TITLE
Vue 3: Dynamic snippet rendering

### ISSUE THREAD

**Issue by ivanRemotely** [storybookjs/storybook#13917]
**Describe the bug**
When clicking the "View Source" option in the docs tab, the presented code is the template for the story as opposed to the generated Vue code. (See screenshot below)

**To Reproduce**

The issue is present in the vue3 cli example, so you can:

1. Clone, install and run https://github.com/storybookjs/storybook/tree/next/examples/vue-3-cli
2. Open any component
3. Go to the Docs tab
4. Click "Show Source"

**Expected behavior**
The presented panel should show usable Vue code.

**Screenshots**

<img width="1073" alt="Screen Shot 2021-02-15 at 3 09 29 PM" src="https://user-images.githubusercontent.com/79115279/107993445-0e484580-6fa0-11eb-921a-43d972c7add8.png">

**System**

Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0.2
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: 6.2.0-alpha.28 => 6.2.0-alpha.28 
    @storybook/addon-essentials: 6.2.0-alpha.28 => 6.2.0-alpha.28 
    @storybook/addon-links: 6.2.0-alpha.28 => 6.2.0-alpha.28 
    @storybook/addon-storyshots: 6.2.0-alpha.28 => 6.2.0-alpha.28 
    @storybook/vue3: 6.2.0-alpha.28 => 6.2.0-alpha.28 
  npmGlobalPackages:
    @storybook/cli: 6.2.0-alpha.24

**Additional context**
I understand Vue 3 support is still a WIP. I'd be more than happy to help fix the issue if you can point me in the general direction of the problem. Thank you for you time and help!

**Comment by shilman** [comment]
This is available for Vue2 and is implemented here: https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/vue/sourceDecorator.ts

Unfortunately the VNodes are not exposed in the same way in Vue3, so we need to figure out a different approach. @phated can elaborate on this, or perhaps that's enough to get you going @ivanRemotely ?

**Comment by phated** [comment]
That's correct, vnode's no longer contain most (any?) of the information that the sourceDecorator uses. From my deep-dive, it seems that this feature would need to be implemented with a "custom renderer", akin to Vue 3's SSR support. This would be done with https://v3.vuejs.org/api/global-api.html#createrenderer but it looks really complex (and I couldn't figure out how to do it).

**Comment by ivanRemotely** [comment]
Thanks for the info, I'll dig into it. I'm very new at Storybook  so I can't guarantee results but I'll give it a spin nonetheless and see what sticks. I was able to at least get the template source by grabbing `context().render().type.template`, looking into renderers now.

My main question is: What I don't fully understand is what is the scope of this work? Would grabbing the name of the component and the used props be enough? I guess if the component has slots and nested components it would make the code incomplete...

**Comment by phated** [comment]
@ivanRemotely Trying to use template won't really work because many Vue 3 components don't have a template. A vnode can be made up of a template, a render function returning something constructed from `h()` or a setup function that returns a render function. The only way to have true coverage over any type of component is to implement a "string renderer" using `createRenderer` API.

As for the scope, it seems very large to me, as you have to implement everything a vnode can contain. The best "simplified" example of a renderer I could find is https://github.com/vuejs/vue-next/tree/master/packages/runtime-test (which is still quite complex).

**Comment by lee-chase** [comment]
Ooh was about to raise the same issue.

Workaround 1 roll it yourself.
```js
const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { MyButton },
  template: '<my-button @click="onClick" v-bind="$props" />',
});
export const Primary = Template.bind({});
Primary.args = {
  primary: true,
  label: 'Button',
};
Primary.parameters = {
  docs: { source: { code: '<my-button @click="onClick" v-bind="$props" />' } },
};
```

Workaround 2 roll it yourself a bit more thoroughly. Much of which could be extracted to a utility function
```
const templateSourceCode = (templateSource, args, replacing = 'v-bind="$props"') => {
  const propToSource = (key, val) => {
    const type = typeof val;
    switch (type) {
      case 'boolean':
        return val ? key : '';
      case 'string':
        return `${key}="${val}"`;
      default:
        return `:${key}="${val}"`;
    }
  };

  return template.replace(
    replacing,
    Object.keys(args)
      .map((key) => propToSource(key, args[key]))
      .join(' ')
  );
};

export const Primary = Template.bind({});
Primary.args = {
  primary: true,
  label: 'Button',
};
Primary.parameters = {
  docs: { source: { code: templateSourceCode(template, Primary.args) } },
};
```

**Comment by RobineSavert** [comment]
Thanks for the answers but workaround 2 breaks the Canvas tab..

**Comment by seanwuapps** [comment]
> Thanks for the answers but workaround 2 breaks the Canvas tab.. it's also not Vue 3 which uses setup to bind the args/props

Workaround 2 worked for me, make sure your template uses `v-bind="$props"` as that's what the function is looking for. or you can add the third argument when you call the `templateSourceCode` function to replace a different string in your template.

I do look forward to seeing this fixed officially, sorry I don't have enough knowledge in Storybook to create a PR

**Comment by mtorromeo** [comment]
This is my workaround based on the code from @lee-chase.

For simplicity, I made it work by only looking for templates that are surrounded by backticks. The code goes in `.storybook/preview.js` and works globally without any modification required to the stories (easier to remove when this gets eventually fixed).

```js
import dedent from 'ts-dedent';

const templateSourceCode = (
  templateSource,
  args,
  argTypes,
  replacing = ' v-bind="args"',
) => {
  const componentArgs = {};
  for (const [k, t] of Object.entries(argTypes)) {
    const val = args[k];
    if (typeof val !== 'undefined' && t.table && t.table.category === 'props' && val !== t.defaultValue) {
      componentArgs[k] = val;
    }
  }

  const propToSource = (key, val) => {
    const type = typeof val;
    switch (type) {
      case "boolean":
        return val ? key : "";
      case "string":
        return `${key}="${val}"`;
      default:
        return `:${key}="${val}"`;
    }
  };

  return templateSource.replace(
    replacing,
    Object.keys(componentArgs)
      .map((key) => " " + propToSource(key, args[key]))
      .join(""),
  );
};

export const parameters = {
  docs: {
    transformSource(src, ctx) {
      const match = /\b("')?template\1:\s*`([^`]+)`/.exec(src);
      if (match) {
        return templateSourceCode(dedent(match[2]), ctx.args, ctx.argTypes);
      }
      return src;
    },
  }
};
```

**Comment by productdevbook** [comment]
<img width="1094" alt="CleanShot 2021-11-09 at 11 13 34@2x" src="https://user-images.githubusercontent.com/38668796/140886768-d9ff91c2-46fb-44e5-8bb5-e30725393315.png">

some problem

**Comment by mtorromeo** [comment]
@Radouch replacing args with initialArgs is better than nothing, but it doesn't reflect changes to the props made at runtime.

Sadly, vue support in storybook is merely an afterthought and has too many quirks IMO.

**Comment by tiagoskaneta** [comment]
I'm using the following decorator (globally registered) to workaround this issue:

```
import { addons, makeDecorator } from '@storybook/addons'
import { h, onMounted } from 'vue'

// this value doesn't seem to be exported by addons-docs
export const SNIPPET_RENDERED = `storybook/docs/snippet-rendered`

export const withSource = makeDecorator({
  name: 'withSource',
  wrapper: (storyFn, context) => {
    const story = storyFn(context)

    // this returns a new component that computes the source code when mounted
    // and emits and events that is handled by addons-docs
    // this approach is based on the vue (2) implementation
    // see https://github.com/storybookjs/storybook/blob/7064642e1aee7786c77fe735c064c0c29dbcee01/addons/docs/src/frameworks/vue/sourceDecorator.ts
    return {
      components: {
        Story: story
      },

      setup () {
        onMounted(() => {
          try {
            // get the story source from the depths of storybook
            const src = context.originalStoryFn.parameters.storySource.source
            // this extracts the template from the story source
            const match = /\b(["']?)template\1:\s*(["'`])([^\1]+)\2/.exec(src)
            if (match) {
              // generate the source code based on the current args
              const code = templateSourceCode(match[3], context.args, context.argTypes)

              const channel = addons.getChannel()

              const emitFormattedTemplate = async () => {
                const prettier = await import('prettier/standalone')
                const prettierHtml = await import('prettier/parser-html')

                // emits an event  when the transformation is completed
                channel.emit(
                  SNIPPET_RENDERED,
                  (context || {}).id,
                  prettier.format(`<template>${code}</template>`, {
                    parser: 'vue',
                    plugins: [prettierHtml],
                    htmlWhitespaceSensitivity: 'ignore',
                    htmlSingleAttributePerLine: true
                  })
                )
              }
      
              emitFormattedTemplate()
            }
          } catch (e) {
            console.warn('Failed to render code', e)
          }
        })

        return () => h(story)
      }
    }
  }
})
```

The `templateSourceCode` is the same function as already mentioned above. Ugly but it works for now. 

I tried creating a custom renderer for vue as @phated mentioned above to try to include the necessary information but ended up having to copy a lot of code from @vue/runtime-dom - as it doesn't export the necessary methods - so I dropped that for now. May try again at some point.

**Comment by pocka** [comment]
I'm working on the Dynamic snippet rendering feature for Vue 3 in #17295. As I've never used Vue 3 for my projects, I want to hear opinions from Vue 3 users. I'll close the PR if the implementation does not cover common use cases or the PR does not get enough attention (again, I've never used Vue 3, what is "common" is unknown to me).

You can try the feature by editing `examples/vue-3-cli/src/stories/addons/docs/DynamicSnippet.stories.js` at `pocka/feature/vue3-dynamic-code-rendering-experiments` branch.

**Comment by shilman** [comment]
Thanks @pocka !!! I'll try to kick the tires this weekend

**Comment by GustavoFenilli** [comment]
I think the docs from https://storybook.js.org/docs/vue/writing-docs/doc-blocks should be updated with an warning that the vue3 example does not work as intended, with an explanation on how to disable the 'show/hide code'.

**Comment by juzser** [comment]
+1 this feature. 
Vue 3 is vue default version now, so it's really helpful if you can bring this feature to SB. 
Thank you.

**Comment by kasperskov909** [comment]
I was working on a workaround where I would create and mount a new vue instance in memory in the `transformSource` function so that I could extract source code and the generated outer HTML - only to realize that only the initial arguments are available as pointed out by @Radouch, meaning the end result would be static and not influenced by user input. Why was args removed from the `storyContext` argument? Or is it simply a limitation inherited from Vue3?

This feature is vital for the usage of Vue3 in SB. Manually writing docs/source code defeats the whole purpose IMO.

@pocka can you give us an update on your PR? Is it alive and if so, what's the plan?

**Comment by tiagoskaneta** [comment]
@kasperskov909 see https://github.com/storybookjs/storybook/issues/13917#issuecomment-1013019386
It's a bit of hit or miss sometimes so a more permanent approach is definitely required to really use SB with vue3.

**Comment by kasperskov909** [comment]
@tiagoskaneta I mean how do you implement it globally on all stories? I've wrapped stories in markup with decorators before but I can't figure out how to use yours?

**Comment by pocka** [comment]
@kasperskov909 
> @pocka can you give us an update on your PR? Is it alive and if so, what's the plan?

The PR is inactive. As I [stated above](https://github.com/storybookjs/storybook/issues/13917#issuecomment-1024040503), the implementation needs feedback from Vue3 users so that we get an idea of whether it matches users' expectations. Also, we need to find a better way to lookup a story component (https://github.com/storybookjs/storybook/pull/17295#issuecomment-1024363417).

**Comment by kasperskov909** [comment]
@tiagoskaneta are you able to help? See my [comment](https://github.com/storybookjs/storybook/issues/13917#issuecomment-1073962114)

**Comment by tiagoskaneta** [comment]
@kasperskov909. I removed the `transformSource` from the docs parameters in the `main.js`. In the `preview.js`  I have

```
import { withSource } from './withSource'

export const decorators = [
  withSource
]
```

So this will apply the decorator globally.
I am seeing an issue with my solution though, where the transformed code is not being applied when changing pages, only when refreshing the page. So your millage may vary.

**Comment by tiagoskaneta** [comment]
@kasperskov909 https://github.com/tiagoskaneta/vue3-sb-code if you still need some reference.

**Comment by kasperskov909** [comment]
@tiagoskaneta cheers, much appreciated. I'll work on a solution for the page reload/route change problem and post here. After that I will look to the PR for a permanent solution.

**Comment by tiagoskaneta** [comment]
@kasperskov909 using `setTimeout(emitFormattedTemplate, 0);` did work for me to some extend.

**Comment by kasperskov909** [comment]
For anyone reading this. Note that my suggetion for @tiagoskaneta solution with using the `originalStoryFn()`  doesn't work with dynamic content from props if you define your template in your story something like this:
```
const Template = (args) => ({
    components: { XButton, XIcon },
    setup() {
        return { args };
    },
    template: `  
    <x-button v-bind="args">
        <template v-slot:icon-left><x-icon :name="args['icon-left']" />
        </template>
        ${args.default}
    </pd-button>
    `
});
```
`${args}` will be empty. You'll need to send the `args` from the `context` as parameters to the `originalStoryFn()`:

`const src = context.originalStoryFn(context.args).template;`

`args['icon-left']` still won't be parsed. I'm working on a solution. Should be managable in `templateSourceCode()`.

**Comment by danspratling** [comment]
Hey all, I know this is being worked on, but I just wanted to note that the exact same issue is also present in the MDX versions of storybook when working with vue 3

<img width="874" alt="Screenshot 2022-05-26 at 19 07 42" src="https://user-images.githubusercontent.com/11349104/170549373-bbb2a11f-8c92-44af-8080-810bee91e48a.png">

**Comment by mokone91** [comment]
Hi! I have use snippet from @tiagoskaneta it works! 

But i faced with issue that code snipet not highlited properly
<img width="405" alt="image" src="https://user-images.githubusercontent.com/2384641/193249607-c7ebf0e7-a628-47d7-bf0d-4a28018dcaba.png">

is there any ide how its can be fixed?

btw, i have added extra type switch entry to parse object values

`
 const propToSource = (key, val) => {
    const type = typeof val;
    switch (type) {
      case 'boolean':
        return val ? key : '';
      case 'string':
        return `${key}="${val}"`;
      case 'object':
        return `${key}="${JSON.stringify(val).replace(/"(\w+)"\s*:/g, '$1:').replaceAll('"', '\'')}"`; // here
      default:
        return `:${key}="${val}"`;
    }
  };
`

**Comment by vhoyer** [comment]
I may not be completely in the loop here, but, as far as I know, there is planning for porting Vue source generation but only after the the major is released, because for the major 7 release there has been a major refactor of various parts of the code, that being the case as far as I understand, they've paused all progress on other features outside of major 7. That being said I think there's a high chance of this feature becoming available in the near future after the major 7 release

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.29 containing PR #20498 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by kasperskov909** [comment]
Beware that the channel.emit() "hack" does not work in SB version 7. Not really a problem as Vue snippet rendering has been fixed. It is a problem though, if you like me, render other forms of snippets like HTML and Web Components.

**Comment by sttrbl** [comment]
@kasperskov909 

Maybe you know how to get story template initial value now (in SB 7)?  `originalStoryFn(context.args, context).template` doesn't work now

**Comment by kasperskov909** [comment]
@sttrbl origianlStoryFn is now an extension method on the context.
Use `context.originalStoryFn(context.args).template` where context is an argument from the `wrapper` arrow function.

**Comment by JamesCatt** [comment]
> Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.29 containing PR #20498 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb@next upgrade --prerelease
> ```
> 
> Closing this issue. Please re-open if you think there's still more to do.

@shilman I'm still seeing this issue under v7.0.2. I.e., the "show code" button just displays the source code for the story rather than the Vue template. Is there something I'm missing?

**Comment by Spirit04eK** [comment]
@shilman 
Sorry, I don't understand how PR #20498 fix this issue. I have `storybook 7.4.0`. How can I enable pretty source code for Vue 3 component?  
Now, I always see
![image](https://github.com/storybookjs/storybook/assets/32958181/02f7b05c-2c7b-4835-a4a4-7b99b473e8ce)  

I try solution by @tiagoskaneta. It works, but template not re-render after apply/change props.

**Comment by itsJohnnyGrid** [comment]
Hi, for those who struggling with source code rerender absence on args change, here is the solution:

PS: `prettier2` is prettier@2 installed as alias (because prettier@3 doesen't sync).
PS: PS: I also renamed decorator into `vue3SourceDecorator`.

```js
import { addons, makeDecorator } from "@storybook/addons";
import { h, onMounted, watch } from "vue";

export const vue3SourceDecorator = makeDecorator({
  name: "vue3SourceDecorator",
  wrapper: (storyFn, context) => {
    const story = storyFn(context);

    // this returns a new component that computes the source code when mounted
    // and emits an events that is handled by addons-docs
    // watch args and re-emit on change
    return {
      components: {
        story,
      },
      setup() {
        onMounted(() => {
          setSourceCode();
        });

        watch(context.args, () => {
          setSourceCode();
        });

        function setSourceCode() {
          try {
            const src = context.originalStoryFn(context.args).template;
            const code = templateSourceCode(src, context.args, context.argTypes);
            const channel = addons.getChannel();

            const emitFormattedTemplate = async () => {
              const prettier = await import("prettier2");
              const prettierHtml = await import("prettier2/parser-html");

              const formattedCode = prettier.format(code, {
                parser: "html",
                plugins: [prettierHtml],
                htmlWhitespaceSensitivity: "ignore",
              });

              // emits an event when the transformation is completed
              channel.emit("storybook/docs/snippet-rendered", (context || {}).id, formattedCode);
            };

            setTimeout(emitFormattedTemplate, 0);
          } catch (e) {
            // eslint-disable-next-line no-console
            console.warn("Failed to render code", e);
          }
        }

        return () =>
          h("div", { style: `padding: 2rem 1.5rem 3rem 1.5rem;` }, [h(story)]);
      },
    };
  },
});

function templateSourceCode(templateSource, args, argTypes) {
  const componentArgs = {};

  for (const [key, val] of Object.entries(argTypes)) {
    const value = args[key];

    if (
      typeof val !== "undefined" &&
      val.table &&
      val.table.category === "props" &&
      value !== val.defaultValue
    ) {
      componentArgs[key] = val;
    }
  }

  return templateSource
    .replace(
      'v-bind="args"',
      Object.keys(componentArgs)
        .map((key) => " " + propToSource(kebabCase(key), args[key]))
        .join(""),
    );
}

function propToSource(key, val) {
  const type = typeof val;

  switch (type) {
    case "boolean":
      return val ? key : "";
    case "string":
      return `${key}="${val}"`;
    default:
      return `:${key}="${val}"`;
  }
}

function kebabCase(str) {
  return str
    .split("")
    .map((letter, idx) => {
      return letter.toUpperCase() === letter
        ? `${idx !== 0 ? "-" : ""}${letter.toLowerCase()}`
        : letter;
    })
    .join("");
}
```

**Comment by isorna** [comment]
> Hi, for those who struggling with source code rerender absence on args change, here is the solution:
> 
> PS: `prettier2` is `prettier@2` installed as alias (because `prettier@3` doesn't sync). PS: PS: I also renamed decorator into `vue3SourceDecorator`.
> 
> ```js
> import { addons, makeDecorator } from "@storybook/addons";
> import { h, onMounted, watch } from "vue";
> 
> export const vue3SourceDecorator = makeDecorator({
>   name: "vue3SourceDecorator",
>   wrapper: (storyFn, context) => {
>     const story = storyFn(context);
> 
>     // this returns a new component that computes the source code when mounted
>     // and emits an events that is handled by addons-docs
>     // watch args and re-emit on change
>     return {
>       components: {
>         story,
>       },
>       setup() {
>         onMounted(() => {
>           setSourceCode();
>         });
> 
>         watch(context.args, () => {
>           setSourceCode();
>         });
> 
>         function setSourceCode() {
>           try {
>             const src = context.originalStoryFn(context.args).template;
>             const code = templateSourceCode(src, context.args, context.argTypes);
>             const channel = addons.getChannel();
> 
>             const emitFormattedTemplate = async () => {
>               const prettier = await import("prettier2");
>               const prettierHtml = await import("prettier2/parser-html");
> 
>               const formattedCode = prettier.format(code, {
>                 parser: "html",
>                 plugins: [prettierHtml],
>                 htmlWhitespaceSensitivity: "ignore",
>               });
> 
>               // emits an event when the transformation is completed
>               channel.emit("storybook/docs/snippet-rendered", (context || {}).id, formattedCode);
>             };
> 
>             setTimeout(emitFormattedTemplate, 0);
>           } catch (e) {
>             // eslint-disable-next-line no-console
>             console.warn("Failed to render code", e);
>           }
>         }
> 
>         return () =>
>           h("div", { style: `padding: 2rem 1.5rem 3rem 1.5rem;` }, [h(story)]);
>       },
>     };
>   },
> });
> 
> function templateSourceCode(templateSource, args, argTypes) {
>   const componentArgs = {};
> 
>   for (const [key, val] of Object.entries(argTypes)) {
>     const value = args[key];
> 
>     if (
>       typeof val !== "undefined" &&
>       val.table &&
>       val.table.category === "props" &&
>       value !== val.defaultValue
>     ) {
>       componentArgs[key] = val;
>     }
>   }
> 
>   return templateSource
>     .replace(
>       'v-bind="args"',
>       Object.keys(componentArgs)
>         .map((key) => " " + propToSource(kebabCase(key), args[key]))
>         .join(""),
>     );
> }
> 
> function propToSource(key, val) {
>   const type = typeof val;
> 
>   switch (type) {
>     case "boolean":
>       return val ? key : "";
>     case "string":
>       return `${key}="${val}"`;
>     default:
>       return `:${key}="${val}"`;
>   }
> }
> 
> function kebabCase(str) {
>   return str
>     .split("")
>     .map((letter, idx) => {
>       return letter.toUpperCase() === letter
>         ? `${idx !== 0 ? "-" : ""}${letter.toLowerCase()}`
>         : letter;
>     })
>     .join("");
> }
> ```

Any idea on how to implement this decorator? currently using Storybook 7.6.8 with vue3-vite and it's only showing:
```js
[object Promise]
```

**Comment by szymonsterczewski** [comment]
@isorna did you find a way how to use it? Facing the same issue.

**Comment by isorna** [comment]
I had to modify it from the story's render:
`
StoryName = {
  args: ...
  render: (args) => {
    StoryName.parameters.docs.source.code = getCodeTemplate(args);
    components: { MyComponent },
    setup() {
      return { args };
    },
    template: getStoryTemplate(args),
  }
}
`

**Comment by shilman** [comment]
@mikemonteith your example is working as expected for me. do you have a reproduction you can share?

**Comment by mikemonteith** [comment]
Thanks @shilman . I have reproduced it here: https://github.com/mikemonteith/storybook-dynamic-render-testcase

**Comment by shilman** [comment]
Hi @mikemonteith ! I upgraded your project to Storybook 8 using `npx storybook@next upgrade` and it's working fine there. SB8 is in RC and contains TONS more quality of life improvements for Vue users (and everybody!) so my recommendation would be to just upgrade. (It _should_ work in SB7 too, but 🤷 !!!)

**Comment by Astarosa** [comment]
I have the exact same issue as @mikemonteith using storybook 7.6.17.

The problem is that we need this specific syntax when dealing with slots. If you have to render some text as slot value for example, because you don't want to use a props label (for many reasons), you have no choice to use a template.
In React no problem children is a props so you can acces it with the short args object syntax.

I would not be surprised that the same problem occurs with Svelte as well.

I will wait for the v8 release and let you know if the problem is solved on my side.

**Comment by Walnussbaer** [comment]
> Am I missing something here?
> 
> Using a story definition of:
> 
> ```js
> export const Primary = {
>   args: {
>     primary: true,
>     label: 'Button',
>   },
>   render: (args) => {
>     return {
>       components: { MyButton },
>       setup() {
>         return { args };
>       },
>       template: '<my-button v-bind="args" />',
>     }
>   },
> };
> ```
> 
> results in:
> <img alt="image" width="1079" src="https://private-user-images.githubusercontent.com/227467/310972997-9caeb37b-8e0a-4109-8c65-a5d8c873c6db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDQ0MjEsIm5iZiI6MTcxMDk0NDEyMSwicGF0aCI6Ii8yMjc0NjcvMzEwOTcyOTk3LTljYWViMzdiLThlMGEtNDEwOS04YzY1LWE1ZDhjODczYzZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNDE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmZkZjk1ZjYzYThmMTUwOTkxZGI4ZGM3ZWFkMTc2ODdiYmE3NTk2MWY1NDQ1ODFhYzQxZWJmNmE5ODg2ZTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AKkhYu9GfexBuSxp5a_7Tje6PrvG8Um12qymWXC7EqY">
> 
> I expected to see some nicely rendered vue3 code like this:
> <img alt="image" width="1042" src="https://private-user-images.githubusercontent.com/227467/310973675-8808df1b-4413-4547-88b5-90df75fc8505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDQ0MjEsIm5iZiI6MTcxMDk0NDEyMSwicGF0aCI6Ii8yMjc0NjcvMzEwOTczNjc1LTg4MDhkZjFiLTQ0MTMtNDU0Ny04OGI1LTkwZGY3NWZjODUwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNDE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTg4MWQwZjAwYjE4NWJlZWVhODM3OGUxYTFlODdlOTA2NzRhM2IwYzIwNzYwMjI4ZjA5ZjJmZDNmMzU0ZWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DY5x1mS9vluoK5VsfPz8UxtjMoFRhBgG3eqvJA6Hs7A">

Same problem here. Our stories use a simliar format to be able to use the Auto Events Addon for Storybook (https://storybook.js.org/addons/storybook-auto-events)

Our story looks like this:

```
const storyMeta = {
  component: MyComponent,
  title: "common/comment/components/MyComponent",
  parameters: {
    docs: {
      description: {
        component: "Foo"
      },
    },
  },
  render: (args, { events }) => ({
    // events --> https://storybook.js.org/addons/storybook-auto-events
    components: { MyComponent},
    setup() {
      return { args, events };
    },
    template: `
      <my-component v-bind="args" v-on="events"></my-component>
    `,
  }),
} satisfies Meta<typeof MyCComponent>;


```

When trying to display the source code, we get only the args definition and not the HTML code. 

![grafik](https://github.com/storybookjs/storybook/assets/49414693/b2271155-d1f2-4429-aebb-778dff259b28)


Using Storybook 7.6.17. I hope an upgrade to Storybook 8 helps us.

**Comment by itsJohnnyGrid** [comment]
# Here is working example for storybook 8
(we use this set for our UI library, and all works pretty well).

**preview.js**
```js 
import { vue3SourceDecorator } from "./decorators/vue3SourceDecorator";

export default {
  decorators: [vue3SourceDecorator],
  //... (other config)
};
```

**vue3SourceDecorator.js**
```js
import { addons, makeDecorator } from "@storybook/preview-api";
import { h, onMounted, watch } from "vue";

export const vue3SourceDecorator = makeDecorator({
  name: "vue3SourceDecorator",
  wrapper: (storyFn, context) => {
    const story = storyFn(context);

    // this returns a new component that computes the source code when mounted
    // and emits an events that is handled by addons-docs
    // watch args and re-emit on change
    return {
      components: { story },
      setup() {
        onMounted(() => {
          setSourceCode();
        });

        watch(context.args, () => {
          setSourceCode();
        });

        function setSourceCode() {
          try {
            const src = context.originalStoryFn(context.args).template;
            const code = templateSourceCode(src, context.args, context.argTypes);
            const channel = addons.getChannel();

            const emitFormattedTemplate = async () => {
              const prettier = await import("prettier2");
              const prettierHtml = await import("prettier2/parser-html");

              const formattedCode = prettier.format(code, {
                parser: "html",
                plugins: [prettierHtml],
                htmlWhitespaceSensitivity: "ignore",
              });

              // emits an event when the transformation is completed
              channel.emit("storybook/docs/snippet-rendered", {
                id: context.id,
                args: context.args,
                source: formattedCode,
              });
            };

            emitFormattedTemplate();
          } catch (e) {
            // eslint-disable-next-line no-console
            console.warn("Failed to render code", e);
          }
        }

        return () => h("div", { style: `padding: 2rem 1.5rem 3rem 1.5rem;` }, [h(story)]);
      },
    };
  },
});

function templateSourceCode(templateSource, args, argTypes) {
  const componentArgs = {};

  for (const [key, val] of Object.entries(argTypes)) {
    const value = args[key];

    if (
      typeof val !== "undefined" &&
      val.table &&
      val.table.category === "props" &&
      value !== val.defaultValue
    ) {
      componentArgs[key] = val;
    }
  }

  const slotTemplateCode =
    // eslint-disable-next-line vue/max-len
    '<template v-for="(slot, index) of slots" :key="index" v-slot:[slot]><template v-if="args[slot]">{{ args[slot] }}</template></template>';
  const templateDefaultRegEx = /<template #default>([\s\S]*?)<\/template>/g;

  return templateSource
    .replace(/>[\s]+</g, "><")
    .trim()
    .replace(slotTemplateCode, "")
    .replace(templateDefaultRegEx, "$1")
    .replace(
      'v-bind="args"',
      Object.keys(componentArgs)
        .map((key) => " " + propToSource(kebabCase(key), args[key]))
        .join(""),
    );
}

function propToSource(key, val) {
  const type = typeof val;

  switch (type) {
    case "boolean":
      return val ? key : "";
    case "string":
      return `${key}="${val}"`;
    default:
      return `:${key}="${val}"`;
  }
}

function kebabCase(str) {
  return str
    .split("")
    .map((letter, idx) => {
      return letter.toUpperCase() === letter
        ? `${idx !== 0 ? "-" : ""}${letter.toLowerCase()}`
        : letter;
    })
    .join("");
}
```

Example of the story:
**button.stories.js**
```js
import { getArgTypes, getSlotNames } from "vueless/service.storybook";

import UButton from "vueless/ui.button";
import UIcon from "vueless/ui.image-icon";
import URow from "vueless/ui.container-row";
import UGroup from "vueless/ui.container-group";

export default {
  id: "1010",
  title: "Buttons & Links / Button",
  component: UButton,
  args: {
    text: "Button",
  },
  argTypes: {
    ...getArgTypes(UButton.name),
  },
};

const DefaultTemplate = (args) => ({
  components: { UButton },
  setup() {
    const slots = getSlotNames(UButton.name);

    return { args, slots };
  },
  template: `
    <UButton v-bind="args">
      <template v-for="(slot, index) of slots" :key="index" v-slot:[slot]>
        <template v-if="args[slot]">{{ args[slot] }}</template>
      </template>
    </UButton>
  `,
});

const SlotTemplate = (args) => ({
  components: { UButton, UIcon },
  setup() {
    return { args };
  },
  template: `
    <UButton v-bind="args">
      ${args.slotTemplate}
    </UButton>
  `,
});

const VariantsTemplate = (args, { argTypes } = {}) => ({
  components: { UButton, URow },
  setup() {
    return {
      args,
      variants: argTypes.variant.options,
    };
  },
  template: `
    <URow>
      <UButton
        v-for="(variant, index) in variants"
        v-bind="args"
        :variant="variant"
        :text="variant"
        :key="index"
      />
    </URow>
  `,
});

export const Default = DefaultTemplate.bind({});
Default.args = {};

export const variants = VariantsTemplate.bind({});
variants.args = {};

export const slotDefault = SlotTemplate.bind({});
slotDefault.args = {
  slotTemplate: `
    <template #default>
      🤘🤘🤘
    </template>
  `,
};
```
