### ISSUE TITLE
BigInt support in TeleJSON

### ISSUE THREAD

**Issue by JesusTheHun** [storybookjs/storybook#13950]
Currently is you set a component property to an object carrying a `BigInt` the entire storybook stops functioning. The console logs show an error trying to serialize this object.

```
Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    (...)
```

Code sample to help you get the context :

```ts
const invitations = {
  isLoading: false,
  entities: [{
    id: 'd25b99c9-4908-44c6-8ce4-d73768b967c6',
    revision: BigInt(1602168054734520320),
    firstName: 'Foo',
    lastName: 'Bar',
    email: 'foo.bar@provider.com',
  }]
};

export default {
  title: 'Acme/Modules/Invitations/InvitationsList',
  component: InvitationsList,
} as Meta;

const Template: Story<InvitationsListProps> = (args) => <InvitationsList {...args} />;

export const Default = Template.bind({});
Default.args = {
  invitations
};
```

Switching to [json-bigint](https://github.com/sidorares/json-bigint) which is a drop-in replacement would solve this issue in a blink.

**Comment by phated** [comment]
@shilman want me to add this to `telejson`? I think it can just be a `toString` and then put it back into a `BigInt` on parse

**Comment by shilman** [comment]
@phated sure! 🙏

**Comment by j-m** [comment]
The referenced telejson merge was shipped in version 5.3.0 and storybook comes with 5.3.3, I'm still experiencing this issue.

Most of my components have bigint in them, so I can't use Storybook until this is fixed :/ 

<hr/>

I don't know anything about storybook dev, but from a quick look this issue stems from the `stringify` here https://github.com/storybookjs/storybook/blob/c0e4c1ee654f95e6ee00f3c04e883bef7cbcd2b3/lib/components/src/controls/Object.tsx#L280
which would need to include something like 
```JS
JSON.stringify(value, (key, value) => 
  typeof value === "bigint" ? value.toString() + "n" : value
, 2);
```
which stops everything from crashing

<hr/>

I imagine the `parse` in the same file as above 
https://github.com/storybookjs/storybook/blob/c0e4c1ee654f95e6ee00f3c04e883bef7cbcd2b3/lib/components/src/controls/Object.tsx#L251

needs updating to 
```JS
JSON.parse(raw, (key, value) => {
  if (typeof value === "string" && /^\d+n$/.test(value)) {
    return BigInt(value.substr(0, value.length - 1));
  }
  return value;
});
```

There are a few `parse`s and `stringify`s in storybook, but not too many :)

<hr/>

unfortunately, the REJT (React Editable JSON tree) doesn't render the `bigint`s - it looks like REJT limits it's datatypes and, instead of attempting to `.toString()` the value, just defaults to rendering nothing.

<hr/>

+1 to the `json-bigint` recommendation

**Comment by JesusTheHun** [comment]
I still have the issue when I switch to the `Docs` tab. `Canvas` works fine.

**Comment by j-m** [comment]
Whoops, I should've clarified, same here

**Comment by JesusTheHun** [comment]
@phated anything you can do about that ? It would be great if it could be shipped with 6.3.1

**Comment by gaetanmaisse** [comment]
@shilman @ndelangen does it look ok to use `telejson` in `@storybook/components`? For instance here https://github.com/storybookjs/storybook/blob/next/lib/components/src/controls/Object.tsx#L282 or there is a reason to avoid that

**Comment by ndelangen** [comment]
There's no reason not to use it... it's already included in both bundles (preview & manager)

**Comment by JesusTheHun** [comment]
@ndelangen if I can help you in any way to move this forward please let me know.

**Comment by ndelangen** [comment]
@JesusTheHun Yeah, It might be a fairly straight forward addition to telejson:
https://github.com/storybookjs/telejson

WDYT?

**Comment by JesusTheHun** [comment]
well I don't know the internals of `@storybook/components` and how it communicates with the rest of the architecture but yes `telejson` is pretty straight forward. We just need to catch all the places we manipulate json, a good old `Crtl + F` should solve this for us :D

**Comment by bryanchriswhite** [comment]
It looks like it's been a while since the conversation peaked but I'm assuming this isn't fixed and/or released yet as the issue is still open.

I'm using @storybook/component v6.4.19 and I have a component with a couple of `bigint` type props and I think I'm encountering this issue this afternoon.

**Comment by ndelangen** [comment]
The feature has been merged to telejson some time ago:
https://github.com/storybookjs/telejson/pull/56

**Comment by jorgenbuilder** [comment]
Seems that this issue still exists with storybook `6.5.16`. I am running

```
    "@storybook/addon-actions": "^6.5.16",
    "@storybook/addon-essentials": "^6.5.16",
    "@storybook/addon-interactions": "^6.5.16",
    "@storybook/addon-links": "^6.5.16",
    "@storybook/builder-vite": "^0.4.0",
    "@storybook/react": "^6.5.16",
```

And seeing `TypeError: Do not know how to serialize a BigInt` in Storybook. Wondering if there's a way to set the telejson version to avoid this, or something of the sort.

**Comment by ndelangen** [comment]
@jorgenbuilder yeah, most package managers will allow you to override the version. yarn has [resolutions](https://yarnpkg.com/cli/set/resolution), npm has [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides), and pnpm [has this feature as well](https://pnpm.io/package_json#pnpmoverrides)

**Comment by jorgenbuilder** [comment]
@ndelangen seems odd to close the issue when using a BigInt still seems to crash Storybook, or am I missing something?

**Comment by gagarin55** [comment]
Any news on this ? It still not working
