### ISSUE TITLE
Storybook 6.2.0-beta.13 not transforming class properties

### ISSUE THREAD

**Issue by anicholls** [storybookjs/storybook#14197]
I have tried to upgrade to `6.2.0-beta.13` to test the fix for #13608 and I am having babel issues. On start up I’m getting a bunch of `Syntax Error: Missing class properties transform` errors. However, it looks like `@babel/plugin-proposal-class-properties` is still included in the default storybook babel plugins so I don't know why this is appearing all of a sudden. Even if I explicitly add it myself in `main.js` I get the same error. I saw a couple babel changes in the changelog for 6.2, but nothing specifically related to this. It worked fine in `6.1.3`.

**To Reproduce**

1. Upgrade to `@storybook/react@6.2.0-beta.13` with `npx sb upgrade -p`
1. Use class properties in a component that is referenced in a story:

```tsx
class MyComponent extends React.Component<MyComponentProps> {
  static Foo = Bar;
  // ...
}
```

1. Start storybook

**Expected behavior**
The class properties should be transformed and Storybook should start normally.

**Code snippets**
Adding the following to `main.js` does not help.

```tsx
  babel: async options => ({
    ...options,
    plugins: [...options.plugins, '@babel/plugin-proposal-class-properties'],
  }),
```

If you log `options`, you can see that the plugin is already provided so this shouldn't be needed anyway.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200083422930007) by [Unito](https://www.unito.io)

**Comment by shilman** [comment]
@anicholls as a workaround can you try

```js
  babelDefault: async options => ({
    ...options,
    plugins: [...options.plugins, '@babel/plugin-proposal-class-properties'],
  }),
```

we did a bunch of package upgrades in 6.2 so if you're not seeing any specific change about this, i'd bet it's due to something that happened in one of our dependencies?

**Comment by anicholls** [comment]
@shilman Thanks! Switching from `babel` to `babelDefault` doesn't seem to make a difference.

**Comment by mgameover** [comment]
Hi guys,
I faced with the  same issue after upgrading SB v6.1.11 → 6.2.0-rc.0. The suggested solution didn't work for me neither. 

But I was managed to get rid of that error and run storybook by simply installing the following packages: 
```
npm install --save-dev @babel/preset-typescript @babel/preset-env @babel/plugin-proposal-class-properties @babel/plugin-proposal-object-rest-spread
```
and deleting `node_modules\.cache` folder. @anicholls that might work for you.

However I am getting another error right now:
```
inferActionsFromArgTypesRegex was not supported :( !

addArgs.js-generated-other-entry.js:58 addActionsFromArgTypes was not supported :( !

index.js:70 TypeError: Cannot convert undefined or null to object
    at getPrototypeOf (<anonymous>)
    at r.parse (vendors~main.ede20facac207df8bf21.bundle.js:475595)
    at Object.t.parse (vendors~main.ede20facac207df8bf21.bundle.js:475619)
    at Mn (vendors~main.ede20facac207df8bf21.bundle.js:475661)
    at Un (vendors~main.ede20facac207df8bf21.bundle.js:475850)
    at Object.parse (vendors~main.ede20facac207df8bf21.bundle.js:475896)
    at Object.parse (vendors~main.ede20facac207df8bf21.bundle.js:475966)
    at ts (vendors~main.ede20facac207df8bf21.bundle.js:475966)
    at us (vendors~main.ede20facac207df8bf21.bundle.js:475966)
    at vendors~main.ede20facac207df8bf21.bundle.js:475996
error @ index.js:70
```
any thoughts?

**Comment by hanwenbo** [comment]
still

**Comment by shilman** [comment]
It's gotta be something here https://github.com/storybookjs/storybook/pull/13631

<img width="472" alt="Dependencies__6_2_non-breaking_package_upgrades_by_phated_·_Pull_Request__13631_·_storybookjs_storybook" src="https://user-images.githubusercontent.com/488689/111308137-48872e80-8695-11eb-95eb-cceb70c869c1.png">

<img width="494" alt="Dependencies__6_2_non-breaking_package_upgrades_by_phated_·_Pull_Request__13631_·_storybookjs_storybook" src="https://user-images.githubusercontent.com/488689/111308234-6359a300-8695-11eb-826e-ae52d98c8a27.png">

**Comment by mgameover** [comment]
Hi guys,
Yes, the issue is sitting somewhere in dependencies... The following configuration works for me:
```
    "@babel/plugin-proposal-class-properties": "7.12.1",
    "@babel/plugin-proposal-object-rest-spread": "7.12.1",
    "@babel/preset-env": "7.12.11",
    "@babel/preset-typescript": "7.12.7",

    "@storybook/addon-a11y": "6.2.0-rc.1",
    "@storybook/addon-actions": "6.2.0-rc.1",
    "@storybook/addon-docs": "6.2.0-rc.1",
    "@storybook/addon-knobs": "6.2.0-rc.1",
    "@storybook/addon-links": "6.2.0-rc.1",
    "@storybook/addon-storysource": "6.2.0-rc.1",
    "@storybook/addon-viewport": "6.2.0-rc.1",
    "@storybook/addons": "6.2.0-rc.1",
    "@storybook/angular": "6.2.0-rc.1",
    "@storybook/source-loader": "6.2.0-rc.1",
```

What I did is:
1. Completely removed `node_modules` folder and `package-lock.json` file
2. added @babel/* and updated @storybook/* packages from the snippet above
3. ran `npm i` 

No issues so far.

**Comment by shilman** [comment]
Does anybody have a repro repo they can share?

**Comment by PhekPR** [comment]
> Was unable to reproduce this in a fresh project. Does anybody have a repro repo they can share?

I think I managed to reproduce this. I removed and simplified as many files as possible from our design system where we currently have this problem when upgrading and then applied the [Storybook upgrade guide](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade) on it.

Here is the repo:
https://github.com/PhekPR/reprod-storybook-transforming-class-properties

**Comment by cinan** [comment]
I had the same problem with storybook 6.2.0-rc.9. Solved by `yarn dedupe` (yarn 2.4.1)

**Comment by darkowic** [comment]
In my case, I was able to make it work by forcing `"@babel/plugin-proposal-class-properties": "~7.10.1",`. This may be also because we have a babel mess in our monorepo. The babel v7.11 or 7.12 is causing many problems.

**Comment by shilman** [comment]
@PhekPR is there any chance you can update your project to use the Yarn or NPM registry? Currently your lockfile is pointing at `pricerunner.info`, which I don't have access to. Also please remove `eslint-config-pricerunner` which looks unused in the repo and is not public. Many thanks!

**Comment by shilman** [comment]
For those of you running into this, is it fixed if you remove `node_modules` and lockfile and reinstall?

**Comment by PhekPR** [comment]
> @PhekPR is there any chance you can update your project to use the Yarn or NPM registry? Currently your lockfile is pointing at `pricerunner.info`, which I don't have access to. Also please remove `eslint-config-pricerunner` which looks unused in the repo and is not public. Many thanks!

Ah of course. I missed one of them, thought I removed them all. It should now be fixed!

**Comment by shilman** [comment]
@PhekPR hey, the lockfile still points to https://nexus.pricerunner.info, any chance you can fix it? If I blow away the lockfile I believe it solves the problem, but I want to repro if possible.

**Comment by PhekPR** [comment]
> @PhekPR hey, the lockfile still points to https://nexus.pricerunner.info, any chance you can fix it? If I blow away the lockfile I believe it solves the problem, but I want to repro if possible.

Ahh. Of course 🤦‍♂️ 
Yes if I blow away the lockfile I get a different error, probably some changed versions. I tried replacing the registry now in the lock file to the default one. Seems to reproduce the same error. Hope it works on your end now also

**Comment by anicholls** [comment]
@shilman I don't have a stripped down repro repo, but it is reproducible on our component library: https://github.com/Workday/canvas-kit. All dependencies use the yarn registry. Ideally we'd avoid blowing away our lockfile.

**Comment by andreiho** [comment]
@anicholls I fixed it by specifically removing only the `@babel/plugin-proposal-class-properties` entries in the lockfile, then re-installing. Before there were about 5 different version resolutions for that package.

**Comment by artaommahe** [comment]
caught this bug after updating 6.2.0-alpha.24 -> 6.2.5. Nothing from this thread helped 😕 6.2.0-rc.1 works well though

**Comment by artaommahe** [comment]
Debugged a little more and here is my results
- does not really work with `6.2.0-rc.1` for me, i had `@storybook/angular: 6.2.0-alpha.31` that time and it works
- `6.2.0-beta.3` works well
- `6.2.0-beta.4` breaks with `Cannot convert undefined or null to object`

Looks like this pr breaks everything https://github.com/storybookjs/storybook/pull/14047

**Comment by hipstersmoothie** [comment]
Running the following fixed it for me:

```
npx yarn-deduplicate --scopes @babel
```

**Comment by artaommahe** [comment]
I've reproduced `Cannot convert undefined or null to object` error with the new ng application and our real package.json/yarn.lock minimal crop. Somehow it's related to `@storybook/addon-docs` usage

- `yarn install`
- `yarn start-storybook -c src/.storybook`
- see error
- stop storybook server
- comment out this line https://github.com/artaommahe/storybook-issue14197/blob/main/src/.storybook/main.ts#L3
- `yarn start-storybook -c src/.storybook`
- no error

```
    "@storybook/addon-docs": "6.2.8",
    "@storybook/angular": "6.2.8",
```

Tried these things, no one helps
- yarn-deduplicate --scopes @babel
- "@babel/plugin-proposal-class-properties": "~7.10.1" (added to resolutions)
- updating angular libs to last versions
- storybook v6.3.0-alpha.12

**Comment by artaommahe** [comment]
@shilman @hipstersmoothie I've reproduced `Cannot convert undefined or null to object` error with the new ng application and our real package.json/yarn.lock minimal crop. Somehow it looks related to `@storybook/addon-docs` usage

https://github.com/artaommahe/storybook-issue14197

- `yarn install`
- `yarn start-storybook -c src/.storybook`
- see error
- stop storybook server
- comment out this line https://github.com/artaommahe/storybook-issue14197/blob/main/src/.storybook/main.ts#L3
- `yarn start-storybook -c src/.storybook`
- no error

```
"@storybook/addon-docs": "6.2.8",
"@storybook/angular": "6.2.8",
```

Tried these things, no one helped
- npx yarn-deduplicate --scopes @babel
- "@babel/plugin-proposal-class-properties": "~7.10.1" (added to resolutions)
- "@babel/plugin-proposal-class-properties": "7.13.0" (added to resolutions)
- updating angular libs to last versions

But this one helps
- rm yarn.lock
- yarn cache clean
- yarn install

Can't find what lib to update to solve this 😕

**Comment by adambrgmn** [comment]
I just encountered the same issue. And I might not have found a solution but a potential cause of the issue.
Since [v7.14.0 @babel/preset-env automatically includes the class properties transform](https://github.com/babel/babel/blob/main/CHANGELOG.md#v7140-2021-04-29). But in our case we rely on a babel preset with @babel/preset-env v7.12.1, which does not include the class properties transform.

I have very scarce knowledge of how, in our case, yarn works with multiple versions of the same dependency. But running `yarn why @babel/preset-env` shows that I have a few different version in my project.

I could use yarn resolutions and force the version. But this is causing ripples into the other projects.

As mentioned not a solution but a possible cause.

**Comment by shilman** [comment]
Thank you @adambrgmn -- much appreciated!! 🙏

**Comment by Domiii** [comment]
As pointed out by @adambrgmn, the new `preset-env` makes changes how things work with babel. Making sure to have consistent dependencies is a must here.

1. Make sure your `package.json` does not have reference outdated versions
2. Find a consistent way to upgrade all packages in any project setup (it does not (to my best knowledge exist))


Luckily, I have a default nuclear option script for monorepos that I maintain for this special case (using `yarn`). Run it, then somehow re-install (in most cases `yarn install` should be sufficient):
```
"force-uninstall": "yarn run clean && rm -rf ./node_modules ./package-lock.json ./yarn.lock && sh scripts/run-all.sh \"rm -rf ./node_modules ./package-lock.json ./yarn.lock\"",
```

The `scripts/run-all.sh` file looks a little like this:

```sh
set -e # cancel on error
# set -x # verbose echo mode

thisDirRelative=$(dirname "$0")
rootDir=$(node -e "console.log(require('path').resolve('$thisDirRelative/..'))") # get absolute path using node

if [ $# -ne 0 ]; then args=" $*"; else args=""; fi
cmd="$args"

# NOTE: NPM gobbles up flags; need to add the double-dash operator.
# see: https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean

echo "Applying command to all packages: '$cmd'..."

for dirName in packages/*; do 
  folder="$rootDir/${dirName}"
  cd "$folder"
  echo "  $dirName$ $cmd"
  eval "$cmd"
done
```

**Comment by shilman** [comment]
@Domiii Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

I think we've already got a fix in

**Comment by shilman** [comment]
Closing this as fixed in 6.3

**Comment by imbhargav5** [comment]
@shilman Issue still persists in 6.3. 😞

**Comment by ankitghosh** [comment]
It was happening to us also for 6.1 version, upgrading it to 6.3 fixed the issue. @imbhargav5 may be try deleting node_modules and storybook cache and try again.

**Comment by imbhargav5** [comment]
Will try it 👍

**Comment by mayank99** [comment]
> Closing this as fixed in 6.3

@shilman I upgraded to 6.3.4, cleared node_modules and cache, and I was still getting this issue:

```
SyntaxError: \path\to\Component.tsx Missing class properties transform.
  17 |
  18 | export default class Component{
> 19 |   private someProps: ComponentProps[] = [];
```

Adding this to main.js fixed it:
```js
  babel: async (options) => ({
    ...options,
    plugins: [['@babel/plugin-proposal-class-properties', { loose: true }]],
  }),
```

Should I open a new issue?

**Comment by liby** [comment]
Encountered this issue in the latest version.

<details>
<summary>Environment Info</summary>

```
  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
  Binaries:
    Node: 14.15.5 - ~/.nvs/default/bin/node
    Yarn: 1.22.10 - ~/.nvs/default/bin/yarn
    npm: 6.14.11 - ~/.nvs/default/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.3.7 => 6.3.7
    @storybook/addon-actions: ^6.3.7 => 6.3.7
    @storybook/addon-console: ^1.2.3 => 1.2.3
    @storybook/addon-essentials: ^6.3.7 => 6.3.7
    @storybook/addon-links: ^6.3.7 => 6.3.7
    @storybook/addon-storysource: ^6.3.7 => 6.3.7
    @storybook/addons: ^6.3.7 => 6.3.7
    @storybook/builder-webpack5: ^6.3.7 => 6.3.7
    @storybook/manager-webpack5: ^6.3.7 => 6.3.7
    @storybook/react: ^6.3.7 => 6.3.7
```
</details>

<details>
<summary>yarn why @babel/preset-env</summary>

```
❯ yarn why @babel/preset-env
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "@babel/preset-env"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@babel/preset-env@7.15.0"
info Has been hoisted to "@babel/preset-env"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "28.5MB"
info Disk size with unique dependencies: "809.64MB"
info Disk size with transitive dependencies: "1019MB"
info Number of shared dependencies: 144
=> Found "@storybook/builder-webpack5#@babel/preset-env@7.13.12"
info This module exists because "@storybook#builder-webpack5" depends on it.
info Disk size without dependencies: "13.94MB"
info Disk size with unique dependencies: "795.01MB"
info Disk size with transitive dependencies: "1004.36MB"
info Number of shared dependencies: 140
=> Found "@cypress/webpack-preprocessor#@babel/preset-env@7.7.1"
info This module exists because "@bahmutov#add-typescript-to-cypress#@cypress#webpack-preprocessor" depends on it.
info Disk size without dependencies: "264KB"
info Disk size with unique dependencies: "432.71MB"
info Disk size with transitive dependencies: "593.54MB"
info Number of shared dependencies: 119
=> Found "@storybook/addon-docs#@babel/preset-env@7.13.12"
info This module exists because "@storybook#addon-essentials#@storybook#addon-docs" depends on it.
info Disk size without dependencies: "160KB"
info Disk size with unique dependencies: "781.22MB"
info Disk size with transitive dependencies: "990.58MB"
info Number of shared dependencies: 140
=> Found "@storybook/core-common#@babel/preset-env@7.13.12"
info This module exists because "@storybook#react#@storybook#core-common" depends on it.
info Disk size without dependencies: "36.02MB"
info Disk size with unique dependencies: "817.09MB"
info Disk size with transitive dependencies: "1GB"
info Number of shared dependencies: 140
=> Found "@storybook/builder-webpack4#@babel/preset-env@7.13.12"
info This module exists because "@storybook#addon-essentials#@storybook#addon-docs#@storybook#builder-webpack4" depends on it.
info Disk size without dependencies: "36.05MB"
info Disk size with unique dependencies: "817.11MB"
info Disk size with transitive dependencies: "1GB"
info Number of shared dependencies: 140
=> Found "@storybook/csf-tools#@babel/preset-env@7.13.12"
info This module exists because "@storybook#addon-essentials#@storybook#addon-docs#@storybook#csf-tools" depends on it.
info Disk size without dependencies: "1.56MB"
info Disk size with unique dependencies: "782.63MB"
info Disk size with transitive dependencies: "991.98MB"
info Number of shared dependencies: 140
✨  Done in 32.07s.
```
</details>

@mayank99 The method mentioned has given me some help. This is done by explicitly listing the `babel` configuration in the `main.js` file without doing anything else and without `return` anything, which solves my issue.
```js
  // It’s working
  babel: () => {},
  
  // Does not help
  babel: async (options) => ({
    ...options,
    plugins: [['@babel/plugin-proposal-class-properties', { loose: true }]],
  }),
```

**Comment by leotm** [comment]
jus curious why/how https://github.com/storybookjs/storybook/issues/14197#issuecomment-878642379 resolves

when our [babel.config.js](https://github.com/storybookjs/react-native/blob/next-6.0/examples/native/babel.config.js) preset `module:metro-react-native-babel-preset` [main.js](https://github.com/facebook/metro/blob/c9a6fd75937c56645ab9e4d88fa820e63e057cd6/packages/metro-react-native-babel-preset/src/configs/main.js#L23) includes it


```js
// ...
const defaultPluginsBeforeRegenerator = [
  // ...
  [
    require('@babel/plugin-proposal-class-properties'),
    // use `this.foo = bar` instead of `this.defineProperty('foo', ...)`
    {loose: true},
  ],
  // ...
  ...passthroughSyntaxPlugins,
];
// ...
return {
// ...
overrides: [
      // the flow strip types plugin must go BEFORE class properties!
      // there'll be a test case that fails if you don't.
      {
        plugins: [require('@babel/plugin-transform-flow-strip-types')],
      },
      {
        plugins: [
          ...defaultPluginsBeforeRegenerator,
          isHermes ? null : require('@babel/plugin-transform-regenerator'),
          ...defaultPluginsAfterRegenerator,
        ].filter(Boolean),
      },
// ...
```

**Comment by dwwr** [comment]
@shilman Thanks for the snippet!

**Comment by movy** [comment]
For the 3rd time I've come across this problem, it happens about every other time I upgrade packages, especially babel-related stuff. As I keep returning here from googe, will leave this note for future self.

None of the snippets above helped, but what really helps is clearing ALL yarn caches, i.e. local project cache at `.yarn/cache` and also home dir cache at `~/.yarn/berry/cache`. I guess similar applies to  npm.. any `node_modules` up the folder tree will potentially srew something up during upgrade, so all requires wiping out. 

And yes, all babel-* modules better be same exact version, e.g:
```json
    "@babel/core": "^7.22.9",
    "@babel/preset-env": "^7.22.9",
    "@babel/preset-typescript": "^7.22.9",
    "@babel/runtime": "^7.22.9",
    "@babel/runtime-corejs3": "^7.22.9",

```

None of babel plugins apart from `preset-env` were required or helped me to fix this. 

Amazing we're still facing this in 2023, module management should be top-notch by now..
