### ISSUE TITLE
Storybook and angular library: Cannot read property 'selector' of undefined

### ISSUE THREAD

**Issue by krbaio3** [storybookjs/storybook#14828]
**Describe the bug**
When I generate a component in an angular library (ng11), and I am going to use it in a storybook, it shows me the error of: 

`Cannot read property 'selector' of undefined.`

**To Reproduce**
https://github.com/krbaio3/sb-lib-issue

**System**
  System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.2.9 => 6.2.9 
    @storybook/angular: ^6.2.9 => 6.2.9 

**Additional context**

Create an angular project: `ng new design-system --create-application=false --prefix=ds --style=scss`

Create a angular-lib: `ng generate library pattern-lib --prefix=pl`

Change the `name` of `design-system/projects/pattern-lib/package.json` to `@css/pattern-lib`

Change the `path` property of `design-system/tsconfig.json` from `pattern-lib` to `@css/pattern-lib`

Generate the component `ng generate component button --project=pattern-lib`

My button component is:

```ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'pl-button',
  template: `<button [attr.is-pink]="pink" [ngClass]="{'make-pink': pink}">{{label ? "😎 " + label : "No Label provided
  🧐"}}</button>`,
  style: [`
button {
  background: blue;
  padding: 1rem 2rem;
  border-radius: 3px;
  appearance: none;
  border: 0;
  -webkit-appearance: none;
  -moz-appearance: none;
  font-size: 1.5rem;
  letter-spacing: 1px;
  color: white;
  box-shadow: 0 4px 10px rgba(55, 55, 55, 0.3),
    0 6px 35px rgba(55, 55, 200, 0.7);
  cursor: pointer;

  &.make-pink {
    background: #ff00a2;
    box-shadow: 0 4px 10px rgba(55, 55, 55, 0.3),
      0 6px 35px rgb(200 55 150 / 70%);
  }
}`
]
})
export class ButtonComponent {

  @Input('label') label: string | null;
  @Input('pink') pink: boolean;

}
```

Change tsconfig properties of `design-system/projects/pattern-lib/tsconfig.lib.json`. Add this property: 

```json
{
"angularCompilerOptions": {
    "enableIvy": false,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
  },
}
```
Generate the lib dist: `ng build`

Init the storybook with `npx -p @storybook/cli sb init --type angular`

Generate my custom story: `MyButton.stories.ts`

```ts
import {Meta, Story} from '@storybook/angular/types-6-0'

// import { ButtonComponent } from '@css/pattern-lib';

import { ButtonComponent } from 'projects/pattern-lib/src/public-api';

export default {
  title: 'Custom/Buttons',
  component: ButtonComponent,
  argTypes: {
    label: {
      control: 'text'
    }
  }
} as Meta;

const Template: Story<ButtonComponent> = (args: ButtonComponent) => ({
  component: ButtonComponent,
  props: args
});

export const FancyBlueButton = Template.bind({});

FancyBlueButton.args = {
  label: 'Button',
};

export const FancyPinkButton = Template.bind({});

FancyBlueButton.args = {
  label: 'Pink version',
  pink: true,
}
```

I run: `npm run storybook`

If I run with this code, (import { ButtonComponent } from 'projects/pattern-lib/src/public-api';) the storybook works.

But, if I change the import (commented) import { ButtonComponent } from '@css/pattern-lib'; the storybook fails, with the error Cannot read property 'selector' of undefined

![image](https://user-images.githubusercontent.com/22777201/117299832-3ea1d080-ae79-11eb-9d88-8934c8a27b05.png)

**Comment by ebakep** [comment]
any updates ? faced the same issue

**Comment by NatalyIvanova** [comment]
Facing the same issue in mdx.

**Comment by krbaio3** [comment]
Hi @ThibaudAV!

do you need more info?

**Comment by ThibaudAV** [comment]
I started to look at it but several things seem to be misconfigured or suspect in the example repos 

Especially here :

https://github.com/krbaio3/sb-lib-issue/blob/master/tsconfig.json#L15
https://github.com/krbaio3/sb-lib-issue/blob/master/stories/Mybutton.stories.ts#L5

the path should match and it should not point to the `dist` folder no ? 
with
```
      "@css/pattern-lib": ["projects/pattern-lib/src/public-api.ts"]
```
`tsconfig.json`
and 
```
import { ButtonComponent } from '@css/pattern-lib';
```
`Mybutton.stories.ts`

and with this version of storybook `^6.3.0-beta.10`

it works on my side :) 

This configuration also seems suspicious to me 
https://github.com/krbaio3/sb-lib-issue/blob/master/.storybook/tsconfig.json#L2
I wonder if 
```
{
  "extends": "../tsconfig.json",
  "exclude": [
    "../src/test.ts",
    "../src/**/*.spec.ts",
    "../projects/**/*.spec.ts"
  ],
  "include": ["../src/**/*", "../projects/**/*"],
  "files": ["./typings.d.ts"]
}
```
is not enough. but this does not change the way storybook works

**Comment by manbearwiz** [comment]
I ran into this same issue. Storybook is not able to find the component annotations in this function. https://github.com/storybookjs/storybook/blob/7064642e1aee7786c77fe735c064c0c29dbcee01/app/angular/src/client/preview/angular-beta/utils/NgComponentAnalyzer.ts#L128

![image](https://user-images.githubusercontent.com/3688847/124491935-6f1ec180-dd79-11eb-84e1-82c2f21a6a17.png)

**Comment by kroeder** [comment]
@manbearwiz what Storybook and Angular version are you using?

**Comment by manbearwiz** [comment]
I can recreate that error with sb6.3.4 + ng11.2.14. I was able to resolve by using sb6.1.21 + ng11.2.14. Haven't yet bisected to determine which specific version between those introduced the bug.

**Comment by manbearwiz** [comment]
I see a flag was added from sb6.2, `angularLegacyRendering`. Tried enabling that but get the same `Cannot read property 'selector' of undefined` error.

**Comment by KondakovArtem** [comment]
Hello. The same problem. It seems that angular in aot mode is removing the annotation from the component (maybe that's not the point). Important note - the component is included as a package in node_modules

However, in the component itself, this information is present.
I made a simple replacement
```
var ngComponentMetadata = component.decorators[0].args[0]; //NgComponentAnalyzer_1.getComponentDecoratorMetadata(component);
```

![image](https://user-images.githubusercontent.com/12134542/126082112-528308f8-7101-4684-986c-6d8d9a839adb.png)
And its works.

**Comment by varadharajan007** [comment]
Any idea on which upcoming version will have fix for this issue ?

**Comment by saulodias** [comment]
I would submit a patch from  @KondakovArtem observations, but I didn't get past the `yarn test` in the [Contribution Guide.](https://storybook.js.org/docs/react/contribute/code) Maybe because I'm on windows... idk

Anyway, here is an ugly solution if anyone needs a workaround other than accessing the library components directly (not built), which I personally don't like. I want the devs to access components using the *built* library entry points.

`package.json`
```javascript
{
  "scripts": {
    "build-storybook": "npm run docs:json && build-storybook",
    "postinstall": "node postinstall" // <-- add this line
  }
}
```

Create the _postinstall_ script, or add this piece of code if you already have one.
`postinstall.js`
```javascript
var fs = require('fs')

// Workaround to fix function getComponentDecoratorMetadata from storybook 6.3.7.
// See https://github.com/storybookjs/storybook/issues/14828.
// TODO: Remove this as soon as issue is solved in a future release.
var file = './node_modules/@storybook/angular/dist/ts3.9/client/preview/angular-beta/utils/NgComponentAnalyzer.js'
fs.readFile(file, 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace(
    'return (decorators || []).find(function (d) { return d instanceof core_1.Component; });',
    'if (!decorators) return component.decorators[0].args[0]; return (decorators || []).find(function (d) { return d instanceof core_1.Component; });'
  );

  fs.writeFile(file, result, 'utf8', function (err) {
    if (err) return console.log(err);
  });
});
````
**I do recommend you freeze your storybook at 6.3.7 or whatever version your using which doesn't have the fix yet. This might break or break your code in different versions. That replace is working nicely for me.**

**Comment by KondakovArtem** [comment]
Good afternoon, Here is my solution to this problem.. Yes it works on 6.3.7. Again. this is an ugly solution but it works
```
   "storybook:fix": "ts-node -P tsconfig.gen.json storybook-fix.ts",
```


```typescript

import fs from 'fs-extra';
import { resolve } from 'path';
import { createHash } from 'crypto';

const FIX_CONTENT = `"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getComponentDecoratorMetadata = exports.getComponentPropsDecoratorMetadata = exports.isComponent = exports.isDeclarable = exports.getComponentInputsOutputs = void 0;
var core_1 = require("@angular/core");
/**
 * Returns component Inputs / Outputs by browsing these properties and decorator
 */
exports.getComponentInputsOutputs = function (component) {
    var _a, _b;
    var componentMetadata = exports.getComponentDecoratorMetadata(component);
    var componentPropsMetadata = exports.getComponentPropsDecoratorMetadata(component);
    var initialValue = {
        inputs: [],
        outputs: [],
    };
    // Adds the I/O present in @Component metadata
    if (componentMetadata && componentMetadata.inputs) {
        (_a = initialValue.inputs).push.apply(_a, componentMetadata.inputs.map(function (i) { return ({ propName: i, templateName: i }); }));
    }
    if (componentMetadata && componentMetadata.outputs) {
        (_b = initialValue.outputs).push.apply(_b, componentMetadata.outputs.map(function (i) { return ({ propName: i, templateName: i }); }));
    }
    if (!componentPropsMetadata) {
        return initialValue;
    }
    // Browses component properties to extract I/O
    // Filters properties that have the same name as the one present in the @Component property
    return Object.entries(componentPropsMetadata).reduce(function (previousValue, _a) {
        var _b, _c;
        var propertyName = _a[0], value = _a[1][0];
        var valProto = value.prototype || value.__proto__ || {};
        if (value instanceof core_1.Input || valProto.ngMetadataName === 'Input') {
            var inputToAdd = {
                propName: propertyName,
                templateName: (_b = value.bindingPropertyName) !== null && _b !== void 0 ? _b : propertyName,
            };
            var previousInputsFiltered = previousValue.inputs.filter(function (i) { return i.templateName !== propertyName; });
            return __assign(__assign({}, previousValue), { inputs: __spreadArrays(previousInputsFiltered, [inputToAdd]) });
        }
        if (value instanceof core_1.Output || valProto.ngMetadataName === 'Output') {
            var outputToAdd = {
                propName: propertyName,
                templateName: (_c = value.bindingPropertyName) !== null && _c !== void 0 ? _c : propertyName,
            };
            var previousOutputsFiltered = previousValue.outputs.filter(function (i) { return i.templateName !== propertyName; });
            return __assign(__assign({}, previousValue), { outputs: __spreadArrays(previousOutputsFiltered, [outputToAdd]) });
        }
        return previousValue;
    }, initialValue);
};
exports.isDeclarable = function (component) {
    if (!component) {
        return false;
    }
    var decoratorKey = '__annotations__';
    var decorators = Reflect.getOwnPropertyDescriptor(component, decoratorKey)
        ? Reflect.getOwnPropertyDescriptor(component, decoratorKey).value
        : component[decoratorKey];
    return !!(decorators || []).find(function (d) { return d instanceof core_1.Directive || d instanceof core_1.Pipe || d instanceof core_1.Component; });
};
exports.isComponent = function (component) {
    if (!component) {
        return false;
    }
    var decoratorKey = '__annotations__';
    var decorators = Reflect.getOwnPropertyDescriptor(component, decoratorKey)
        ? Reflect.getOwnPropertyDescriptor(component, decoratorKey).value
        : component[decoratorKey];
    return (decorators || []).some(function (d) { return d instanceof core_1.Component; });
};
/**
 * Returns all component decorator properties
 * is used to get all \`@Input\` and \`@Output\` Decorator
 */
exports.getComponentPropsDecoratorMetadata = function (component) {
    var decoratorKey = '__prop__metadata__';
    var propsDecorators = Reflect &&
        Reflect.getOwnPropertyDescriptor &&
        Reflect.getOwnPropertyDescriptor(component, decoratorKey)
        ? Reflect.getOwnPropertyDescriptor(component, decoratorKey).value
        : component[decoratorKey];

    if (!propsDecorators) {
        var propsDecorators = {};
        for (var key in component.propDecorators) {
            if (component.propDecorators.hasOwnProperty(key)){
                propsDecorators[key] = [component.propDecorators[key][0].type]
            }
        }
    }
    return propsDecorators;
};
/**
 * Returns component decorator \`@Component\`
 */
exports.getComponentDecoratorMetadata = function (component) {
    var decoratorKey = '__annotations__';
    var decorators = Reflect &&
        Reflect.getOwnPropertyDescriptor &&
        Reflect.getOwnPropertyDescriptor(component, decoratorKey)
        ? Reflect.getOwnPropertyDescriptor(component, decoratorKey).value
        : component[decoratorKey];
    if (!decorators) {
        return component.decorators[0].args[0];
    }
    return (decorators || []).find(function (d) { return d instanceof core_1.Component; });
};`;

const FIX_FILE = 'NgComponentAnalyzer.js';
const PATH = `node_modules/@storybook/angular/dist/ts3.9/client/preview/angular-beta/utils`;
const CHECK_HASH = ['0be5cd4bed1d63d21a865a14707131ff', 'e0c243b9118ecf34576a8ed5d2f5e238'];

(async () => {
    console.log('Start fixing storybook...');
    let path = resolve(PATH, FIX_FILE);

    if (!fs.existsSync(path)) {
        path = resolve('../../', PATH, FIX_FILE);
        if (!fs.existsSync(path)) {
            throw new Error('Missing fixing file');
        }
    }

    const code = await fs.readFile(path, 'utf-8');

    const hash = createHash('md5').update(code).digest('hex');
    const fixHash = createHash('md5').update(FIX_CONTENT).digest('hex');
    console.log(hash);
    if (hash === fixHash) {
        console.log('Storybook is already fixed');
        return;
    }
    if (!CHECK_HASH.includes(hash)) {
        throw new Error(
            `File ${path} was modified by developers. New hash is ${hash}, prev hash ${CHECK_HASH}`,
        );
    }
    console.log('Fixing is done');
    await fs.writeFile(`${path}_backup`, code);
    await fs.writeFile(path, FIX_CONTENT);
})();

```

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.32 containing PR #15874 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by A-Industry** [comment]
Unfortunately I still run into this issue with Storybook 6.4.0-alpha.32, Angular 12 and webpack 5:

`Cannot read property 'selector' of undefined
TypeError: Cannot read property 'selector' of undefined
    at Object.push../node_modules/@storybook/angular/dist/ts3.9/client/preview/angular-beta/ComputesTemplateFromComponent.js.exports.computesTemplateFromComponent (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:101518:30)
    at prepareMain (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:102991:52)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:102981:39
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:102978:20
    at cleanArgsDecorator (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:103013:12)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:102975:30
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:102978:20
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:103050:17
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:100467:21
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-b72747.iframe.bundle.js:102975:30`

These are the packages that are installed.

`"@storybook/addon-actions": "^6.4.0-alpha.32",
    "@storybook/addon-essentials": "^6.4.0-alpha.32",
    "@storybook/addon-links": "^6.4.0-alpha.32",
    "@storybook/addon-storysource": "^6.4.0-alpha.32",
    "@storybook/angular": "^6.4.0-alpha.32",
    "@storybook/builder-webpack5": "^6.4.0-alpha.32",
    "@storybook/manager-webpack5": "^6.4.0-alpha.32",`

I noticed that internally Storybook or angular seems to be using Typescript 3.9 (See first line of stack trace: ...storybook/angular/dist/ts3.9/) while at project level Typescript 4.3.5 seems to be installed. Could this mismatch be a cause of the issue?

**Comment by saulodias** [comment]
Well, the issue was solved for me on Angular 11 LTS. However after suffering a lot with this issue and other issues I realized trying to consume from a compiled library creates LOTS of issues on storybook, so I'd highly recommend against that. This will only make your workflow unnecessarily more complex. So I edited out some private info from the develpment workflow my team will follow and made it generic for you guys.

![image](https://user-images.githubusercontent.com/35342506/131365188-0812c0fe-8315-45ff-85a5-2e57fbb60cd1.png)

Notice how we are not consuming from a library when it comes to developing the components on storybook. We are consuming directly from the library source code and webpack does a good job at compliling it for the storybook purposes. Unfortunately I can't share the code, but find me on the Storybook Discord server if you need any help.

**Comment by A-Industry** [comment]
Thnx for your reply. We are also running this directly against the source, but no luck with Angular 12.2.2. Previously when we were on Angular 9 with Webpack4 storybook worked correctly.

**Comment by wesself** [comment]
Also still experiencing issues with our angular library project, Any chance this can be opened again?

**Comment by shilman** [comment]
@saulodias @ThibaudAV any ideas why the fix didn't work?

**Comment by wesself** [comment]
So doing tests with a basic component, when loading it into SB directly it works but when loading from the library.  

Component in SB folder
![image](https://user-images.githubusercontent.com/53283809/133801407-20fd39f2-2a4b-42bc-907e-e9969e21830f.png)

Component in Libs
![2021-09-17_10-41](https://user-images.githubusercontent.com/53283809/133801909-656ea494-8394-43d1-89ad-79a069334191.png)

**Comment by Tim-arts** [comment]
Just ran into the issue, the bug is still present in the latest stable release of SB

**Comment by ThibaudAV** [comment]
@wesself coule you provide a reproduction repository ? 🙏
I would like to try to make a fix to this issue but I have trouble reproducing it reliably 😅

**Comment by saulodias** [comment]
You guys will have this and probably other issues if you try to render your library components by pointing to a compiled library. Storybook doesn't work well with that, and like I said, this introduces one unnecessary step to your development workflow. 
[I'm able to reproduce the issue when I import the file directly from the library.](https://github.com/saulodias/my-workspace/tree/storybook-issue-14828)
![image](https://user-images.githubusercontent.com/35342506/133930319-395b3fe4-f87f-4d2a-91d7-2f8253e3cf62.png)

I don't recommend this approach. Please, import your component directly from its source code.
I recommend you create an alias in your root folder `tsconfig.json` for your entry points and point them to the entry point `public-api`. 

```json
{
  "compilerOptions": {
    "paths": {
      "my-lib": ["projects/my-lib/src/public-api"]
    }
  }
}
```
If you import your components from `"my-lib"` like that you shouln't have this problem. 
See: [Angular Library + Storybook](https://dev.to/saulodias/angular-library-storybook-44ma)

**Comment by wesself** [comment]
I was able to get it loaded with the changes you recommended, thx for this sample @saulodias. Is this the recommended way to load libs into Storybook or should this issue ultimately be fixed?

**Comment by Tim-arts** [comment]
I don't think this should be closed because it raises a certain number of questions. First of them (screenshot 1) is that stories files are not useful anymore, it displays the content from the component template (.html), second one is, when I switch between the canvas tab and the documentation tab, the content disappears. Third of them (screenshot 2) is that the "Documentation" becomes now empty (probably unable to automatically load component documentation from parameters)

Screenshot 1:
![image](https://user-images.githubusercontent.com/10064887/134083561-22aa3d20-d027-4680-bc94-2885ee4637f6.png)
![image](https://user-images.githubusercontent.com/10064887/134083538-be8885fe-195c-4756-a258-ed5c3bd303db.png)


Screenshot 2:
![image](https://user-images.githubusercontent.com/10064887/134083477-b0551cfb-c34b-46a0-b3bf-f866771eee23.png)

**Comment by ThibaudAV** [comment]
@wesself yes i would like the repo with the broken version. see if i find something. but i don't promise anything ^^

**Comment by wesself** [comment]
@ThibaudAV here is a sample 
https://github.com/wesself/storybookLibSample

**Comment by ThibaudAV** [comment]
@wesself didn't you forget to push the `.storybook` folder?

**Comment by wesself** [comment]
@ThibaudAV so after cleaning and adding the .stories back was also able to get it working, pushed a new change, not sure what config I have fixed to have this working now. So from me, it's not reproducible now.

**Comment by shilman** [comment]
Thanks @wesself ! Closing this until we get a reproduction 🙏

**Comment by bhanuchhabra7** [comment]
in that case, shouldn't this be in open state instead of close?

**Comment by Tim-arts** [comment]
As indicated by @shilman , it's closed until someone makes a reproduction. I haven't been able to reproduce it since it happened sadly

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.11 containing PR #17156 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.16 containing PR #17156 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by matyprospera** [comment]
Most definitely reproduces on `6.5.0-alpha.44`

**Comment by anuragpathak21** [comment]
I am at Angular 13 with Storoybook 6.4.19 and getting the same error. My stories are outside .stories folder 

![image](https://user-images.githubusercontent.com/50142570/156520106-09e2b008-5fdd-4ec5-b567-8ab788fa8734.png)

**Comment by aaronjones1** [comment]
I'm getting the same error as @anuragpathak21.  Angular `v13.2`, Storybook `v6.4.19`.  My components are in an Angular library within an empty workspace.  The component stories are outside the `.stories` folder.

**Comment by vegardsoerlie** [comment]
I'm getting the same error. Angular `12.2`, Storybook `6.4.20`.

- .storybook
- projects
  - package1
    - .stories file
  - package2
    - .stories file

**Comment by FLAVIOALFA** [comment]
In my own case, I was getting that error because I accidentally installed the dependencies inside the library and just having the node_modules folder throws me that error.

**Comment by StanislavByzov** [comment]
Hi guys, I'm facing the same error (TypeError: Cannot read properties of null (reading 'selectors')) while I'm not using Storybook, just Angular with some packages, so I think the issue can be related to not just Storybook. My current project uses Angular 13.1.2, and the error occurs with one component during local development.

**Comment by amanyzohair** [comment]
> Hi guys, I'm facing the same error (TypeError: Cannot read properties of null (reading 'selectors')) while I'm not using Storybook, just Angular with some packages, so I think the issue can be related to not just Storybook. My current project uses Angular 13.1.2, and the error occurs with one component during local development.

I had the same problem, downgrading npm version worked for me

**Comment by diego-rapoport** [comment]
Hi, I'm facing the same issue with Angular 15.2.0 and storybook 7.0.6

**Comment by computergnome99** [comment]
Facing this issue with `Storybook@7.0.7` and `Angular@15.x` in an Angular Library project. Is there a reliable workaround for this issue with Storybook 7 yet?

**Comment by krutikapatil-bh** [comment]
Hi, I am also facing the same issue with Angular 15.2.6 and Storybook 7.0.7 in an Angular Library project. Kindly provide me with some help to resolve this

**Comment by John-Zimmer** [comment]
I'm able to reliably reproduce this. This issue seems to occur when working in an Angular project with multiple projects in the workspace and dependencies being installed in the individual projects (likely due to npm 7 installing peer dependencies by default now). I'm not sure why the peer dependencies being installed causes this, but hopefully this helps narrow in on the root cause.

Steps to reproduce:

1. Generate a new Angular workspace and generate a new library project (copied from Angular's docs)
`ng new my-workspace --no-create-application`
`cd my-workspace`
`ng generate library my-lib`
2. Initialize storybook
`npx storybook@next init`
3. Run storybook and confirm that everything is working as expected
`npm run storybook`
4. Run `npm install` in the project folder
`cd projects/my-lib`
`npm install`
5. **Run storybook again and the error occurs**
`cd ../../`
`npm run storybook`
6. Remove node_modules and install the project's dependencies using npm 4-6 peer dependency handling
`rm projects/my-lib/node_modules`
`cd projects/my-lib`
`npm install --legacy-peer-deps`
7. Run storybook again and **things are working as expected again**
`cd ../../`
`npm run storybook`

TL;DR: short term fix is to remove node_modules from project folders and install dependencies with the `--legacy-peer-deps` if necessary

**Comment by computergnome99** [comment]
Are there any updates on this since we have repro steps now?

**Comment by computergnome99** [comment]
@ThibaudAV can we remove the `needs reproduction` tag?

**Comment by shilman** [comment]
I don't know the current state of this issue, but I do know that we no longer support Angular 11. If somebody is experiencing this problem with Angular 14, 15, or 16 and Storybook 7.0+, please open an issue with a reproduction and we'd be happy to take a look at it. To create a reproduction, go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by shilman** [comment]
thanks @computergnome99 @tlaukkanen !!!

**Comment by jesse-schein** [comment]
I generally never comment on GitHub but thought to help get this issue raised. 

Using:
NodeJs: 16.20.0
Npm: 8.19.4
Angular: ^16.0.4 (takes 16.1.1)
storybook: ~7.0.22

I got the error listed in the main post during running the storybook website trying to render a component. 

After deleting all package lock and node modules folder, and doing npm install —legacy-peer-reps it fixed all my issues after running storybook.

**Comment by computergnome99** [comment]
@jesse-schein Thanks for the confirmation!

**Comment by DanielAlcaraz** [comment]
@jesse-schein solution works with npm. But in our monorepo we are using pnpm and I cannot find a way to make it work. We are using the last versions of Angular and Storybook with Nx.

**Comment by yayassa-tootelo** [comment]
Hello, I'm facing the same issue with Nx, I tried to use storybook in the libs folder.

Angular: 16.1.0
Storybook: 7.1.0
Nodejs: 16.16.0

**Comment by atropo** [comment]
I can confirm the problem using storybook inside an `angular-workspace` with more projects, the workaround of  @John-Zimmer in https://github.com/storybookjs/storybook/issues/14828#issuecomment-1523875596 works for me.

In my case I don't need to add  flags to `npm`,  but just removing the `node_modules`  from the project directory and doing again a  fresh `npm install` in the workspace root, fixes the problem. Maybe this is related to my version of `npm` being a little older.

My environment is:

```
Storybook 7.3.2 
Angular CLI: 15.2.9
Node: 16.14.2
Package Manager: npm 8.5.0
OS: linux x64
```


I did some debugging and in my case the problem is in the function [computesTemplateFromComponent](https://github.com/storybookjs/storybook/blob/936602d1bba26788298d3aa839e38ddb248c4fbc/code/frameworks/angular/src/client/angular-beta/ComputesTemplateFromComponent.ts#L34):  the `ngComponentMetadata` is undefined.

```js
 const ngComponentMetadata = getComponentDecoratorMetadata(component);  //undefined for me
```


Debugging a little more inside the `getComponentDecoratorMetadata` function:

```js
export const getComponentDecoratorMetadata = (component: any): Component | undefined => {
  const decorators = reflectionCapabilities.annotations(component); //correctly populated

  return decorators.reverse().find((d) => d instanceof Component); //failing  on the test function
};
```

I see the `decorators` const correctly populated with a decorator object, but then the subsequent `find()` returns `undefined`.

I hope this could help identify the problem.

**Comment by EliezerB123** [comment]
I can confirm this error, but I have a bit more information.

We started having this error after moving from Angular 12 to Angular 15, but, well, we ALSO decided to migrate to Storybook v7 at the same time.

So I'm in the unique position to confirm that this happens in both 6.5.16, AND 7.3.2, in the same project, after migrating to Angular 15.

Angular CLI: 15.2.8
Node: 16.20.2
Package Manager: npm 8.19.4
OS: win32 x64

Storybook: Both 6.5.16 AND 7.3.2, (But 7.3.2 only has this issue in a builded PROD, not dev. While 6.5.16 has this issue in DEV too.)

**Comment by manuelkroiss** [comment]
Did anyone successfully solve this issue?

I am facing the same problem as @EliezerB123.

Storybook Version: 7.4.5
Node Version: 18.17.0
npm Version: 8.3.0

Starting storybook in dev mode works perfectly fine. Running a production build and deploying the result files leads to the error.

However, I encountered the following:

When I use a story with the `component` attribute, the error occurs.
Example:
```
export Default {
   component: ButtonComponent
} as Meta;
```

Stories where I used a template instead of the component reference work as expected.
Example:
```
const Template: StoryFn<ButtonComponent> = (args: ButtonComponent) => ({
  props: {
    ...args,
  },
  template: '<ic-one-button></ic-one-button>'
});
```

**Comment by EliezerB123** [comment]
> I can confirm the problem using storybook inside an `angular-workspace` with more projects, the workaround of @John-Zimmer in [#14828 (comment)](https://github.com/storybookjs/storybook/issues/14828#issuecomment-1523875596) works for me.
> 
> In my case I don't need to add flags to `npm`, but just removing the `node_modules` from the project directory and doing again a fresh `npm install` in the workspace root, fixes the problem. Maybe this is related to my version of `npm` being a little older.
> 
> My environment is:
> 
> ```
> Storybook 7.3.2 
> Angular CLI: 15.2.9
> Node: 16.14.2
> Package Manager: npm 8.5.0
> OS: linux x64
> ```
> 
> I did some debugging and in my case the problem is in the function [computesTemplateFromComponent](https://github.com/storybookjs/storybook/blob/936602d1bba26788298d3aa839e38ddb248c4fbc/code/frameworks/angular/src/client/angular-beta/ComputesTemplateFromComponent.ts#L34): the `ngComponentMetadata` is undefined.
> 
> ```js
>  const ngComponentMetadata = getComponentDecoratorMetadata(component);  //undefined for me
> ```
> 
> Debugging a little more inside the `getComponentDecoratorMetadata` function:
> 
> ```js
> export const getComponentDecoratorMetadata = (component: any): Component | undefined => {
>   const decorators = reflectionCapabilities.annotations(component); //correctly populated
> 
>   return decorators.reverse().find((d) => d instanceof Component); //failing  on the test function
> };
> ```
> 
> I see the `decorators` const correctly populated with a decorator object, but then the subsequent `find()` returns `undefined`.
> 
> I hope this could help identify the problem.

From what I can tell, this seems to be the likely source of the bug. As per https://stackoverflow.com/a/63937850/5243309, it seems that **instanceof Component** will fail when using two `node_modules/@angular` folders, or when a library has its own instance of  **node_modules/@angular** because it has Angular listed in `dependencies` instead of `peerDependencies`. ( [link](https://stackoverflow.com/a/22004559/5243309) )

The solution seems to be to replace all the code using `instanceOf` with something like this:
 `decorator.constructor.name === factory.prototype.constructor.name`.

**Comment by Alex85651** [comment]
Hi, i'm facing the same problem. It occurs only when running a production build and only on one story :'(
Here are the versions I use : 

Storybook Version: 7.4.6
Node Version: 18.16.0
npm Version: 9.5.1
Angular 16.2

**Comment by grankovsky** [comment]
HI, found solution.  
Change imports for stand alone
from:  import { Component } from '@xm-ngx/components/component';
to : import { Component } from './component.component';

I hope this could help.

**Comment by valentinpalkovic** [comment]
> @atropo
> 
> > I did some debugging and in my case the problem is in the function [computesTemplateFromComponent](https://github.com/storybookjs/storybook/blob/936602d1bba26788298d3aa839e38ddb248c4fbc/code/frameworks/angular/src/client/angular-beta/ComputesTemplateFromComponent.ts#L34): the `ngComponentMetadata` is undefined.
> > ```
> >  const ngComponentMetadata = getComponentDecoratorMetadata(component);  //undefined for me
> > ```
> > 
> > 
> > Debugging a little more inside the `getComponentDecoratorMetadata` function:
> > ```
> > export const getComponentDecoratorMetadata = (component: any): Component | undefined => {
> >   const decorators = reflectionCapabilities.annotations(component); //correctly populated
> > 
> >   return decorators.reverse().find((d) => d instanceof Component); //failing  on the test function
> > };
> > ```
> > 
> > 
> > I see the `decorators` const correctly populated with a decorator object, but then the subsequent `find()` returns `undefined`.
> > I hope this could help identify the problem.
> 
> From what I can tell, this seems to be the likely source of the bug. As per https://stackoverflow.com/a/63937850/5243309 and https://stackoverflow.com/q/41587865/5243309, it seems that _**instanceof Component**_ will fail when using two `node_modules/@angular` folders, or when a library has its own instance of `node_modules/@angular` because it has Angular listed in `dependencies` instead of `peerDependencies`. ( [link#3](https://stackoverflow.com/a/22004559/5243309) )
> 
> Which explains why **npm install --legacy-peer-deps** appears to solve the issue for some people.
> 
> The solution seems to be to replace all the code using `instanceOf` with something like this: `decorator.constructor.name === factory.prototype.constructor.name`.

Initially, I thought the same, and I already prepared a PR to not use `instanceof` checks but instead rely on some type of information, which is appended during compilation to the decorator properties.

I talked to the Angular core team, and they warned me to support this case since having multiple instances of Angular in the application is a quite broken state, and many things are likely to malfunction. The only valid solution, therefore, is to guarantee that the application loads one instance of Angular.

So I thought about the reproduction, which was provided by @John-Zimmer. When creating an Angular workspace with some applications and libraries, each library might have its dependencies, which we must install. Since npm's default behavior is to install peer dependencies, a `npm install` in a library folder will install `@angular/core` as well. This is NOT what we want. The whole workspace should refer to one `@angular/core` instance, not multiple ones. So what happens if we use npm's workspace feature here? Let's go to the root package.json and let's add all project folders as a workspace:

```json
{
 ...
 "workspaces": [
    "projects/*"
  ],
 ...
}
```

Then, an `npm install` **is only executed at the root level**, never in a library folder. Dependencies will automatically be hoisted to the root's node_module folder, and conflicting dependencies will remain in the lib's node_modules. This guarantees that we always have one instance of `@angular/core` installed and used. Does anyone know, whether there are some arguments against this approach?

NX, on the other side, has its [Single Version policy](https://nx.dev/concepts/more-concepts/dependency-management#single-version-policy), where all dependencies are installed in the root folder. Hence, the mentioned issues with having multiple instances of Angular should never occur. But there seem to be issues, and I am curious whether @yayassa-tootelo or @DanielAlcaraz could provide a reproduction with nx. But also, in this case, I suggest using the workspace feature of the used package manager to resolve this issue.

**Comment by RenaudC5** [comment]
Since the [7.5.0 storybook release](https://github.com/storybookjs/storybook/releases/tag/v7.5.0), it is now possible to use the `argsToTemplate` method for property and event Bindings. 

In our case, this has been used as a workaround for the error `Cannot read property 'selector' of undefined`.

Here is an example of how to use it : 

```js
import { argsToTemplate } from '@storybook/angular';

export const ExampleRange: Story = {
  name: 'État par défaut',
  args: {
    stringProp: "Foo",
    objectProp : {foo: "bar"},
    arrayProp: ["Foo", "Bar"]
  },
  render: (args) => ({
    props: args,
    template: `<app-my-input ${argsToTemplate(args)}></app-my-input>`
  })
};
```
Using this on all of our stories seems to work, and we haven't found any problems at the moment.

Hope this helps.

---
Versions : 
Storybook Version: 7.5.0
Node Version: 18.16.0
npm Version: 9.5.1
Angular 16.2.8

**Comment by leogouveia** [comment]
> > @atropo
> > > I did some debugging and in my case the problem is in the function [computesTemplateFromComponent](https://github.com/storybookjs/storybook/blob/936602d1bba26788298d3aa839e38ddb248c4fbc/code/frameworks/angular/src/client/angular-beta/ComputesTemplateFromComponent.ts#L34): the `ngComponentMetadata` is undefined.
> > > ```
> > >  const ngComponentMetadata = getComponentDecoratorMetadata(component);  //undefined for me
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Debugging a little more inside the `getComponentDecoratorMetadata` function:
> > > ```
> > > export const getComponentDecoratorMetadata = (component: any): Component | undefined => {
> > >   const decorators = reflectionCapabilities.annotations(component); //correctly populated
> > > 
> > >   return decorators.reverse().find((d) => d instanceof Component); //failing  on the test function
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I see the `decorators` const correctly populated with a decorator object, but then the subsequent `find()` returns `undefined`.
> > > I hope this could help identify the problem.
> > 
> > 
> > From what I can tell, this seems to be the likely source of the bug. As per https://stackoverflow.com/a/63937850/5243309 and https://stackoverflow.com/q/41587865/5243309, it seems that _**instanceof Component**_ will fail when using two `node_modules/@angular` folders, or when a library has its own instance of `node_modules/@angular` because it has Angular listed in `dependencies` instead of `peerDependencies`. ( [link#3](https://stackoverflow.com/a/22004559/5243309) )
> > Which explains why **npm install --legacy-peer-deps** appears to solve the issue for some people.
> > The solution seems to be to replace all the code using `instanceOf` with something like this: `decorator.constructor.name === factory.prototype.constructor.name`.
> 
> Initially, I thought the same, and I already prepared a PR to not use `instanceof` checks but instead rely on some type of information, which is appended during compilation to the decorator properties.
> 
> I talked to the Angular core team, and they warned me to support this case since having multiple instances of Angular in the application is a quite broken state, and many things are likely to malfunction. The only valid solution, therefore, is to guarantee that the application loads one instance of Angular.
> 
> So I thought about the reproduction, which was provided by @John-Zimmer. When creating an Angular workspace with some applications and libraries, each library might have its dependencies, which we must install. Since npm's default behavior is to install peer dependencies, a `npm install` in a library folder will install `@angular/core` as well. This is NOT what we want. The whole workspace should refer to one `@angular/core` instance, not multiple ones. So what happens if we use npm's workspace feature here? Let's go to the root package.json and let's add all project folders as a workspace:
> 
> ```json
> {
>  ...
>  "workspaces": [
>     "projects/*"
>   ],
>  ...
> }
> ```
> 
> Then, an `npm install` **is only executed at the root level**, never in a library folder. Dependencies will automatically be hoisted to the root's node_module folder, and conflicting dependencies will remain in the lib's node_modules. This guarantees that we always have one instance of `@angular/core` installed and used. Does anyone know, whether there are some arguments against this approach?
> 
> NX, on the other side, has its [Single Version Policy](https://nx.dev/concepts/more-concepts/dependency-management#single-version-policy), where all dependencies are installed in the root folder. Hence, the mentioned issues with having multiple instances of Angular should never occur. But there seem to be issues, and I am curious whether @yayassa-tootelo or @DanielAlcaraz could provide a reproduction with nx. But also, in this case, I suggest using the workspace feature of the used package manager to resolve this issue.

Is there a repo or a stackblitz/codesandbox with working code?

**Comment by AmbrosiaDevelopments** [comment]
The only thing that fixed it for me was switching `enableProdMode` to `false` in angular.json. Not amazing but quick work around until this gets figured out for sure. I'm not using a monorepo either.

**Comment by shaman-apprentice** [comment]
Maybe it helps anyone: I had the same issue. I have a Angular mono repo for libraries and storybook installed at the root. I accidentally run `npm i` once within a library folder, so that I had a *node_modules* folder at the root and within the library. Deleting *node_modules* within the library and only run `npm i` at root fixed it for me.

**Comment by antoine-carruana** [comment]
Is a solution in the works ? 
The only solution working for us actually is to set a template instead of using the component directly, but it's not a solution for long term.

Versions :
Storybook Version: 7.6.7
Node Version: 18.18.2
npm Version: 9.8.1
Angular 17.0.8

**Comment by ranceroxas** [comment]
This is still happening. Tried a few options
Node v18.18.0
Storybook: 7.6.4

1. Created a Angular library v16.2.0. Added a simple button. 
2. Created a sample app that uses the library from #1. Added storybook here. 
3. Imported the button via dependencies.
4. Encountering this issue when deployed

1. Created a Angular library v16.2.0. Added a simple button. 
2. Added storybook here
3. Imported the button via file dependencies.
4. Still encountering this issue when deployed

Another clue: It works in my local for both approach.

**Comment by valentinpalkovic** [comment]
@ranceroxas Have you read my comment here: https://github.com/storybookjs/storybook/issues/14828#issuecomment-1770336203. Please make sure that only one instance of Angular is used in the monorepo. Otherwise, disabling prod mode like mentioned in other comments might help as well.

**Comment by vasa-ae** [comment]
We intended to use Storybook in our organization, but we have this problem. After trying "fixes" in this thread we have not been able to solve it.

Versions: Angular 17 and Storybook 8

**Comment by valentinpalkovic** [comment]
@vasa-ae, Can you tell me how your repository structure looks? If you use a mono repo, does [this comment](https://github.com/storybookjs/storybook/issues/14828#issuecomment-1770336203) help? The main issue is that you likely have multiple Angular instances in your repository in different node_module folders. Ensure that just one instance of `@angular` dependencies is installed, and then the issue should go away.

**Comment by vasa-ae** [comment]
@valentinpalkovic, Thanks for the quick response! 

Our whole Storybook portal is designed this way:

We have a standalone Angular library that contains our components; published on a private npm registry as **@aea/angular-shared-library**.

We keep our stories within the library, like this:

![image](https://github.com/storybookjs/storybook/assets/168075460/d42e7567-a5a9-4c82-8a51-5c6f851c3eef)

Then we have Angular application that has Storybook and library installed: 

```json
"dependencies": {
    "@aea/angular-shared-library": "^0.0.1",
    ...
  },
  "devDependencies": {
    ...
    "@chromatic-com/storybook": "^1.3.3",
    "@storybook/addon-essentials": "^8.0.8",
    "@storybook/addon-interactions": "^8.0.8",
    "@storybook/addon-links": "^8.0.8",
    "@storybook/angular": "^8.0.8",
    "@storybook/blocks": "^8.0.0-beta.4",
    "@storybook/test": "^8.0.0-beta.4",
   ...
    "storybook": "^8.0.8",
    "typescript": "~5.3.2",
    ...
  }
```

Installed library looks like this: 

![image](https://github.com/storybookjs/storybook/assets/168075460/06719b85-4392-492e-a1e6-829c129c85ff)

And we have configured Storybook to load stories from library, like this:

_.storybook/main.ts_:
```javascript
import type { StorybookConfig } from "@storybook/angular";

const config: StorybookConfig = {
  stories: [
    "../node_modules/@aea/angular-shared-library/stories/**/*.stories.ts"
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@chromatic-com/storybook",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook/angular",
    options: {},
  },
};

export default config;
```
_.storybook/tsconfig.json_:

```json
{
  "extends": "../tsconfig.app.json",
  "compilerOptions": {
    "types": ["node"],
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true
  },
  "exclude": ["../src/test.ts", "../src/**/*.spec.ts"],
  "include": [
    "./preview.ts",
    "../node_modules/@aea/angular-shared-library/stories/**/*.stories.ts"
  ],
  "files": ["./typings.d.ts"]
}
```

These are the scripts:

```json
...
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "storybook": "ng run storybook-front:storybook",
    "build-storybook": "ng run storybook-front:build-storybook",
    "docker": "npm run build-storybook && docker compose up --build",
    "http-server-test": "npm run build-storybook && http-server storybook-static"
  }
...
```
Script **"storybook"** works fine and running scripts **"docker"** and **"http-server-test"**, we get error:

![image](https://github.com/storybookjs/storybook/assets/168075460/5cac827a-cc4f-4669-8332-14ed246b0c7d)

We have the same approach for the Vue.js library and everything works fine there.

I believe that solution from comment you are mentioning does not apply for this situation, anyway we have tried removing peerDependencies (just because we are trying everything) from library and nothing has changed (as expected).

**Comment by valentinpalkovic** [comment]
Thank you for providing all this information.

First, I want to clarify that loading stories from "node_modules" isn't officially supported. We often explicitly exclude running builder plugins/loaders for `node_module` files because of performance reasons.

Second, could you run `npm why @angular/core` or `yarn why @angular/core`, depending of your package manager.

Could you also initialize Storybook in your library `@aea/angular-shared-library` instead? Does the error disappear if you would do so (also for testing purposes)?

**Comment by Jintus** [comment]
Hi everyone, I'm facing the same issue using Angular@16 pnpm workspace and StoryBook@8.

I have made a reproductible repo [here](https://codesandbox.io/p/devbox/bug-sb-pnpm-angular-2h2dqf?file=%2Fpackages%2Fangular-lib%2Fpackage.json%3A17%2C33&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwkdvq9800063b6hx4bmkcxf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwkdvq9700023b6hqh63zxk2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwkdvq9700043b6h0bu6m1ml%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwkdvq9800053b6hm5tce5kf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwkdvq9700023b6hqh63zxk2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkdvq9700013b6hrcgv5lgq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwkfn3ue00023b6goc7cd12l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A33%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A33%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackages%252Fangular-lib%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwkdvq9700023b6hqh63zxk2%2522%252C%2522activeTabId%2522%253A%2522clwkfn3ue00023b6goc7cd12l%2522%257D%252C%2522clwkdvq9800053b6hm5tce5kf%2522%253A%257B%2522id%2522%253A%2522clwkdvq9800053b6hm5tce5kf%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clwkdvq9700043b6h0bu6m1ml%2522%253A%257B%2522id%2522%253A%2522clwkdvq9700043b6h0bu6m1ml%2522%252C%2522activeTabId%2522%253A%2522clwkdw91d002q3b6hesi9re3r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkdvq9700033b6hdt8zhbx3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clwkdw91d002q3b6hesi9re3r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwkdw93z00kddblxgmup4esu%2522%257D%252C%257B%2522id%2522%253A%2522clwkg0zk200bp3b6ggyc0n156%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwkg0zkr01f4dblx9aktg3r1%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

To try it out:
1. `pnpm install` on the root workspace
2. `cd apps/angular-storybook`
3. `pnpm serve`

Hope it will help for debugging.

@valentinpalkovic I have make sure that in the Angular UI lib angular is a peerDependency and with a `pnpm why @angular/core` ther is only 1 version of angular installed 16.2.12.

I have no error in dev it's only with the builded storybook. (You can try `pnpm storybook`)

**Comment by Jintus** [comment]
> Hi everyone, I'm facing the same issue using Angular@16, pnpm workspace and StoryBook@8.
> 
> I have made a reproductible repo [here](https://codesandbox.io/p/devbox/bug-sb-pnpm-angular-2h2dqf).
> 
> To try it out:
> 
> 1. `pnpm install` on the root workspace
> 2. `pnpm start`
> 
> Hope it will help for debugging.
> 
> @valentinpalkovic I have make sure that, in the Angular UI lib, angular is a peerDependency and with a `pnpm why @angular/core` there is only 1 version of angular installed 16.2.12.
> 
> I have no error in dev it's only with the builded storybook. (You can try `pnpm storybook`)

Are this exemple good for debugging what is the error ?

**Comment by elvinachang** [comment]
Having the same issue here, any workarounds on this?
Using storybook 8.2.9 with angular 16.
It def look like its the build of storybook that is giving this error for components used within stories.

**Comment by jdavis-software** [comment]
@valentinpalkovic did you ever get this to work with `pnpm` and `storybook` ?

**Comment by robatwilliams** [comment]
Adding latest error message for ease of finding this when searching:

> Cannot read properties of undefined (reading 'selector')

**Comment by sdragos1** [comment]
I have had the same issue with `Angular 19.2` and `Storybook 8.6`.

The error comes often from angular mono repo setups. Because you can have nested node_modules, on at the root of your workspace and another inside your library, so Storybook has trouble resolving the component metadata.

What you can do is use dependency hoisting.

Depending on what package manager you use you can usually configure dependency hoisting.

Example for `pnpm`

```
packages:
  - "ng-ui"

hoistPattern:
  - "*"
```

This way you centralize the dependencies at the root of your workspace
