### ISSUE TITLE
Type information missing for "loaders"

### ISSUE THREAD

**Issue by Bilge** [storybookjs/storybook#15406]
**Describe the bug**
There is no TypeScript type information for any of the [loaders](https://storybook.js.org/docs/html/writing-stories/loaders) feature.

In particular, there is no `loaders` property on `Story`/`BaseStory`.

**To Reproduce**
```ts
export const Default = Template.bind({});
Default.loaders = createLoaders();
```

>TS2339: Property 'loaders' does not exist on type 'Story '.

**System**
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.106
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9
    @storybook/addon-essentials: ^6.2.9 => 6.2.9
    @storybook/addon-links: ^6.2.9 => 6.2.9
    @storybook/html: ^6.2.9 => 6.2.9
```

**Comment by dohomi** [comment]
@Bilge I am facing the same issue, is there a workaround for this?

**Comment by phbernard** [comment]
A workaround, based on [Storybook example](https://storybook.js.org/docs/react/writing-stories/loaders#fetching-api-data):

    type TodoItemStory = {
      loaders?: (() => Promise<any>)[];
    } & Story<TodoItemProps>;

    export const Primary: TodoItemStory = (args: TodoItemProps, { loaded: { todo } }) => <TodoItem {...args} todo={todo} />;

    Primary.loaders = [
      async () => ({
        todo: (await fetch('https://jsonplaceholder.typicode.com/todos/1')).json(),
      }),
    ];

**Comment by shilman** [comment]
This is being fixed in 6.4 by @tmeasday

**Comment by BigglesZX** [comment]
Did this make it into the release? Struggling to find any more information about this today. Thanks!

**Comment by tmeasday** [comment]
@BigglesZX `@storybook/addons` exports a `LoaderFunction` type.

You can also use the `LoaderFunction` exported by `@storybook/csf` (although you need to use a canary release `0.0.2--canary.87bc651.0` -- for no particular reason, we should sort that out @shilman). The CSF version is parameterized by framework (exported by framework package) and args for the story.

**Comment by BigglesZX** [comment]
@tmeasday Thanks!

I was eventually able to satisfy TypeScript by using `as` to type the data being injected via `loaders`. I'm new to TypeScript so not sure if this is considered good practice. I had been looking for a way to extend the definition of `StoryContext` used by `ComponentStory` to include the custom properties from `loaders`/`loaded`, but I failed. Here's my story, simplified a bit:

```jsx
const client = ...;

export default {
    title: 'MyComponent',
    component: MyComponent,
} as ComponentMeta<typeof MyComponent>;

const Template: ComponentStory<typeof MyComponent> = (args, { loaded: { data }}) => {
    return <MyComponent {...args} data={data as MyDataType} />
};
Template.loaders = [
    async () => ({
        data: (await client.fetch()) as Promise<MyDataType>,
    }),
];
```

This works, but if there's a better way to type this, I'd be interested to hear it.

**Comment by ryanrouleau** [comment]
Any update on this?  There's also this open issue: https://github.com/storybookjs/storybook/issues/14282 . 

I see `loaded` here on `StoryContext` in csf
```typescript
export declare type StoryContext<TFramework extends AnyFramework = AnyFramework, TArgs = Args> = StoryContextForLoaders<TFramework, TArgs> & {
    loaded: Record<string, any>;
    abortSignal: AbortSignal;
    canvasElement: HTMLElement;
};
```

and `loaders` here:

```typescript
export declare type BaseAnnotations<TFramework extends AnyFramework = AnyFramework, TArgs = Args> = {
    decorators?: DecoratorFunction<TFramework, TArgs>[];
    parameters?: Parameters;
    args?: Partial<TArgs>;
    argTypes?: Partial<ArgTypes<TArgs>>;
    loaders?: LoaderFunction<TFramework, TArgs>[];
    render?: ArgsStoryFn<TFramework, TArgs>;
    play?: PlayFunction<TFramework, TArgs>;
};
```

but still receive this error:
```
Type '{ (args: Args, { loaded: store }: StoryContext<ReactFramework, Args>): Promise<Element>; loaders: LoaderFunction<ReactFramework, Args>[] | undefined; }' is not assignable to type 'AnnotatedStoryFn<ReactFramework, Args>'.
  Type '{ (args: Args, { loaded: store }: StoryContext<ReactFramework, Args>): Promise<Element>; loaders: LoaderFunction<ReactFramework, Args>[] | undefined; }' is not assignable to type 'ArgsStoryFn<ReactFramework, Args>'.
    Type 'Promise<Element>' is missing the following properties from type 'ReactElement<unknown, string | ((props: any) => ReactElement<any, any> | null) | (new (props: any) => Component<any, any, any>)>': type, props, keyts(2322)
```

when doing:

```tsx
import { Meta, Story } from '@storybook/react';
import React from 'react';

export default {
  title: 'omitted',
  component: omitted,
} as Meta;

const Template: Story = async (args, { loaded: store }) => (
 ... omitted for privacy
  );

Template.loaders = [async () => ({ store: (await omitted())})];

export const Default = Template.bind({});

```

**Comment by unional** [comment]
Type assertion (`as`) is fine in this case. 

What you can do further is to create a type alias, so it will save you some typing:

```ts
type Story = ComponentStory<typeof MyComponent> & { loaders: ... }
```

so you can use the same `Story` type in each of your story in the file.

**Comment by valentinpalkovic** [comment]
Thanks for the report! The legacy `Story` type was removed in v8 in favour of `StoryObj`/`StoryFn`, which properly type the `loaders` field on a story. Closing as resolved by the CSF3 type rewrite.
