### ISSUE TITLE
Error: received updateGlobals but was unable to determine the source of the event, received updateGlobals but was unable to determine the source of the event

### ISSUE THREAD

**Issue by ChaitanyaKrishnaPappala** [storybookjs/storybook#15659]
**Describe the bug**
When I try to build and serve the build version of storybook this issue arises.

**To Reproduce**
Run 
1. `build-storybook -c .storybook -o .storybook-static`
2. `npx serve -s .storybook-static`

**System**
Mac OS 
Dependencies:
```
  "react": "^16.13.1",
 "@storybook/addon-actions": "^6.1.20",
 "@storybook/addon-essentials": "^6.1.20",
 "@storybook/addon-knobs": "^6.1.20",
 "@storybook/addon-links": "^6.1.20",
 "@storybook/node-logger": "^6.1.20",
 "@storybook/preset-create-react-app": "^3.1.6",
 "@storybook/react": "^6.2.9"

```

Below is my `.storybook/main.js` file

```
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-create-react-app',
  ],
};
```

**Additional context**
Throws the following errors in the console,
1. received sharedStateChanged-manager-storybook/viewport but was unable to determine the source of the event
2. received updateGlobals but was unable to determine the source of the event

![Screen Shot 2021-07-22 at 2 40 06 PM](https://user-images.githubusercontent.com/15865071/126699639-9cc8f506-babb-44b4-9b92-4537a284b70e.png)

**Comment by Jordan-Eckowitz** [comment]
Yeah seeing the same issue when I deploy Storybook. When I run it locally using `serve` it works fine. Could this be a CORS issue? Perhaps something related to this: https://github.com/storybookjs/storybook/issues/11892

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by lorcannn** [comment]
I had the same problem when i am run:
1. `npm run build-storybook`
2. `serve -s storybook-static`

![image](https://user-images.githubusercontent.com/56643497/147449242-4c2652c7-81e0-40c9-82a9-c5f1f297b661.png)

🥳🥳The finally I resolve this problem when i am run:
`serve storybook-static`

**Comment by Jordan-Eckowitz** [comment]
@shilman I think you can close this ticket - was an AWS problem addressed in this closed issue: https://github.com/storybookjs/storybook/issues/12538#issuecomment-701894383

**Comment by mduenias** [comment]
FYI I am getting this error when using this recipe: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#reordering-docs-tab-first

```
export const parameters = {
  previewTabs: { 'storybook/docs/panel': { index: -1 } },
}
```
Both when running storybook locally and with the static build. 
I would love to have a way to reorder the tabs without causing this warnings.

**Comment by designmatty** [comment]
I'm unfortunately seeing the same as @mduenias. For now, I'm just going to remove the reordering logic until it's fixed.

**Comment by somenickname** [comment]
@mduenias @designmatty  could you check that changes in `previewTabs` also trigger double bundle loading?

**Comment by HyperLife1119** [comment]
> FYI I am getting this error when using this recipe: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#reordering-docs-tab-first
> 
> ```
> export const parameters = {
>   previewTabs: { 'storybook/docs/panel': { index: -1 } },
> }
> ```
> 
> Both when running storybook locally and with the static build. I would love to have a way to reorder the tabs without causing this warnings.

Same problem, still exists in Storybook 6.5.9.

![image](https://user-images.githubusercontent.com/41798664/178405734-b9f92bf6-85cf-4017-97c4-27cb1c05c9d3.png)

**Comment by usrrname** [comment]
Seems this still exists!

**Comment by mogamogua** [comment]
it still exists 🥲

**Comment by AlexeyTeterin** [comment]
Still same issue on v 7.6.10

**Comment by JuhG** [comment]
We have the same issue on `8.0.5`.
Created a discussion that's basically the same issue: https://github.com/storybookjs/storybook/discussions/26941

After some digging, this seems to be the issue: https://github.com/storybookjs/storybook/blob/38dfc50b7a4e2d4d1e59356362a461b1aa18c3cd/code/lib/channels/src/postmessage/index.ts#L219
When `getEventSourceUrl` is called, `event.source` is undefined, but - in our case - only sometimes. So maybe some race condition?

@shilman can we reopen this?

**Comment by MustafaLeanTech** [comment]
Also having the same issue on storybook v8.2.1

**Comment by JuhG** [comment]
There's now a reproduction repo in the related discussion: https://github.com/storybookjs/storybook/discussions/26941#discussioncomment-10221221

It shows that it doesn't show the error on simple story pages, but produces it on more complicated pages 100% of time - while using the exact same components, just rendering the same thing multiple times. So - as @nukemonk points out - it does seem like a race condition.

Repo: https://github.com/nukemonk/globals_toolbar_error
Chromatic: https://66ac97cfb6985b19d709445f-szcqjhqcuf.chromatic.com/?path=/docs/example-button-with-problem--docs

![Screenshot 2024-08-02 at 10 49 51](https://github.com/user-attachments/assets/c0ae4c28-e828-4fb7-b4ab-f38d0d0afe58)

**Comment by ChristopherJohnson25** [comment]
Having the same issue on 8.6.0

**Comment by techvsi-catvu** [comment]
Still having issue on **8.3.6**
