### ISSUE TITLE
Cannot anchor to headings in MDX documentation

### ISSUE THREAD

**Issue by gyfchong** [storybookjs/storybook#18395]
**Describe the bug**
When appending the ID of a heading to the URL ie. storybook.com#story-heading the page does not anchor down to the target heading.

Additionally, previously each heading had the ability to click an icon to create a link to the heading, this is now gone. Any manual links also do not work.

**To Reproduce**
[Repo](https://github.com/gyfchong/storybook-anchor-issue-repro)
[Deploy](https://taupe-moonbeam-5b3c12.netlify.app/?path=/story/button--page)

**System**
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.6 => 6.5.6 
    @storybook/addon-docs: ^6.5.6 => 6.5.6 
    @storybook/addon-essentials: ^6.5.6 => 6.5.6 
    @storybook/addon-interactions: ^6.5.6 => 6.5.6 
    @storybook/addon-links: ^6.5.6 => 6.5.6 
    @storybook/builder-webpack5: ^6.5.6 => 6.5.6 
    @storybook/manager-webpack5: ^6.5.6 => 6.5.6 
    @storybook/node-logger: ^6.5.6 => 6.5.6 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.6 => 6.5.6 
    @storybook/testing-library: ^0.0.11 => 0.0.11

**Comment by luchn49** [comment]
I've been running into the same issue. There's no longer an icon when trying to hover over the headers.

You can see it: https://storybookjs.netlify.app/official-storybook/?path=/story/addons-docs-markdown-docs--page.

---

Not sure if that's an issue from storybook or MDX?

**Comment by gyfchong** [comment]
> Not sure if that issue is from storybook or MDX?

Yeah not sure either, seems it only affects MDX type docs, and not the auto generated one from Storybook.

**Comment by sag1v** [comment]
Can confirm the issue is still there on v6.5.9.

As @gyfchong mentioned in [this comment](https://github.com/storybookjs/storybook/issues/18395#issuecomment-1149398392)

> ... seems it only affects MDX type docs, and not the auto generated one from Storybook

I'm also experiencing the same behavior

**Comment by binh710** [comment]
Hey all, does anyone know which version of SB should I downgrade to to avoid this first? We need to release our SB to production this week.

**Comment by sag1v** [comment]
@shilman Is this being investigated by the team? I think its quite a critical issue because documentations without a way to share links is pretty poor experience.
A [similar issue](https://github.com/storybookjs/storybook/issues/16918) was resolved not so long ago BTW. 

references
https://github.com/storybookjs/storybook/pull/17134
https://github.com/storybookjs/storybook/pull/17080

**Comment by binh710** [comment]
> Hey all, does anyone know which version of SB should I downgrade to to avoid this first? We need to release our SB to production this week.

We have to downgrade SB back to 6.4.19 for now as our project rely heavily on mdx docs. Hopefully this get fix soon. :)

Cheers guys, thanks for maintaining SB! It's an awesome product <3

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.16 containing PR #18740 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by sag1v** [comment]
@shilman Thanks 😊
Does this fix only apply for the v7 alpha release? We have the same issue on v6 as well (not sure if it's related to the mdx2 feature)

**Comment by ggascoigne** [comment]
I know it's a big request, but is there any chance of getting this fix backported to v6, it looks like v7 is a bit of a ways away still so it's not clear that that is a viable solution right now.

**Comment by gyfchong** [comment]
Bumped to `v6.5.10` and added the span, but [Storybook ToC](https://storybook.js.org/addons/storybook-docs-toc) still won't work, seems they scan the MDX title id's for their anchors.

Have tried manually adding the # to the URL to anchor down but also doesn't work. Not sure what else to try.

**Comment by yannbf** [comment]
Hey @gyfchong thanks for the update. As mentioned in the comment which closed this issue, the fix was added to Storybook 7.0 alpha. I don't think it's been ported back to 6.5, which must be the reason it didn't work for you. @shilman do you think we can patch this back?

**Comment by gyfchong** [comment]
> Hey @gyfchong thanks for the update. As mentioned in the comment which closed this issue, the fix was added to Storybook 7.0 alpha. I don't think it's been ported back to 6.5, which must be the reason it didn't work for you. @shilman do you think we can patch this back?

Ah I misunderstood the merged branch, I thought that was for storybook, but it was someone else's repo! 😅

**Comment by lazysergey** [comment]
@yannbf could we have this patch in `v6` as well? as `7.0.0` is not released yet

@binh710 could you advice on how to downgrade please?
I tried to change versions in `package.json` manually with `yarn install --force` 
![image](https://user-images.githubusercontent.com/30532154/183889243-7a6cf17e-d48c-42da-a388-5389f07275b1.png)
but seems I have to downgrade `babel-loader` as well? having this error:

```
WARN Force closed preview build
ERR! TypeError: (0 , _coreCommon.getStorybookBabelConfig) is not a function
```

also I've tried  `npx storybook@6.4.19 init` and `yarn storybook@6.4.19 --automigrate` without luck

thanks in advance 👍

**Comment by DzmVasileusky** [comment]
I am also thinking that essential bug fixes should be included into current stable version not a future one

**Comment by sag1v** [comment]
I totally agree. Maybe @shilman can reconsider?

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.13-alpha.0 containing PR #18740 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by sag1v** [comment]
Awesome @shilman thanks! 🙏  Do you want us to test this before you release the next official 6.x.x version?

**Comment by lazysergey** [comment]
@sag1v how do you upgrade it to exact version? `npx sb upgrade --prerelease` command actually installs `7.0.0-alpha.34`:

![Screenshot 2022-09-30 at 10 37 32 PM](https://user-images.githubusercontent.com/30532154/193344486-8ee0dd3b-b3c6-4d18-ae03-3758d517f38e.jpg)

**Comment by sag1v** [comment]
> @sag1v how do you upgrade it to exact version? `npx sb upgrade --prerelease` command actually installed `7.0.0-alpha.34` for me:
> 
> ![Screenshot 2022-09-30 at 10 37 32 PM](https://user-images.githubusercontent.com/30532154/193344486-8ee0dd3b-b3c6-4d18-ae03-3758d517f38e.jpg)
> 
> 
> 
> 

Yeah I know its a shame 😞 i had to manually upgrade each package. That's why it didn't work out at first because i forgot to upgrade some packages.

**Comment by lazysergey** [comment]
@sag1v tyvm, resolved for me, hope this will go live soon 🤞 

what I did:
I've changed version manually and did `yarn install`:
![image](https://user-images.githubusercontent.com/30532154/193348549-1cbc6a6a-1fbf-452c-81e0-5b42f9e85bf0.png)

For me it  still gives `id: undefined` for mdx documents that import `*.md`, but it finally works fine for mdx 🎉 🎉 🎉 
![image](https://user-images.githubusercontent.com/30532154/193348808-82a3f443-d811-4435-b5a9-32134a22cdd6.png)


if for someone this version still doesn't work, I would check the following:

1. confirm that `preset.js` has [PR #18740](https://github.com/storybookjs/storybook/pull/18740/files) change:
![image](https://user-images.githubusercontent.com/30532154/193348698-8bd69e1f-a516-407d-8202-2e2dedc8d662.png)

2. Check which `id` do you get in `mdx.js` where storybook decides if it should render `Header` or `HeaderWithOcticonAnchor`:
![image](https://user-images.githubusercontent.com/30532154/193348478-019f8dfc-4b6d-40a5-a1cf-07c4b49f757f.png)

That's how I debugged before realising that I'm checking `md` and then tried `mdx` which worked 🙂

**Comment by sag1v** [comment]
@shilman Hey 👋  
When do we expect to see version 6.5.13 released?

**Comment by shilman** [comment]
@sag1v sorry this fell off my radar. I want to get one more thing patched back to 6.5 in the next day or two and then will release. Thanks for your patience!

**Comment by sag1v** [comment]
@shilman Thanks! 
Just heads-up, it turns out that `npx sb upgrade --prerelease` is installing version 7.x and not 6.x. Is there away to pass a major version or is it a bug that needs to get fixed?

**Comment by shilman** [comment]
We're going to change upgrade to allow you to specify an npm tag. For now it's just the way it works:

- upgrade = latest stable
- upgrade --prerelease = latest prerelease

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.13 containing PR #18740 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by valpioner** [comment]
Same here, header links don't work using 8.4.5

**Comment by sag1v** [comment]
are you able to migrate to latest version?
