### ISSUE TITLE
[Bug]: Invalid binary plist error with Storybook 7 beta

### ISSUE THREAD

**Issue by robcaldecott** [storybookjs/storybook#20992]
### Describe the bug

I am trying to update a NextJS project to use Storybook 7 beta but when I attempt to run `pnpm storybook` on my Macbook M1 I am greeted with the following error:

```
/Users/me/Projects/next-tailwind/node_modules/.pnpm/bplist-parser@0.2.0/node_modules/bplist-parser/bplistParser.js:55
    throw new Error("Invalid binary plist. Expected 'bplist' at offset 0.");
          ^

Error: Invalid binary plist. Expected 'bplist' at offset 0.
    at Object.exports.parseBuffer (/Users/me/Projects/next-tailwind/node_modules/.pnpm/bplist-parser@0.2.0/node_modules/bplist-parser/bplistParser.js:55:11)
    at Module.defaultBrowserId (file:///Users/me/Projects/next-tailwind/node_modules/.pnpm/default-browser-id@3.0.0/node_modules/default-browser-id/index.js:27:22)
    at async module.exports (/Users/me/Projects/next-tailwind/node_modules/.pnpm/@aw-web-design+x-default-browser@1.4.88/node_modules/@aw-web-design/x-default-browser/src/detect-mac.js:4:14)
 ELIFECYCLE  Command failed with exit code 1.
```

This is using the `@storybook/react-webpack5`.

### To Reproduce

```shell
Repo here: https://github.com/robcaldecott/next-tailwind/tree/storybook-7-beta


git clone git@github.com:robcaldecott/next-tailwind.git -b storybook-7-beta
cd next-tailwind
pnpm install
pnpm storybook
```

If you do not have `pnpm` then install with `npm install -g pnpm`. However, a separate project that uses `npm` exhibits the same issue so I don't think `pnpm` is a factor here.
```


### System

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-essentials: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-interactions: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-links: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/react: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/react-webpack5: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by zhyd1997** [comment]
I have no such issue, but got the build error: 

<img width="968" alt="Screenshot 2023-02-08 at 11 32 53" src="https://user-images.githubusercontent.com/31362988/217422969-c295a9b7-4882-461b-9cd5-a7a9caccd925.png">

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.2
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-essentials: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-interactions: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-links: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/react: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/react-webpack5: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
```

`pnpm` version: `7.16.1`, `7.26.3`

**Comment by robcaldecott** [comment]
I can also duplicate this by creating a brand new NextJS project and then adding Storybook.

```
pnpm create next-app [answer Yes to all prompts]
cd my-app
npx storybook@next init [answer Yes to all prompts]
pnpm storybook
```

**Comment by zhyd1997** [comment]
Interesting 🤔 , I encountered this issue, always `Enter` when initialize the app.

<img width="1017" alt="Screenshot 2023-02-08 at 17 42 18" src="https://user-images.githubusercontent.com/31362988/217493190-6377199b-cd3e-4b37-a0d8-c92a11f54b3f.png">

**Comment by robcaldecott** [comment]
The issue seems to be parsing my `/Users/robert.caldecott/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist` file in the `default-browser-id` package. That file exists but the package does not like it.

I think it's looking for the default browser. I have Chrome, Safari and Firefox installed with Chrome as the default.

**Comment by robcaldecott** [comment]
If I edit `node_modules/default-browser-id/index.js` and change it to look like this:

```js
export default async function defaultBrowserId() {
	return "com.google.chrome"
}
```

Then it works and Storybook starts.

**Comment by zhyd1997** [comment]
It works well when I commented all of css import statements on component files.

<img width="436" alt="Screenshot 2023-02-08 at 17 52 09" src="https://user-images.githubusercontent.com/31362988/217495645-64c79c3e-c17b-4ed0-88d7-e4c609867796.png">

**Comment by zhyd1997** [comment]
> If I edit `node_modules/default-browser-id/index.js` and change it to look like this:
> 
> ```js
> export default async function defaultBrowserId() {
>   return "com.google.chrome"
> }
> ```
> 
> Then it works and Storybook starts.

This because you didn't use `bplist` package which broke at the beginning.

**Comment by zhyd1997** [comment]
@robcaldecott could you find this file on your mac :eyes:

`~/Library/Preferences/com.apple.LaunchServices.plist`

**Comment by zhyd1997** [comment]
> Interesting 🤔 , I encountered this issue, always `Enter` when initialize the app.
> 
> <img alt="Screenshot 2023-02-08 at 17 42 18" width="1017" src="https://user-images.githubusercontent.com/31362988/217493190-6377199b-cd3e-4b37-a0d8-c92a11f54b3f.png">

I need to run this command `pnpm add -D style-loader css-loader postcss-loader` and then `pnpm run storybook` works.

**Comment by robcaldecott** [comment]
@zhyd1997 Here it is

**~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LSHandlers</key>
	<array>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>com.jamf.connect</string>
			<key>LSHandlerURLScheme</key>
			<string>jamfconnect</string>
		</dict>
		<dict>
			<key>LSHandlerContentType</key>
			<string>public.url</string>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleViewer</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleViewer</key>
			<string>com.google.chrome</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>com.google.chrome</string>
			<key>LSHandlerURLScheme</key>
			<string>http</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>starleaf.breeze2</string>
			<key>LSHandlerURLScheme</key>
			<string>starleaf</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>starleaf.breeze2</string>
			<key>LSHandlerURLScheme</key>
			<string>breeze</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>com.google.chrome</string>
			<key>LSHandlerURLScheme</key>
			<string>mailto</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>com.google.chrome</string>
			<key>LSHandlerURLScheme</key>
			<string>https</string>
		</dict>
		<dict>
			<key>LSHandlerContentType</key>
			<string>public.html</string>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>com.google.chrome</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>us.zoom.xos</string>
			<key>LSHandlerURLScheme</key>
			<string>zoomphonecall</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>com.tinyspeck.slackmacgap</string>
			<key>LSHandlerURLScheme</key>
			<string>slack</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>com.docker.docker</string>
			<key>LSHandlerURLScheme</key>
			<string>docker-desktop</string>
		</dict>
		<dict>
			<key>LSHandlerPreferredVersions</key>
			<dict>
				<key>LSHandlerRoleAll</key>
				<string>-</string>
			</dict>
			<key>LSHandlerRoleAll</key>
			<string>com.google.chrome</string>
			<key>LSHandlerURLScheme</key>
			<string>webcal</string>
		</dict>
	</array>
</dict>
</plist>
```

**Comment by zhyd1997** [comment]
this file is not a valid `plist` file, this is mine:

<img width="778" alt="Screenshot 2023-02-08 at 19 06 42" src="https://user-images.githubusercontent.com/31362988/217512727-271a00dd-4755-4bfb-909a-665543049e01.png">

**Comment by robcaldecott** [comment]
@zhyd1997 how odd. I think XML is also valid format though? I'm using MacOS Monterey 12.6.1 but it is managed by my IT department. I wonder if others in my org have the same issue, I will check. I doubt I will be the last person to come across this.

**Comment by zhyd1997** [comment]
@robcaldecott what's the buffer logged?

**Comment by robcaldecott** [comment]
@zhyd1997 I've fixed it!

- I opened Safari and made it my default browser. File stayed as XML.
- I opened Chrome and made it my default browser. File was converted to binary.
- `pnpm storybook` now runs!

Thank you so much for your help ⭐

**Comment by connorjs** [comment]
The "toggle default browser, open it, and try again" worked for me too for anyone else coming across this issue... no idea why. (I use Safari/Safari Technology Preview as my default browser.)

**Comment by dima-getselectstar** [comment]
`--no-open` helps here. So this is definitely BE which needs to be fixed on storybook side. 
`storybook dev -p 6006 --no-open -s public`

**Comment by aaron-nance** [comment]
Issue still happens even in Storybook 8. Toggleing default browser is the simplest fix.

**Comment by SoxFace** [comment]
Thanks @aaron-nance - same issue. Toggling default browser in your system settings works. The other suggestions earlier in this thread, did not.

**Comment by borracciaBlu** [comment]
### The Solution
```
cp ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist ~/com.apple.launchservices.secure.plist.bkp
cp ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist ~/com.apple.launchservices.secure.plist.bkp2
 plutil -convert binary1 ~/com.apple.launchservices.secure.plist.bkp
cp ~/com.apple.launchservices.secure.plist.bkp ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist
```

### How to recreate the bug?
```
cp ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist ~/com.apple.launchservices.secure.plist.bkp
plutil -convert xml1 ~/com.apple.launchservices.secure.plist.bkp
cp ~/com.apple.launchservices.secure.plist.bkp ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist
```

### Why is this happening?
Long story short a package is expecting `~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist` to be in binary format and instead it gets an xml.

How it comes?
In [`code/core/src/core-server/utils
/open-in-browser.ts`](https://github.com/storybookjs/storybook/blob/25d6ece29a10b2f528e2df58c215c33dbe0595f8/code/core/src/core-server/utils/open-in-browser.ts) we use [@aw-web-design/x-default-browser@1.4.126](https://github.com/storybookjs/storybook/blob/25d6ece29a10b2f528e2df58c215c33dbe0595f8/code/core/package.json#L461C6-L461C38) which uses `default-browser-id@3.0.0` that is an old version. Latest is `default-browser-id@5.0.0`.

### The strange case of @aw-web-design/x-default-browser

Now, the crazy part is that `@aw-web-design/x-default-browser` on npm is on version 1.4.126 and use `default-browser-id@3.0.0` but on [github](https://github.com/The-Code-Monkey/TechStack/blob/main/packages/x-default-browser/package.json) it says that latest version is `"1.3.299"` (which is not listed in npm though) and it does use `default-browser-id@5.0.0`.

Also on github it says `This repository was archived by the owner on Mar 22, 2025. It is now read-only.`
