### ISSUE TITLE
Upgrade to TS5.0

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#21792]
Long term, we'll want to:

- Upgrade storybook's monorepo to TypeScript 5 (this is a maintenance task)
- Ensure storybook is compatible with 5.0.0 and the generators we're compatible with (this will sort of happen automatically because generators will publish new versions and we'll start using them after ~24h)
- Maybe add an internal sandbox to test compatibility with TypeScript 5, but I'm not sure there's a need for this.
- Maybe investigate if the new language features might be useful for storybook or it's users.

_Originally posted by @ndelangen in https://github.com/storybookjs/storybook/issues/21276#issuecomment-1486345258_

**Comment by psychobolt** [comment]
For anyone who wants to use multiple array extends in TS 5.0, you'll get a error when running `storybook build` or `storybook dev`

```sh
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
```

Issue was fixed in https://github.com/dividab/tsconfig-paths/pull/245 , but is still a issue until we can upgrade esbuild-register with the fix. I managed to set a resolution with the precompiled package update in my project. https://github.com/psychobolt/vite-storybook-boilerplate/tree/main/packages/esbuild-register
``` json
  "resolutions": {
    "esbuild-register": "workspace:*"
  }
```

**Comment by naporin0624** [comment]
I applied the following patch in [patch-package](https://www.npmjs.com/package/patch-package) and it worked!

https://gist.github.com/naporin0624/70c2e00f791d881895910a8f2cdb3026

**Comment by matthew-dean** [comment]
I'm getting `Error: did not recognize object of type "TSSatisfiesExpression"` in `vue-docgen-api` after upgrading to the latest Storybook version (7.0.25). How do I fix this?

**Comment by matthew-dean** [comment]
Storybook 7 for Vite does not yet support TypeScript 5 (specifically the `satisfies` keyword). It has an old dependency on `vue-docgen-api`.

I was able to fix this by overriding Storybook in my `package.json`:
```json
  "overrides": {
    "vue-docgen-api": "^4.73.0"
  },
```

**Comment by custardcream98** [comment]
I'm still waiting for `esbuild-register` to be updated, but it seems like that won't happen anytime soon, as there haven't been any releases for `esbuild-register` since last year.

I believe it would be a good idea to explore alternative options if available. It's frustrating that Storybook still doesn't support TypeScript 5.0!!

**Comment by shilman** [comment]
@custardcream98  what isn't working for you? Do you have a reproduction you can share? This issue is about updating the storybook monorepo to TS5. I'm pretty sure it should work fine in user projects

**Comment by custardcream98** [comment]
@shilman 
Yes, it works fine but I can't use array extends in tsconfig as described [above](https://github.com/storybookjs/storybook/issues/21792#issuecomment-1533356647).

**Comment by shilman** [comment]
@custardcream98 gotcha--thanks for clarifying

**Comment by ndelangen** [comment]
@kasperpeulen this is now no longer blocked by [esbuild-register](https://github.com/storybookjs/storybook/issues/24010)

**Comment by shilman** [comment]
@custardcream98 does this now work in 7.5.0-alpha.3 and above for you?

**Comment by steven-prybylynskyi** [comment]
I have an error when using the mentioned above `satisifies` keyword
```
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /SelectControl.stories.tsx: Unexpected token, expected "," (18:2)

  16 |     placeholder: 'Estimated Arrival Time'
  17 |   }
> 18 | } satisfies Meta<typeof SelectControlComponent>);
     |   ^
  19 | export default meta;
  20 | type Story = StoryObj<typeof meta>;
  21 | export const SelectControl: Story = {
    at constructor (/node_modules/@babel/parser/lib/index.js:356:19)
    at JSXParserMixin.raise (/node_modules/@babel/parser/lib/index.js:3223:19)
    at JSXParserMixin.unexpected (/node_modules/@babel/parser/lib/index.js:3253:16)
    at JSXParserMixin.expect (/node_modules/@babel/parser/lib/index.js:3590:28)
    at JSXParserMixin.parseParenAndDistinguishExpression (/node_modules/@babel/parser/lib/index.js:11490:14)
    at JSXParserMixin.parseExprAtom (/node_modules/@babel/parser/lib/index.js:11142:23)
    at JSXParserMixin.parseExprAtom (/node_modules/@babel/parser/lib/index.js:6937:20)
    at JSXParserMixin.parseExprSubscripts (/node_modules/@babel/parser/lib/index.js:10862:23)
    at JSXParserMixin.parseUpdate (/node_modules/@babel/parser/lib/index.js:10845:21)
    at JSXParserMixin.parseMaybeUnary (/node_modules/@babel/parser/lib/index.js:10821:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (/node_modules/@babel/parser/lib/index.js:10659:61)
    at JSXParserMixin.parseExprOps (/node_modules/@babel/parser/lib/index.js:10664:23)
    at JSXParserMixin.parseMaybeConditional (/node_modules/@babel/parser/lib/index.js:10641:23)
    at JSXParserMixin.parseMaybeAssign (/node_modules/@babel/parser/lib/index.js:10602:21)
    at /node_modules/@babel/parser/lib/index.js:10572:39
    at JSXParserMixin.allowInAnd (/node_modules/@babel/parser/lib/index.js:12284:16)
    at JSXParserMixin.parseMaybeAssignAllowIn (/node_modules/@babel/parser/lib/index.js:10572:17)
    at JSXParserMixin.parseVar (/node_modules/@babel/parser/lib/index.js:13264:91)
    at JSXParserMixin.parseVarStatement (/node_modules/@babel/parser/lib/index.js:13105:10)
    at JSXParserMixin.parseStatementContent (/node_modules/@babel/parser/lib/index.js:12688:23)
    at JSXParserMixin.parseStatementLike (/node_modules/@babel/parser/lib/index.js:12593:17)
    at JSXParserMixin.parseModuleItem (/node_modules/@babel/parser/lib/index.js:12570:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/node_modules/@babel/parser/lib/index.js:13194:36)
    at JSXParserMixin.parseBlockBody (/node_modules/@babel/parser/lib/index.js:13187:10)
    at JSXParserMixin.parseProgram (/node_modules/@babel/parser/lib/index.js:12469:10)
    at JSXParserMixin.parseTopLevel (/node_modules/@babel/parser/lib/index.js:12459:25)
    at JSXParserMixin.parse (/node_modules/@babel/parser/lib/index.js:14381:10)
    at parse (/node_modules/@babel/parser/lib/index.js:14422:38)
    at parser (/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/node_modules/@babel/core/lib/transformation/normalize-file.js:64:37)
    at normalizeFile.next (<anonymous>)
    at run (/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/node_modules/gensync/index.js:261:32)
    at /node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/node_modules/gensync/index.js:223:11)
    at processResult (/node_modules/webpack/lib/NormalModule.js:764:19)
    at /node_modules/webpack/lib/NormalModule.js:866:5
    at /node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /node_modules/babel-loader/lib/index.js:39:103
```

**Comment by steven-prybylynskyi** [comment]
`.storybook/main.ts`
```ts
import { StorybookConfig } from '@storybook/react-webpack5';

const storybookConfig: StorybookConfig = {
  stories: ['../src'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions'
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
  docs: {
    autodocs: true,
  },
  features: {
    buildStoriesJson: true,
  },
}

export default storybookConfig;
```

**Comment by steven-prybylynskyi** [comment]
@shilman please let me know where should I look at?

**Comment by steven-prybylynskyi** [comment]
also that:
![image](https://github.com/storybookjs/storybook/assets/3078595/a68750c4-f63e-47be-8d5d-e7102e5bf8a0)
