### ISSUE TITLE
[Bug]: string-width dependency stops storybook from executing

### ISSUE THREAD

**Issue by PhilippMolitor** [storybookjs/storybook#22431]
EDIT: Workaround described here: https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092

### Describe the bug

I am using Storybook 7 with the automatically generated vite-react setup.

When installing Storybook 7, yarn yields these dependency errors:

```
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning Pattern ["string-width@^1.0.2 || 2 || 3 || 4"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width@^4.2.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.0"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width@^4.2.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width@^4.2.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width-cjs@npm:string-width@^4.2.0"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width@^4.2.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["wrap-ansi-cjs@npm:wrap-ansi@^7.0.0"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-wrap-ansi-cjs-7.0.0-67e145cff510a6a6984bdf1152911d69d2eb9e43-integrity/node_modules/wrap-ansi-cjs" as pattern ["wrap-ansi@^7.0.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.2"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width@^4.2.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.0.0"] is trying to unpack in the same destination "/Users/phil/Library/Caches/Yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width@^4.2.3"]. This could result in non-deterministic behavior, skipping.
[4/5] 🔗  Linking dependencies...
warning "@storybook/addon-styling > css-loader@6.7.3" has unmet peer dependency "webpack@^5.0.0".
warning "@storybook/addon-styling > less-loader@11.1.0" has unmet peer dependency "less@^3.5.0 || ^4.0.0".
warning "@storybook/addon-styling > less-loader@11.1.0" has unmet peer dependency "webpack@^5.0.0".
warning "@storybook/addon-styling > postcss-loader@7.3.0" has unmet peer dependency "webpack@^5.0.0".
warning "@storybook/addon-styling > sass-loader@13.2.2" has unmet peer dependency "webpack@^5.0.0".
warning "@storybook/addon-styling > style-loader@3.3.2" has unmet peer dependency "webpack@^5.0.0".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ husky install
husky - Git hooks installed
✨  Done in 5.01s.
```

When running storybook, this error occurs:
```
/Users/phil/Projects/nextmission/node_modules/wide-align/align.js:2
var stringWidth = require('string-width')
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/phil/Projects/nextmission/node_modules/string-width/index.js from /Users/phil/Projects/nextmission/node_modules/wide-align/align.js not supported.
Instead change the require of index.js in /Users/phil/Projects/FPV/nextmission/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/wide-align/align.js:2:19)
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/gauge/render-template.js:2:13)
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/gauge/plumbing.js:3:22)
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/gauge/index.js:2:16)
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/npmlog/log.js:3:13)
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/@storybook/node-logger/dist/index.js:1:1141)
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/@storybook/cli/dist/generate.js:1:1014)
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/@storybook/cli/bin/index.js:9:1)
    at Object.<anonymous> (/Users/phil/Projects/nextmission/node_modules/storybook/index.js:3:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.4.0
```

Just out of curiosity, I tried changing all `require()` calls of the listed node_modules files to `import()`, and after that i got the same error that is happening in #22430 : 

```
❯ yarn dev:storybook
yarn run v1.22.19
$ storybook dev -p 6006
@storybook/cli v7.0.0

(node:55273) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
info => Starting manager..
✘ [ERROR] No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"

    node_modules/@storybook/preview-api/dist/chunk-6KOCOQSE.mjs:6:356:
      6 │ ... CURRENT_STORY_WAS_SET, PREVIEW_KEYDOWN, STORY_UNCHANGED, STORY_CHANGED, STORY_PREPARED, DOCS_PREPARED, STORY_MISSING, STORY_THREW_EXCEPTION, STORY_RENDER_PHASE_CHANGED, STORY_ERRORED, PLAY_...
        ╵                                                                                             ~~~~~~~~~~~~~

✘ [ERROR] No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"

    node_modules/@storybook/preview-api/dist/chunk-6KOCOQSE.mjs:6:356:
      6 │ ... CURRENT_STORY_WAS_SET, PREVIEW_KEYDOWN, STORY_UNCHANGED, STORY_CHANGED, STORY_PREPARED, DOCS_PREPARED, STORY_MISSING, STORY_THREW_EXCEPTION, STORY_RENDER_PHASE_CHANGED, STORY_ERRORED, PLAY_...
        ╵                                                                                             ~~~~~~~~~~~~~

ERR! Error: Build failed with 2 errors:
ERR! node_modules/@storybook/preview-api/dist/chunk-6KOCOQSE.mjs:6:356: ERROR: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
ERR! node_modules/@storybook/preview-api/dist/chunk-6KOCOQSE.mjs:6:356: ERROR: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
ERR!     at failureErrorWithLog (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1636:15)
ERR!     at /Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1048:25
ERR!     at runOnEndCallbacks (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1471:45)
ERR!     at buildResponseToResult (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1046:7)
ERR!     at /Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1075:16
ERR!     at responseCallbacks.<computed> (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:697:9)
ERR!     at handleIncomingPacket (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:752:9)
ERR!     at Socket.readFromStdout (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:673:7)
ERR!     at Socket.emit (node:events:537:28)
ERR!     at addChunk (node:internal/streams/readable:324:12)
ERR!  Error: Build failed with 2 errors:
ERR! node_modules/@storybook/preview-api/dist/chunk-6KOCOQSE.mjs:6:356: ERROR: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
ERR! node_modules/@storybook/preview-api/dist/chunk-6KOCOQSE.mjs:6:356: ERROR: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
ERR!     at failureErrorWithLog (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1636:15)
ERR!     at /Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1048:25
ERR!     at runOnEndCallbacks (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1471:45)
ERR!     at buildResponseToResult (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1046:7)
ERR!     at /Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:1075:16
ERR!     at responseCallbacks.<computed> (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:697:9)
ERR!     at handleIncomingPacket (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:752:9)
ERR!     at Socket.readFromStdout (/Users/phil/Projects/nextmission/node_modules/esbuild/lib/main.js:673:7)
ERR!     at Socket.emit (node:events:537:28)
ERR!     at addChunk (node:internal/streams/readable:324:12) {
ERR!   errors: [
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: [Object],
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"'
ERR!     },
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: [Object],
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"'
ERR!     }
ERR!   ],
ERR!   warnings: []
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System

```shell
Won't work because also npx fails with the same errors.
```

### Additional context

I started off with storybook 7.0.8, and after uprading to 7.0.9 this happened. Now all versions have this behavior. I tried Node 16, 18 and 20, as well as clearing my yarn cache and deleting node_modules.

**Comment by NormySan** [comment]
I'm also getting this error with Yarn, changing to pnpm solved it.

**Comment by PhilippMolitor** [comment]
@NormySan I switched from yarn 1 to yarn 3, this also resolved it. very weird indeed.

**Comment by estevaolucas** [comment]
I've faced this issue today! Struggle to find the root cause. 
Basically some transient dependency was updating `string-width` to `v5`. I had to add a yarn resolution to `cli-truncate@2.1.0` in order to pin `string-width` to `v4`,

**Comment by vilic** [comment]
I have encountered similar problem multiple times. And I guess it's likely a bug of yarn.

After deleting entries related to `string-width` in `yarn.lock` and `yarn` again, the problem gets fixed:

<img width="1031" alt="image" src="https://github.com/storybookjs/storybook/assets/970430/ec1ff61b-0233-44f0-9081-92775c8e14c8">

And `name string-width-cjs` is no longer there as well.

**Comment by samends** [comment]
Also experiencing this error, storybook version `7.0.9`, node version `v16.14.0`, yarn version `1.22.19`

**Comment by Sitting-Duck351** [comment]
Everything was working until string-width v5.0.1 was added to yarn.lock, after then I get:
`Error [ERR_REQUIRE_ESM]: require() of ES Module <path>/node_modules/string-width/index.js`
If I add `name string-width` to v4.2.3 then it works. As workaround I use NPM, which adds the name and then `yarn import` to generate yarn.lock, since my pipeline is all based in yarn.

**Comment by tmeasday** [comment]
This is an instance of this issue: https://github.com/isaacs/jackspeak/issues/5 -- we had thought we resolved this with https://github.com/storybookjs/storybook/pull/23080 but I think it was the wrong approach.

It's unclear what circumstances cause the bug to be triggered, it seems to just be which package yarn in its confusion hoists to the root `node_modules`.

Context: 
 - It comes from the changes in this PR: https://github.com/yargs/cliui/pull/139 which are being debated in `cliui`
 - In the meantime `jackspeak@2.1.2` has been updated to use the fork that breaks yarn1.
 - We only have that package as a transitive dep of `glob` which only depends on `jackspeak@^2.0.3`: https://github.com/isaacs/node-glob/blob/8c371a3eaacaa0783c34bda13d32fca3219017d3/package.json#L63C16-L63C16
 
So a simple workaround is to fix the resolution of `jackspeak` to `2.1.1`:

```json
  "resolutions": {
    "jackspeak": "2.1.1"
  }
```

You may need to delete `yarn.lock` also as `yarn` gets pretty confused.

**Comment by gurkiratkn** [comment]
@estevaolucas 
cli-truncate@2.1.0 fixed the issue, but now there is a new similar issue. can you help me out-

`Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\gurkirat.singh\Desktop\engine-dashboard\node_modules\wrap-ansi\index.js from C:\Users\gurkirat.singh\Desktop\engine-dashboard\node_modules\cliui\build\index.cjs not supported.
Instead change the require of index.js in C:\Users\gurkirat.singh\Desktop\engine-dashboard\node_modules\cliui\build\index.cjs to a dynamic import() which is available in all CommonJS modules.`

**Comment by tmeasday** [comment]
@gurkiratkn -- did you try the resolution I suggested?

**Comment by jcwalker3** [comment]
For those Mac users still using 1.22.19 you can upgrade yarn to the latest stable with:

yarn set version stable


> 
> **I'll note another workaround is to simply not use yarn 1 🤷**
>

**Comment by marcoarruda** [comment]
I tried on MacOS the `resolutions` approach (still with yarn 1.22.19) and it just decreased the warnings, from [image1] to [image2]

<img width="633" alt="Screenshot 2023-07-22 at 12 33 17" src="https://github.com/storybookjs/storybook/assets/216738/70d6e9ca-2b42-45ca-8dfe-abc34e699456">

<img width="390" alt="image1" src="https://github.com/storybookjs/storybook/assets/216738/cf6eff9d-cb41-48e6-aca9-40d7da3e0459" />
<img width="390" alt="image2" src="https://github.com/storybookjs/storybook/assets/216738/e5615649-13e5-46e0-a23b-f9a6102481be" />

---

Though upgrading yarn (`yarn set version stable`), mentioned by @tmeasday and emphasized by @jcwalker3 (thanks, I didn't see the first mention 😅 ), made it work 🎉 

<img width="390" alt="Screenshot 2023-07-22 at 12 33 09" src="https://github.com/storybookjs/storybook/assets/216738/199f9c86-70a6-4018-a590-91f0dc19605a">

**Comment by MikeMcC399** [comment]
- Possibly this relates to Yarn Classic issue https://github.com/yarnpkg/yarn/issues/4812, fixed in Yarn Modern.

**Comment by mikejoyceio** [comment]
> **So a simple workaround is to fix the resolution of `jackspeak` to `2.1.1`:**
> 
> ```json
>   "resolutions": {
>     "jackspeak": "2.1.1"
>   }
> ```

 @tmeasday this worked for me. Thanks!

**Comment by floatrx** [comment]
try
1. clean cache
2. upgrade npm & yarn
3. remove lock* files (yarn | npm)
4. re-install packages

```npm cache clean --force
yarn cache clean --all

npm install -g npm@latest
npm install -g yarn@latest

rm node_modules/ yarn.lock package-lock.json

yarn
```

**Comment by dzienisz** [comment]
The issue occurs every time so I don't think that any temporary solution is right.

I have Mac with Yarn 1.XX.XX when I install Storybook through NPX comand it run and the end. Problem occur when I want to yarn storybook my myself.

**Comment by dzienisz** [comment]
ok, so maybe some kind of information in the installation docs or better error handling? It took me now an hour to try to debug and run it

**Comment by MikeMcC399** [comment]
@dzienisz 

> ok, so maybe some kind of information in the installation docs or better error handling? It took me now an hour to try to debug and run it

I sympathize as I also spent quite a few hours on this issue!

**Comment by eby-paul-daniel-codeglo** [comment]
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\node_modules\string-width\index.js from C:\node_modules\cli-table3\src\utils.js not supported.
Instead change the require of index.js in C:\node_modules\cli-table3\src\utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\node_modules\cli-table3\src\utils.js:1:21)
    at Object.<anonymous> (C:\node_modules\cli-table3\src\table.js:2:15)
    at Object.<anonymous> (C:\node_modules\cli-table3\index.js:1:18)
    at Object.<anonymous> (C:\node_modules\@storybook\core-server\dist\index.js:113:8471)
    at Object.<anonymous> (C:\node_modules\@storybook\cli\dist\generate.js:11:4494)
    at Object.<anonymous> (C:i\node_modules\@storybook\cli\bin\index.js:9:1)
    at Object.<anonymous> (C:\node_modules\storybook\index.js:3:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.0
error Command failed with exit code 1.

Solution that worked for me : 

When I deleted the yarn.lock and ran yarn again, this was resolved

**Comment by imPBH** [comment]
> Solution that worked for me :
> 
> When I deleted the yarn.lock and ran yarn again, this was resolved

This doesn't really solve the issue, if you do this and then push your code, the problem will still occur for other people using your code.
If you stick with `yarn 1`,  this workaround works really well :

> **So a simple workaround is to fix the resolution of `jackspeak` to `2.1.1`:**
> 
> ```json
>   "resolutions": {
>     "jackspeak": "2.1.1"
>   }
> ```

**Comment by elf-ioki** [comment]
Deleting the `yarn.lock` and all `node_modules` and installing them again fixed this issue for me 👍🏻

**Comment by ahmed-khlifi** [comment]
upgrade Yarn , run **npm install --global yarn**  , delete node modules and yarn.lock and then run `yarn `again

**Comment by tmeasday** [comment]
Thanks for the feedback folks. I updated [my comment above](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092) to further emphasise that upgrading to yarn 3 is the preferred solution.

Ideally SB itself would catch the above error and link folks to this issue; however as it happens at require time, I don't think that's easy to do at our end--if any one figures out how, a PR to do that would be much appreciated!

**Comment by ks-krimi** [comment]
After deleting yarn.lock and running yarn, solve the error for me.

**Comment by akshayjai1** [comment]
> After deleting yarn.lock and running yarn, solve the error for me.

worked!

**Comment by bacvietswiss** [comment]
> After deleting yarn.lock and running yarn, solve the error for me.

This works for me, but it's really annoying since I need to delete yarn.lock all the time before running storybook

**Comment by MikeMcC399** [comment]
@bacvietswiss 

> > After deleting yarn.lock and running yarn, solve the error for me.
> 
> This works for me, but it's really annoying since I need to delete yarn.lock all the time before running storybook

The better workaround is in https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092

Add the following to `package.json` 

```json
  "resolutions": {
    "jackspeak": "2.1.1"
  }
```

The problem is resolved by updating from Yarn Classic (v1) to Yarn Modern (v3).

**Comment by zeroskullx** [comment]
I was encountering this error and went through the following steps:

- Storybook 7.4.0
- Next 12
- Yarn 1.22.19
- Node 18.17.1

1. Install the Storybook CLI globally if you haven't already, using yarn:
   ```
   yarn global add @storybook/cli
   ```
   or using npm:
   ```
   npm install -g @storybook/cli
   ```

2. Run the command to initialize Storybook in your project. This will create or recreate an initial configuration and set up the Storybook structure in your project:
   ```
   getstorybook init
   ```

3. Add these scripts to your package.json file to start Storybook. Open your project's package.json file and add the appropriate scripts. For example:
   ```
   "scripts": {
     "storybook": "start-storybook -p 6006",
     "build-storybook": "build-storybook"
   }
   ```

...and also, for yarn 'resolutions' and npm 'overrides':
```json
  "resolutions": {
    "string-width": "^4",
    "jackspeak": "^2",
    "strip-ansi": "^6"
  }
```

**Comment by qridwan** [comment]
> I was encountering this error and went through the following steps:
> 
>     * Storybook 7.4.0
> 
>     * Next 12
> 
>     * Yarn 1.22.19
> 
>     * Node 18.17.1
> 
> 
>     1. Install the Storybook CLI globally if you haven't already, using yarn:
>        ```
>        yarn global add @storybook/cli
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        or using npm:
>        ```
>        npm install -g @storybook/cli
>        ```
> 
>     2. Run the command to initialize Storybook in your project. This will create or recreate an initial configuration and set up the Storybook structure in your project:
>        ```
>        getstorybook init
>        ```
> 
>     3. Add these scripts to your package.json file to start Storybook. Open your project's package.json file and add the appropriate scripts. For example:
>        ```
>        "scripts": {
>          "storybook": "start-storybook -p 6006",
>          "build-storybook": "build-storybook"
>        }
>        ```
> 
> 
> ...and also, for yarn 'resolutions' or for npm 'overrides':
> 
> ```json
>   "resolutions": {
>     "string-width": "^4",
>     "jackspeak": "^2",
>     "strip-ansi": "^6"
>   }
> ```

This works! thanks 🙏🏼

**Comment by michelarteta** [comment]
hey guys, having the same issue where running into an error when trying to install storybook. Error code 'ERR_REQUIRE_SEM'. node v 18.18. Yarn version 1.22.19. Anyone facing this problem?

**Comment by Alex-Programmer-Bro** [comment]
> @bacvietswiss
> 
> > > After deleting yarn.lock and running yarn, solve the error for me.
> > 
> > 
> > This works for me, but it's really annoying since I need to delete yarn.lock all the time before running storybook
> 
> The better workaround for Yarn Classic (v1) is in [#22431 (comment)](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092)
> 
> Add the following to `package.json`
> 
> ```json
>   "resolutions": {
>     "jackspeak": "2.1.1"
>   }
> ```
> 
> The problem is resolved by updating from Yarn Classic (v1) to Yarn Modern (v3).

It works for me and when I use `bun`

**Comment by sheldon-welinga** [comment]
I was encountering the same issue and below was the fix. Works without setting any resolutions
1. Set the stable yarn version
```
yarn set version stable
```
2. Reinstall the packages
```
yarn install
```

**Comment by tmeasday** [comment]
@sheldon-welinga - yes, this is the recommended fix! Perhaps that needs to be made more clear?

**Comment by MuhammadBabarWaseem** [comment]
I AM GETTING THIS STUFF:
yarn storybook 
 
 Error: It looks like you are having a known issue with package hoisting.
Please check the following issue for details and solutions: https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092


D:\CODE\ui-lib\node_modules\@storybook\cli\bin\index.js:23
  throw error;
  ^

Error: Cannot find module 'string-width'
Require stack:
- D:\CODE\ui-lib\node_modules\cli-table3\src\utils.js
- D:\CODE\ui-lib\node_modules\cli-table3\src\table.js
- D:\CODE\ui-lib\node_modules\cli-table3\index.js
- D:\CODE\ui-lib\node_modules\@storybook\core-server\dist\index.js
- D:\CODE\ui-lib\node_modules\@storybook\cli\dist\generate.js
- D:\CODE\ui-lib\node_modules\@storybook\cli\bin\index.js
- D:\CODE\ui-lib\node_modules\storybook\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\CODE\ui-lib\node_modules\cli-table3\src\utils.js:1:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\CODE\\ui-lib\\node_modules\\cli-table3\\src\\utils.js',
    'D:\\CODE\\ui-lib\\node_modules\\cli-table3\\src\\table.js',
    'D:\\CODE\\ui-lib\\node_modules\\cli-table3\\index.js',
    'D:\\CODE\\ui-lib\\node_modules\\@storybook\\core-server\\dist\\index.js',
    'D:\\CODE\\ui-lib\\node_modules\\@storybook\\cli\\dist\\generate.js',
    'D:\\CODE\\ui-lib\\node_modules\\@storybook\\cli\\bin\\index.js',
    'D:\\CODE\\ui-lib\\node_modules\\storybook\\index.js'
  ]
}

Node.js v18.16.1
error Command failed with exit code 7.

**Comment by Katalyst33** [comment]
> I was encountering the same issue and below was the fix. Works without setting any resolutions
> 
> 1. Set the stable yarn version
> 
> ```
> yarn set version stable
> ```
> 
> 2. Reinstall the packages
> 
> ```
> yarn install
> ```

worked for me too. just when i was about to give up

**Comment by abdul-megadraws** [comment]
```
Run:
yarn set version stable && yarn install 

After:
Restart VScode(Editor)
```

**Comment by eylonshm** [comment]
1. Add this code inside package.json:

```
"resolutions": {
    "jackspeak": "2.1.1"
 }
```
2. Remove node_modules folder and yarn.lock package.lock files.
3. Run npm/yarn install.
Worked for me :)

**Comment by russo97** [comment]
> **TLDR:** the simplest solution here is to **upgrade to Yarn 3**. Yarn 1 is deprecated and I guess bugs like the below aren't going to get fixed.
> 
> _There is a workaround for Yarn 1 however, read on:_
> 
> This is an instance of this issue: [isaacs/jackspeak#5](https://github.com/isaacs/jackspeak/issues/5), I guess technically a bug in yarn 1 -- we had thought we resolved this with #23080 but I think it was the wrong approach.
> 
> It's unclear what circumstances cause the bug to be triggered, it seems to just be which package yarn in its confusion hoists to the root `node_modules`.
> 
> Context:
> 
> * It comes from the changes in this PR: [fix: handle strings the same in cjs, esm, and deno yargs/cliui#139](https://github.com/yargs/cliui/pull/139) which are being debated in `cliui`
> * In the meantime `jackspeak@2.1.2` has been updated to use the fork that breaks yarn1.
> * We only have that package as a transitive dep of `glob` which only depends on `jackspeak@^2.0.3`: https://github.com/isaacs/node-glob/blob/8c371a3eaacaa0783c34bda13d32fca3219017d3/package.json#L63C16-L63C16
> 
> **So a simple workaround is to fix the resolution of `jackspeak` to `2.1.1`:**
> 
> ```json
>   "resolutions": {
>     "jackspeak": "2.1.1"
>   }
> ```
> 
> You may need to delete `yarn.lock` also as `yarn` gets pretty confused.
> 
> Note we don't really have any better solution because (a) Storybook can't set the resolution field for you, and (b) `glob` (and therefore `jackspeak`) is a transitive dependency of quite a few of our dependencies, so we can't even prebundle or depend on a specific "good" version.

the second solution proposed by @tmeasday worked for me

**Comment by jordan-bite** [comment]
> **TLDR:** the simplest solution here is to **upgrade to Yarn 3**. Yarn 1 is deprecated and I guess bugs like the below aren't going to get fixed.

Where is it documented that Yarn 1 is deprecated? And no, upgrading to Yarn 3 is most definitely not the "simplest" solution.

**Comment by tmeasday** [comment]
> Where is it documented that Yarn 1 is deprecated? 
https://github.com/yarnpkg/yarn/issues/8583#issuecomment-783161589

> And no, upgrading to Yarn 3 is most definitely not the "simplest" solution.
🤷 depending on what you mean by simple I guess. I understand migrating from yarn 1 isn't necessarily easy, we ourselves have some codebases still on it too.

**Comment by eduinlight** [comment]
I 

> > **TLDR:** the simplest solution here is to **upgrade to Yarn 3**. Yarn 1 is deprecated and I guess bugs like the below aren't going to get fixed.
> > _There is a workaround for Yarn 1 however, read on:_
> > This is an instance of this issue: [isaacs/jackspeak#5](https://github.com/isaacs/jackspeak/issues/5), I guess technically a bug in yarn 1 -- we had thought we resolved this with #23080 but I think it was the wrong approach.
> > It's unclear what circumstances cause the bug to be triggered, it seems to just be which package yarn in its confusion hoists to the root `node_modules`.
> > Context:
> > 
> > * It comes from the changes in this PR: [fix: handle strings the same in cjs, esm, and deno yargs/cliui#139](https://github.com/yargs/cliui/pull/139) which are being debated in `cliui`
> > * In the meantime `jackspeak@2.1.2` has been updated to use the fork that breaks yarn1.
> > * We only have that package as a transitive dep of `glob` which only depends on `jackspeak@^2.0.3`: https://github.com/isaacs/node-glob/blob/8c371a3eaacaa0783c34bda13d32fca3219017d3/package.json#L63C16-L63C16
> > 
> > **So a simple workaround is to fix the resolution of `jackspeak` to `2.1.1`:**
> > ```json
> >   "resolutions": {
> >     "jackspeak": "2.1.1"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You may need to delete `yarn.lock` also as `yarn` gets pretty confused.
> > Note we don't really have any better solution because (a) Storybook can't set the resolution field for you, and (b) `glob` (and therefore `jackspeak`) is a transitive dependency of quite a few of our dependencies, so we can't even prebundle or depend on a specific "good" version.
> 
> the second solution proposed by @tmeasday worked for me

This works for me

**Comment by daniellalasa2** [comment]
> > **TLDR:** the simplest solution here is to **upgrade to Yarn 3**. Yarn 1 is deprecated and I guess bugs like the below aren't going to get fixed.
> > _There is a workaround for Yarn 1 however, read on:_
> > This is an instance of this issue: [isaacs/jackspeak#5](https://github.com/isaacs/jackspeak/issues/5), I guess technically a bug in yarn 1 -- we had thought we resolved this with #23080 but I think it was the wrong approach.
> > It's unclear what circumstances cause the bug to be triggered, it seems to just be which package yarn in its confusion hoists to the root `node_modules`.
> > Context:
> > 
> > * It comes from the changes in this PR: [fix: handle strings the same in cjs, esm, and deno yargs/cliui#139](https://github.com/yargs/cliui/pull/139) which are being debated in `cliui`
> > * In the meantime `jackspeak@2.1.2` has been updated to use the fork that breaks yarn1.
> > * We only have that package as a transitive dep of `glob` which only depends on `jackspeak@^2.0.3`: https://github.com/isaacs/node-glob/blob/8c371a3eaacaa0783c34bda13d32fca3219017d3/package.json#L63C16-L63C16
> > 
> > **So a simple workaround is to fix the resolution of `jackspeak` to `2.1.1`:**
> > ```json
> >   "resolutions": {
> >     "jackspeak": "2.1.1"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You may need to delete `yarn.lock` also as `yarn` gets pretty confused.
> > Note we don't really have any better solution because (a) Storybook can't set the resolution field for you, and (b) `glob` (and therefore `jackspeak`) is a transitive dependency of quite a few of our dependencies, so we can't even prebundle or depend on a specific "good" version.
> 
> the second solution proposed by @tmeasday worked for me

This worked for me as well.
Yarn 1
Nextjs 14.1.1
Storybook 7.4.5
Cypress 13.6.4

But I realized that it's time to upgrade the Yarn, eventually...

**Comment by shadowspawn** [comment]
For yarn 1 users, this issue should be fixed by upgrading to yarn v1.22.22 or higher.

- https://github.com/yarnpkg/yarn/releases/tag/v1.22.22

**Comment by tmeasday** [comment]
Sounds like we can close this ticket then.

I'll note that as of SB8 (just released!) [we no longer officially support yarn 1](https://storybook.js.org/docs/migration-guide#major-breaking-changes), and I encourage folks to consider upgrading.

**Comment by sibelius** [comment]
how to solve this ?

**Comment by tmeasday** [comment]
@sibelius I think https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092 still applies. Perhaps there is some sign that yarn 1 might eventually fix the problem, but there is a workaround in the comment and migrating to yarn 4 is still my recommendation if possible.

**Comment by yyyyaaa** [comment]
in my case this still exists within a npm + lerna monorepo, not sure what triggers it tho

**Comment by thomasbnt** [comment]
> **TLDR:** the simplest solution here is to **upgrade to Yarn 4**. Yarn 1 is deprecated and I guess bugs like the below aren't going to get fixed.
> 
> _There is a workaround for Yarn 1 however, read on:_
> 
> This is an instance of this issue: [isaacs/jackspeak#5](https://github.com/isaacs/jackspeak/issues/5), I guess technically a bug in yarn 1 -- we had thought we resolved this with #23080 but I think it was the wrong approach.
> 
> It's unclear what circumstances cause the bug to be triggered, it seems to just be which package yarn in its confusion hoists to the root `node_modules`.
> 
> Context:
> 
>     * It comes from the changes in this PR: [fix: handle strings the same in cjs, esm, and deno yargs/cliui#139](https://github.com/yargs/cliui/pull/139) which are being debated in `cliui`
> 
>     * In the meantime `jackspeak@2.1.2` has been updated to use the fork that breaks yarn1.
> 
>     * We only have that package as a transitive dep of `glob` which only depends on `jackspeak@^2.0.3`: https://github.com/isaacs/node-glob/blob/8c371a3eaacaa0783c34bda13d32fca3219017d3/package.json#L63C16-L63C16
> 
> 
> **So a simple workaround is to fix the resolution of `jackspeak` to `2.1.1`:**
> 
> ```json
>   "resolutions": {
>     "jackspeak": "2.1.1"
>   }
> ```
> 
> You may need to delete `yarn.lock` also as `yarn` gets pretty confused.
> 
> Note we don't really have any better solution because (a) Storybook can't set the resolution field for you, and (b) `glob` (and therefore `jackspeak`) is a transitive dependency of quite a few of our dependencies, so we can't even prebundle or depend on a specific "good" version.

Hello and thanks for this resolving message, works for me!

**Comment by SutuSebastian** [comment]
Anyone experiencing this with `bun` in a monorepo?

**Comment by andrijaantunovic** [comment]
> Anyone experiencing this with `bun` in a monorepo?

Just had a weird error with bun that pointed me to this issue. Deleting the node_modules folder and running `bun update` fixed it for me. 🤷

**Comment by SutuSebastian** [comment]
> > Anyone experiencing this with `bun` in a monorepo?
> 
> Just had a weird error with bun that pointed me to this issue. Deleting the node_modules folder and running `bun update` fixed it for me. 🤷

Didn't work for me, reason is `bun` hoists all `node_modules` at the root level, instead of them being present at the package level, this results in breaking the storybook but funny enough that `bun@1.0.31` works, but as soon as u go `bun@1.0.32` or `bun@1.0.33` (both tested) it breaks any storybook commands.

My solution? stick lock `bun` to `bun@1.0.31`

**Comment by jacklaurencegaray** [comment]
> For yarn 1 users, this issue should be fixed by upgrading to yarn v1.22.22 or higher.
> 
> * https://github.com/yarnpkg/yarn/releases/tag/v1.22.22

I'm using yarn 1.23.0 and still encounter this error.

**Comment by shadowspawn** [comment]
To be clear @jacklaurencegaray , you need to regenerate the `yarn.lock` file to clear the error from older version of yarn. (You may have done the, but just making sure.)

**Comment by tmeasday** [comment]
@shadowspawn have you seen it work? [I tried with a brand new project on yarn 1.22.22 and continued to see the original problem](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1992742618). As I said, I don't think the yarn 1 issue is actually fixed, although the change you pointed to does seem like a step in the right direction.

I'll point out [as I mentioned way back](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092):

> It's unclear what circumstances cause the bug to be triggered, it seems to just be which package yarn in its confusion hoists to the root node_modules.

So it's not impossible the issue was "fixed" for you just by chance, as an aside.

**Comment by shadowspawn** [comment]
@tmeasday I saw the same hoisting problem fixed, but it was in a different project.

> So it's not impossible the issue was "fixed" for you just by chance, as an aside.

I did have a reproducible failure which went away when I used the new version of yarn, so I thought it was good.  I commented here because the issue was linked. But maybe I was just lucky or trigger conditions changed but not fully fixed, as you say.

Sorry I may have offered false hope. 😢

**Comment by tmeasday** [comment]
Hard to say for sure without analyzing `node_modules` (and remembering the exact form of the problem) but I'm going to guess given my and @jacklaurencegaray's experience that this is the case 😞

**Comment by marcotas** [comment]
Deleting the `node_modules` folder also worked for me with `pnpm`.

**Comment by pozda** [comment]
TL;DR: - install SB8 with npm and then switch back to yarn (works with yarn 1.22.22)

unusual solution helped in my case: 
- removed node_modules
- removed yarn.lock
- removed @storybook and all those addons (keep the list somewhere)
- run npx storybook@latest init
- install back the addons, install packages that are listed in console error
- try running it with yarn
- when successful, delete the package_lock.json, node_modules
- run yarn with empty yarn.lock file
- profit

**Comment by ljhyeok** [comment]
@pozda thanks a lot! It works for me

**Comment by qfdk** [comment]
Hello all,

I found a solution and would like to share how to resolve it:
0. Don;t need to delete yarn.lock
1. Run `yarn why string-width` to find the library that uses it as a dependency.
2. Downgrade this library to the version that works, remove `node_modules`, and then run `yarn install` to verify it works.
3. **_Use `yarn upgrade lib@version` to upgrade only this library._**

It should work.

Happy coding!

2024-06-03

**Comment by chessmadridista** [comment]
> You may need to delete `yarn.lock` also as `yarn` gets pretty confused.

This solution worked for me. Thanks!

**Comment by tiarebalbi** [comment]
This issue still happening, any plan to workaround the problem? I had to follow the step described by @tmeasday

**Comment by tmeasday** [comment]
@tiarebalbi AFAIK [my comment](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092) still applies.

**Comment by Netail** [comment]
If I remember correctly, Yarn v1.22.22 should have resolved this
