### ISSUE TITLE
[Bug]: Storybook preview hooks can only be called inside decorators and story functions.

### ISSUE THREAD

**Issue by stevegreco** [storybookjs/storybook#29189]
### Describe the bug

When attempting to use a custom `render` function to create a Story for a controlled component, I am getting the following error.

```
Storybook preview hooks can only be called inside decorators and story functions.
```

This previously worked fine, so I am curious what changed.

My Story code is as follows.  I am just trying to use a basic implementation of `useState`.  The Story renders correctly, but as soon as I press the `Button`, this error is displayed.

From what I can tell, this is being caused by `@storybook/addon-themes`.  You can see my setup in the reproduction.

```ts
// .storybook/preview.ts
import type { Preview, ReactRenderer } from '@storybook/react';
import { withThemeByDataAttribute } from '@storybook/addon-themes';

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
  decorators: [
    withThemeByDataAttribute<ReactRenderer>({
      themes: {
        light: 'light',
        dark: 'dark',
        auto: 'auto',
      },
      defaultTheme: 'light',
      attributeName: 'data-color-mode',
    }),
  ],
};

export default preview;

```

```tsx
type Story = StoryObj<typeof meta>;

export const Controlled: Story = {
  args: {
    size: 'small',
    label: 'Button',
  },
  render: function Render(args) {
    const [pressed, setPressed] = React.useState(false);

    return (
      <>
        <Button {...args} onClick={() => setPressed(!pressed)} />
        <h1>{pressed.toString()}</h1>
      </>
    );
  },
};

```

### Reproduction link

https://stackblitz.com/edit/github-rjewa6?file=.storybook%2Fpreview.ts

### Reproduction steps

1. Run the Storybook.
2. Navigate to the Button -> Controlled Story
3. Press the button

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.0
    CPU: (14) arm64 Apple M3 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/.tools/pnpm/9.6.0/bin/pnpm <----- active
  Browsers:
    Chrome: 129.0.6668.58
    Safari: 18.0
```

**Comment by lpillonel** [comment]
Also facing the exact same issue, which appeared in version 8.3.0.
For the moment, staying on 8.2.9 prevent the issue.

**Comment by morewings** [comment]
The same problem happens to me as well. 
Here is reproduction: [chromatic preview](https://656cdd7c29a818474826ecb1-zakghlejyk.chromatic.com/?path=/story/inputs-checkbox--primary), [code](https://github.com/morewings/koval-ui/tree/fix/storybook-update)

**Comment by i-mo-gupta** [comment]
Facing the same issue, it started happening with `8.3.0`. It works fine till `8.2.9`. I have the pretty much the same story example as given in description.

**Comment by carlwelchyubico** [comment]
Just notice this same issue today. Every story that has a useState is broken :(

**Comment by peterfargo2** [comment]
Downgraded from 8.3.5 to 8.2.9 and useState works for me now.

**Comment by morewings** [comment]
I love the `Empathy Backlog` name. Sending warm vibes to Storybook comrades.

**Comment by TheCodingGorilla** [comment]
A not so ideal work around is:

```
export function Story() {
    return ComponentDecorator(Component);
}
```

**Comment by morewings** [comment]
> A not so ideal work around is:
> 
> ```
> export function Story() {
>     return ComponentDecorator(Component);
> }
> ```

Sometimes Context in needed.

**Comment by kasperpeulen** [comment]
@yannbf 
This issue is really complicated and in fundamental way, this was broken for quite some time.

The issue seemed to have been aggravated by a RSC decorator change.

Here is a PR that should fix that issue:
https://github.com/storybookjs/storybook/pull/26243

There will still be a problem when a user write a chain of decerator like this itself:

```
    withThemeByDataAttribute<ReactRenderer>({
      themes: {
        light: 'light',
        dark: 'dark',
        auto: 'auto',
      },
      defaultTheme: 'light',
      attributeName: 'data-color-mode',
    }),
    // We have something like this decorator now by default in React since 8.3.0
    // But you get the same error with a custom decorator, that doesn't use storyFn.
    (Story) => {
      return <Story />;
    },
```

Or even a custom decorator that uses the storybook context in some way:

```
    (storyFn) => {
      useParameter("bla", {});
      return storyFn();
    },
    (Story) => {
      return <Story />;
    },
```

This is a very weird issue. We are not yet at the bottom of this problem.

We might be able to prevent it with a custom applyDecorator, in a similar way that Vue has:

https://github.com/storybookjs/storybook/blob/1fdd2d6c675b81269125af5027e45a357c09f1fa/code/renderers/vue3/src/decorateStory.ts#L47-L80

And add a (S) => </S> decorator in between each other decorator in the stack. After some experimenting it seems that React doesn't loose its react state in this way.

**Comment by lundmikkel** [comment]
What is status here, @kasperpeulen? Have you gotten a solution/fix yet? I have the same issue in Angular.

**Comment by damonaskavio** [comment]
Had the same issue on my end, fixed it by using the useState from preview-api instead of React's

```diff
- import { useState } from "react";
+ import { useState } from "storybook/internal/preview-api";
```

**Comment by kasperpeulen** [comment]
@yannbf Didn't you look at this issue?

**Comment by oleksandr-danylchenko** [comment]
Unfortunately, _I still experience the same exception even after downgrading to the `8.2.10` version_! 

Here's the story template I use: 
```tsx
const InteractiveStudentTemplate = (args) => {
	const { ... } = args;

	const [submitting, setSubmitting] = useState(false);
	const handleChoiceSelected = (choiceFamilyId: FamilyId) => {
		setSubmitting(true);
	};

	return <button onClick={() => setSubmitting(true)}>Click me!</button>;
};

export const PollQuestion = InteractiveStudentTemplate.bind({});
PollQuestion.args = {
	...
}
```
Whenever I click on the button - the screen flashes with the exception: 

https://github.com/user-attachments/assets/065934e8-ddf1-44c2-ba02-5491e5999ed5

---

However, the approach recommended by @damonaskavio helps, and after replacing the `useState` imports with `import { useState } from "storybook/internal/preview-api";` - story renders successfully ✅

**Comment by vojdan** [comment]
> UPD: The following recommendation helped me - https://stackoverflow.com/a/77859321/10963661. I moved the `withThemeFromJSXProvider` definition to the last place in the `decorators` array. And then replaced hooks imports back with the `import { useState } from 'react'`. After that - the stories finally started working again!

Simply adding "async" to my component broke it. This suggestion worked for me, but I had to add the <React.Suspense> wrapper.
```
	decorators: [
		/**
		 * This is a workaround to fix an issue with the "withThemeByClassName" and React Server Components
		 * see https://github.com/storybookjs/storybook/issues/29189#issuecomment-2573457548
		 *
		 * Error: Storybook preview hooks can only be called inside decorators and story functions.
		 * 	at invalidHooksError (http://localhost:6006/sb-preview/runtime.js:3668:7)
		 * 	at useStoryContext (http://localhost:6006/sb-preview/runtime.js:3783:11)
		 * 	at useParameter (http://localhost:6006/sb-preview/runtime.js:3788:27)
		 * 	at useThemeParameters (http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-412678.iframe.bundle.js:14928:684)
		 * */
		storyFn => {
			return <React.Suspense>{storyFn() as React.ReactNode}</React.Suspense>;
		},
		withThemeByClassName({
			themes: {
				// nameOfTheme: 'classNameForTheme',
				light: '',
				dark: 'dark',
			},
			defaultTheme: 'light',
		}),
	],
```

**Comment by elliason** [comment]
I was having the same issue in 8.4.7. Not using @storybook/addon-themes fixed it.

**Comment by vojdan** [comment]
> > UPD: The following recommendation helped me - https://stackoverflow.com/a/77859321/10963661. I moved the `withThemeFromJSXProvider` definition to the last place in the `decorators` array. And then replaced hooks imports back with the `import { useState } from 'react'`. After that - the stories finally started working again!
> 
> Simply adding "async" to my component broke it. This suggestion worked for me, but I had to add the <React.Suspense> wrapper.
> 
> ```
> 	decorators: [
> 		/**
> 		 * This is a workaround to fix an issue with the "withThemeByClassName" and React Server Components
> 		 * see https://github.com/storybookjs/storybook/issues/29189#issuecomment-2573457548
> 		 *
> 		 * Error: Storybook preview hooks can only be called inside decorators and story functions.
> 		 * 	at invalidHooksError (http://localhost:6006/sb-preview/runtime.js:3668:7)
> 		 * 	at useStoryContext (http://localhost:6006/sb-preview/runtime.js:3783:11)
> 		 * 	at useParameter (http://localhost:6006/sb-preview/runtime.js:3788:27)
> 		 * 	at useThemeParameters (http://localhost:6006/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-412678.iframe.bundle.js:14928:684)
> 		 * */
> 		storyFn => {
> 			return <React.Suspense>{storyFn() as React.ReactNode}</React.Suspense>;
> 		},
> 		withThemeByClassName({
> 			themes: {
> 				// nameOfTheme: 'classNameForTheme',
> 				light: '',
> 				dark: 'dark',
> 			},
> 			defaultTheme: 'light',
> 		}),
> 	],
> ```

Seems to be fixed in 8.5.0.

**Comment by lpillonel** [comment]
version 8.5.0 also solved the issue for me 👍

**Comment by TroutZen** [comment]
> version 8.5.0 also solved the issue for me 👍

I'm on 8.5.1 and seeing this error. It's intermittent which doesn't make a lot of sense to me :). If I constantly refresh the page eventually the error goes away and my component renders. But that's not a solution only an observation.

**Comment by moatorres** [comment]
I'm facing the exact same issue.

**Comment by kasperpeulen** [comment]
@vanessayuenn I think we should put this as high priority in the empathy workstream.

**Comment by popuguytheparrot** [comment]
> If I constantly refresh the page eventually the error goes away and my component renders

I have same behavior after build storybook-static, in dev mode not catch it

**Comment by giovannipds** [comment]
we're having the same issue

**Comment by CarlosAmaral** [comment]
This is still a problem.

**Comment by kasperpeulen** [comment]
Working on a fix to finally solve this properly in Storybook 9!

**Comment by adam-sajko** [comment]
Temporary fix:

hooks.ts
```ts
import { useArgs as useStoryArgs } from '@storybook/preview-api';
import type { Args, StoryObj } from '@storybook/react';

type StoryContext = Parameters<NonNullable<StoryObj<any>['render']>>[1];

declare global {
  // eslint-disable-next-line no-var
  var STORYBOOK_HOOKS_CONTEXT: {
    currentContext: StoryContext;
  };
}

/**
 * TODO: Storybook authors have stated that the issue with Storybook hooks will be fixed in v9:
 * https://github.com/storybookjs/storybook/issues/29189#issuecomment-2751516699
 *
 * Once the issue is fixed, we can remove this hook.
 *
 * ```ts
 * const [args, updateArgs, resetArgs] = useArgs(context);
 * ```
 */
export function useArgs<
  TArgs extends Args = Args,
  TContext extends StoryContext = StoryContext,
>(
  context?: TContext,
): [
  TArgs,
  (newArgs: Partial<TArgs>) => void,
  (argNames?: Array<keyof TArgs>) => void,
] {
  if (
    'currentContext' in global.STORYBOOK_HOOKS_CONTEXT &&
    !global.STORYBOOK_HOOKS_CONTEXT.currentContext &&
    context
  ) {
    // eslint-disable-next-line react-compiler/react-compiler
    global.STORYBOOK_HOOKS_CONTEXT.currentContext = context;
  }

  return useStoryArgs();
}
```

Usage:
```ts
import { useArgs } from './hooks'

export const Default: Story = {
  render(props, context) {
    const [, updateArgs] = useArgs(context);
  
    // your code
  }
}
```

BTW. for the web, I'm also using a custom decorator to auto-update the args when the story is rendered
```ts
import { makeDecorator, useArgs, useEffect } from '@storybook/preview-api';

const ADDON_ID = 'storybook-auto-update-args';
const PARAM_KEY = 'autoUpdateArgs';

// WEB: This decorator is used to fix the issue where the args are not updated to default values when the story is rendered.
const withArgs = makeDecorator({
  name: ADDON_ID,
  parameterName: PARAM_KEY,
  wrapper: (storyFn, context, {}) => {
    const [args, updateArgs] = useArgs();

    useEffect(() => updateArgs({}), [context.id, updateArgs]);

    return storyFn({
      ...context,
      args,
    });
  },
});

export default withArgs;
```

preview.ts:
```ts
import type { Preview } from '@storybook/react';

const preview: Preview = {
  decorators: [withArgs],
}
```

---

My version of Storybook: 8.4.4

---

CC @kasperpeulen @stevegreco

**Comment by adam-sajko** [comment]
@stevegreco For React hooks, you can use a similar approach—@storybook/preview-api provides similar hooks like useState, useCallback, etc. But a better option would be to just create a wrapper for the story.

```tsx
const InternalControlled = () => {
  const [pressed, setPressed] = React.useState(false);

  return (
    <>
      <Button {...args} onClick={() => setPressed(!pressed)} />
      <h1>{pressed.toString()}</h1>
    </>
  );
};

export const Controlled: Story = {
  args: {
    size: 'small',
    label: 'Button',
  },
  render: function Render(args) {
    return <InternalControlled />;
  },
};

```

**Comment by emab** [comment]
> [@stevegreco](https://github.com/stevegreco) For React hooks, you can use a similar approach—@storybook/preview-api provides similar hooks like useState, useCallback, etc. But a better option would be to just create a wrapper for the story.
> 
> const InternalControlled = () => {
>   const [pressed, setPressed] = React.useState(false);
> 
>   return (
>     <>
>       <Button {...args} onClick={() => setPressed(!pressed)} />
>       <h1>{pressed.toString()}</h1>
>     </>
>   );
> };
> 
> export const Controlled: Story = {
>   args: {
>     size: 'small',
>     label: 'Button',
>   },
>   render: function Render(args) {
>     return <InternalControlled />;
>   },
> };

Using a wrapper means that the `Show code` option does not show the unwrapped code, which is a bit annoying.

**Comment by yandodov** [comment]
I get the same thing with Storybook 9.0.6 using `@storybook/nextjs`. However, I get it only in `async` stories with `features.experimentalRSC: true` in `.storybook/main.ts` and:

- In dev mode, it happens only when a bunch of updates happen in quick succession (e.g. holding the backspace button to delete text)
- In prod mode, the error is shown immediately when the story is loaded

My guess is that there's some kind of race condition between `useArgs` in `async` RSC components. Perhaps the component takes too long, so `useArgs` of a previous render is called when a new render is already in process.

**Comment by hieucd04** [comment]
This is still happening to me in Storybook `9.0.18`.
Every story that has a `useState` is broken.

**Comment by sonikasharma1403** [comment]
+1. facing the same issue with storybook 9.1 and react + vite

**Comment by kelleghan2** [comment]
Facing the same issue when only setting state in a component that calls useArgs:

```
const TimePickerStory = (args: TimePickerProps) => {
  const [ timeValue, setTimeValue ] = useState<number | null>(args.value)
  const [ _, _ ] = useArgs()

  return (
    <TimePicker
      {...args}
      onChange={(value) => {
        setTimeValue(value)
      }}
      value={timeValue}
    />
  )
}
```

**Comment by pedaars** [comment]
@kasperpeulen is there any update on this issue my companies story book has a large numeber of stories that use hooks

**Comment by asso1985** [comment]
Having same issue when I'm doing async operation in a theme decorator. 

```
export const withThemeDecorator = ({ themes, defaultTheme, loadThemes }: any) => {
  if (!themes && !loadThemes) {
    throw new Error('withThemeDecorator requires either themes or loadThemes');
  }

  return (Story: any, context: any) => {
    const { themeOverride } = context.parameters.themes ?? {};
    const [resolvedThemes, setResolvedThemes] = useState<any>(themes);

    useEffect(() => {
      if (loadThemes) {
        (async () => {
          try {
            const loaded = await loadThemes();

            setResolvedThemes(loaded);
          } catch (e) {
            // eslint-disable-next-line no-console
            console.error('Failed to load themes', e);
          }
        })();
      }
    }, [loadThemes]);

    const selectedTheme = themeOverride || context.globals.theme || defaultTheme;
    const theme = resolvedThemes?.[selectedTheme];

    if (!theme) {
      return <Story />;
    }

    return (
      <ThemeContextProvider theme={theme}>
        <Story />
      </ThemeContextProvider>
    );
  };
};
```

Funny enough tho, it only fails on static and under Playright

**Comment by gurpreetsainisalesforce** [comment]
> [@kasperpeulen](https://github.com/kasperpeulen) is there any update on this issue my companies story book has a large numeber of stories that use hooks

Same! A lot of our stories have started to fail.

**Comment by gurpreetsainisalesforce** [comment]
Has anyone been able to find a workaround for this issue yet?

**Comment by vanessayuenn** [comment]
Hey folks, this issue is quite old and spans across 3 major versions (we just released v10!). The original repro doesn't show the issue anymore, and this makes it difficult for us to investigate. 

Can someone please try this out with v10 and see if the issue persists? If it does, please open a new issue with a new repro so we can look into it! Thanks so much for your help.

**Comment by Dron007** [comment]
I think that the problem still exists in Storybook 10. The same code that worked fine in Storybook 8 now shows this error in one of my stories:

> "Storybook preview hooks can only be called inside decorators and story functions."

I reproduced it here: https://stackblitz.com/edit/github-4dcmyf-ojozm1kp?file=src%2Fstories%2Fhooks.js
The example is simplified so it may look like it is not very useful but the original component has much more logic which was moved to the hook for generalization and reuse.

The problem only occurs when I import external hook which uses `react`'s `useState` inside:

`ExpandableSection.stories`:
```js
import { useExpandablePageSection } from './hooks';
...
const Template = {
  render: function Component(args) {
    const [, setArgs] = useArgs();
    const { isExpanded, toggleExpanded } = useExpandablePageSection();

    const onToggleExpanded = () => {
      toggleExpanded();
      args.onToggleExpanded();
      setArgs({ isExpanded: !args.isExpanded });
    };

    return (
      <ExpandableSection
        {...args}
        isExpanded={isExpanded}
        onToggleExpanded={onToggleExpanded}
      >
        {!!isExpanded && (
          <div>
            section content{' '}
            <button onClick={() => toggleExpanded()}>close</button>
          </div>
        )}
      </ExpandableSection>
    );
  },
};
```

`hooks.js`:
```js
import { useState } from 'react'
import { useState as useStateStorybook } from 'storybook/preview-api'

// useState imported from react will fail in Storybook stories
// IS_STORYBOOK is added in .storybook/preview.js
const useState_ = window?.IS_STORYBOOK ? useStateStorybook : useState

export function useExpandablePageSection () {
  const [isExpanded, setIsExpanded] = useState_(true)

  const toggleExpanded = () => {
    setIsExpanded(!isExpanded)
  }

  return ({
    isExpanded,
    toggleExpanded,
  })
}
```

As you can see only `useState` from `storybook/preview-api` works well. `useState` from `react` fails with error.

Though this workaround works, I think it should be documented somewhere or better fix should be added. I also dislike the fact that component should know anything about Storybook.
