### ISSUE TITLE
[Bug]: Canvas types in the play function stopped working with Yarn PnP.

### ISSUE THREAD

**Issue by DiFuks** [storybookjs/storybook#30763]
### Describe the bug

Starting from Storybook version `8.6.0-alpha.5`, the types for `canvas` [stopped working](https://codesandbox.io/p/devbox/amazing-nightingale-qptdg9?file=%2Fsrc%2FSlider.stories.tsx%3A19%2C5). In version `8.6.0-alpha.5`, the types work correctly when using `within(canvasElement)`, but not otherwise. In Storybook `8.6.0-alpha.4`, both approaches [work correctly](https://codesandbox.io/p/devbox/hopeful-golick-mwvwht?file=%2Fsrc%2FSlider.stories.tsx%3A16%2C21).  

This issue occurs only when using Yarn PnP.

### Reproduction link

https://codesandbox.io/p/devbox/amazing-nightingale-qptdg9?file=%2Fsrc%2FSlider.stories.tsx%3A19%2C5

### System

```bash
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Shell: Unknown
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    Yarn: 4.7.0 - /usr/local/bin/yarn <----- active
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/share/npm-global/bin/pnpm
```

**Comment by mrginglymus** [comment]
It appears that `@storybook/test` is attempting to patch a type in `@storybook/core`:

https://github.com/storybookjs/storybook/blob/d8260421bed5d80f5cc261d462630e07c1f5deca/code/lib/test/src/index.ts#L25

But, as you are unlikely to have `@storybook/core` in your deps, this doesn't do anything on PnP. A workaround is to add `@storybook/core` to your own deps.

**Comment by DiFuks** [comment]
@mrginglymus 
Thanks! This workaround works. However, for it to work with workspaces, you also need to add the following code to `.yarnrc.yml`:

```yml
packageExtensions:
  "@storybook/test@*":
    peerDependencies:
      "@storybook/core": "*"
```

**Comment by DiFuks** [comment]
I think this is a bug on the `@storybook/test` side. It references `@storybook/test`, so it should have it in its `peerDeps`.

**Comment by valentinpalkovic** [comment]
Hi @DiFuks 

Can you please try out the latest Storybook 9 alpha release? The issue should be resolved, since `@storybook/test` was moved into core and the referenced code `declare module '@storybook/core/csf'` doesn't exist anymore.

**Comment by martinnabhan** [comment]
In my case I had to add `import 'storybook/test'` for canvas and userEvent's types to be loaded. If I don't import the types manually the empty Canvas interface in `storybook/dist/csf/index.d.ts` gets used.

**Comment by kondo0602** [comment]
It is redundant to import `storybook/test` in all files that want to use `canvas` or `userEvent`.

By adding the following description to `tsconfig.json`, the `storybook/test` type will be globally expanded, eliminating the need to `import storybook/test` in each `*.stories.tsx`.

```json
{
  "compilerOptions": {
    "types": ["storybook/test"],
  }
}

```

**Comment by DiFuks** [comment]
@kondo0602 

Be careful. By overriding the `compilerOptions.types` field, you change the default behavior for global types. For example, `@types/node` types will no longer be added to the global type scope.
[https://www.typescriptlang.org/tsconfig/#types](https://www.typescriptlang.org/tsconfig/#types)

It’s enough to just add `import 'storybook/test'` in any project file (preferably something like `global.d.ts`).

**Comment by yatishgoel** [comment]
Confirming this is still reproducible on `storybook@10.5.0-alpha.3` under Yarn PnP. The root cause is the declared module `storybook/internal/csf` augmentation in `code/core/src/test/index.ts`, module augmentations only apply if TypeScript loads the augmenting module, which doesn't happen reliably under PnP, so Canvas ships as an empty interface, and StoryContext.userEvent is missing.
