### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by ericclemmons** [storybookjs/storybook#5298]
**Describe the bug**

Using `require` within on a CommonJS module throws this red error in the preview window.

**To Reproduce**

```js
import { storiesOf } from '@storybook/react';
import { setupGraphiQL } from '@storybook/addon-graphql';

const createQuery = require('./createQuery'); // This is the problem line
```

Where `createQuery.js` is:

```js
module.exports = function createQuery(operationName = 'MyQuery') {
  return `...`
}
```

**Expected behavior**

I expect to be able to `require` a module with `module.exports`.

**Screenshots**
> <img width="1008" alt="screen shot 2019-01-18 at 3 55 14 pm" src="https://user-images.githubusercontent.com/15182/51418626-79ad5800-1b39-11e9-845a-5b3d28cc92fc.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [chrome]
 - Framework: [e.g. react]
 - Addons: [graphql]
 - Version: [e.g. 4.1.7]

**Additional context**

Custom `webpack.config.js`:

```js
// https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode

const webpack = require('webpack');

module.exports = config => {
  config.devtool = 'inline-source-map';

  // Needed for ./node_modules/graphiql/graphiql.css
  config.module.rules.push({
    test: /\.css$/,
    loaders: ['style-loader', 'css-loader']
  });

  // Explicitly ignore `.flow` files because GraphiQL, for whatever
  // insane reason, ships `.flow` files that get picked up by Webpack
  // and Next.js
  //
  // > https://github.com/apollographql/apollo-client-devtools/pull/59/files
  config.plugins.push(new webpack.IgnorePlugin(/\.flow$/));

  return config;
};
```

**Comment by jth0024** [comment]
I'm seeing this issue as well

**Comment by nmccready** [comment]
Get rid of stale

**Comment by shilman** [comment]
Is this an issue with `addon-graphql` only, or a general SB issue?

**Comment by lassiter** [comment]
bump, We're running into this issue as well. We use module.exports for our API library. Has anyone made any progress?

**Comment by ndelangen** [comment]
Related:
https://github.com/webpack/webpack/issues/4039

**Comment by JulienPradet** [comment]
For anyone looking for an actionable solution:

You need not to mix `import` with the `module.exports` syntax. (cf. https://github.com/webpack/webpack/issues/4039#issuecomment-273804003)

However, sometimes it's not mixed in your code. You only have some `require/module.exports` in your file. But the error still occurs because some webpack loaders actually add some imports to your file (most likely babel).

So get rid of your `module.exports` and only use `export`/`export default` syntax. Sometimes you can also configure your loaders to ensure that they don't use any imports, but didn't manage to find a magic solution on my end.

**Comment by gilesbutler** [comment]
For anyone stumbling across this, I faced the same problem after importing a NPM package to a Vue component in Storybook. Adding `sourceType: 'unambiguous'` to my babel config fixed the issue for me. Thanks to this issue https://github.com/vuejs/vue-cli/issues/2746

**Comment by DalderupMaurice** [comment]
I'm having this issue as well, not sure how to fix this as I'm not using any `module.exports` nor am I using Vue and I am uzing CRA so there's no babel config to modify

**Comment by lannierose** [comment]
Fixed mine by removing { "modules": false } from this line in .babelrc: ["env", { "modules": false }]

**Comment by HeyKJ** [comment]
> Fixed mine by removing { "modules": false } from this line in .babelrc: ["env", { "modules": false }]

also { "modules": "commonjs" } is working

**Comment by MikeYermolayev** [comment]
Recently this issue appeared again for me. I have a config with styles which is exported by `module.exports = {styleConfig}` and used in components by `import {styleConfig} from 'styleconfig';`. This is done in this way because it's also used in my postCSS config

Everything works when I start my CRA but storybook doesn't start.

**Comment by mattvalleycodes** [comment]
This error happens when there is a mix of module.exports and export. Often times your code only uses ES6 syntax but still get this error. It could be because Webpack / Typescript / Babel are configured in a way that don't exclude some of the node_modules. For me that was the case as I'm using Yarn work-spaces.  Try to inspect the generated Webpack config by adding:

```js
webpackFinal: async (config) => console.log(config.module.rules);
```

chances are that Typescript / Javascript loaders are not configured correctly. 

I fixed the issue by doing:

```jsx
// loader for JS and TS
config.module.rules[0].exclude = [/node_modules/];
```

The original value was excluding only the root-level node_modules whereas with Yarn workspaces you gotta exclude all node_modules.

**Comment by Dark-Games** [comment]
Hey, i have this issue, but i think my problem was with craco.config: 

```
//craco.config.js
const path = require('path');
const { getLoader, loaderByName } = require('@craco/craco');
const absolutePath = path.join(__dirname, '../components');
module.exports = {
  webpack: {
    plugins: [],
    configure: (webpackConfig, { env, paths }) => {
      const { isFound, match } = getLoader(
        webpackConfig,
        loaderByName('babel-loader')
      );
      if (isFound) {
        const include = Array.isArray(match.loader.include)
          ? match.loader.include
          : [match.loader.include];
        match.loader.include = include.concat[absolutePath];
      }
      return webpackConfig;
    },
  },
};
```

But that code work for one of my repo but the another one give this error, someone know what can be wrong?

**Comment by pramod0** [comment]
> Fixed mine by removing { "modules": false } from this line in .babelrc: ["env", { "modules": false }]

signed in to report that this works. Thank you.
