### ISSUE TITLE
CRA & Storybook webpack clash

### ISSUE THREAD

**Issue by firaskrichi** [storybookjs/storybook#6505]
CRA 2.1.5 & Storybook webpack clash - I tried with the latest alpha v of storybook v5.1.0-alpha.25 and the stable version and the problem happens in both 

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.
The react-scripts package provided by Create React App requires a dependency:
  "webpack": "4.28.3"
Don't try to install it manually: your package manager does it automatically.
```

**Comment by shilman** [comment]
@mrmckeb Is this related to https://github.com/storybooks/storybook/pull/5308?

**Comment by mrmckeb** [comment]
@shilman, it may require a similar fix.

@firaskrichi, can you please run `npm ls webpack` and paste the results?

**Comment by baptooo** [comment]
Hello, I am having the same issue here, I am giving you the result of `npm ls webpack`

```
├─┬ @storybook/react@5.0.6
│ ├─┬ @storybook/core@5.0.6
│ │ └── webpack@4.30.0  deduped
│ └── webpack@4.30.0
└─┬ react-scripts@2.1.8
  └── webpack@4.28.3
```

**Comment by firaskrichi** [comment]
@shilman is there an easy workaround we could do until this is fixed maybe? A version that's likely to work?

**Comment by shilman** [comment]
I'm not sure. @mrmckeb is the expert here! Happy to prioritize a release this to get it fixed for CRA users!

**Comment by yairEO** [comment]
I have the same issue :(

```
▶ npm ls webpack 
backoffice-v2@1.0.0 /Users/yeven/projects/backoffice-v2
├─┬ @storybook/react@5.0.11
│ ├─┬ @storybook/core@5.0.11
│ │ └── webpack@4.32.2  deduped
│ └── webpack@4.32.2 
└─┬ react-scripts@3.0.1
  └── webpack@4.29.6 
```

Require assistance please...have no idea how to fix this

**Comment by firaskrichi** [comment]
@mrmckeb what do you advise doing here?

**Comment by john-bell-gw** [comment]
I'm also having this problem and I'd really appreciate some help. 

```
▶ npm ls webpack 
...
├─┬ @storybook/react@5.2.0-alpha.23
│ ├─┬ @storybook/core@5.2.0-alpha.23
│ │ └── webpack@4.33.0  deduped
│ └── webpack@4.33.0 
└─┬ react-scripts@3.0.1
  └── webpack@4.29.6 
```

**Comment by annakjet** [comment]
So far I have found only one solution: add `SKIP_PREFLIGHT_CHECK=true` to `.env`, but that is more of a band-aid rather than an actual solution. Unfortunately, using `yarn` is not an option, since the company does not want to switch to it.

Anybody has any ideas on how to deal with this?

**Comment by annakjet** [comment]
Actually, found a solution: all I had to do was move the `react-scripts` dependency from `devDependencies` to reg `dependencies`.

**Comment by mrmckeb** [comment]
Hi all, you need to have `react-scripts` in `dependencies`, not `devDependencies`. This is how it installs by default.

If you're seeing versioning issues, try removing your `node_modules` and lock file, and reinstalling. This should resolve most issues.

**Comment by seantcoyote** [comment]
I'm still seeing this issue with react-scripts 3.1.1 and storybook 5.1.11 when I add Storybook to an existing project. I'm not using `devDependencies`, so that's not the issue, and using the `resolutions` property in `package.json` doesn't work.

The one solution that does work is to use yarn instead of npm to install dependencies, presumably because of its superior conflict resolution abilities. If I create a new CRA project, however, and add Storybook there's no conflict when installing with npm (or yarn).

The output of `npm ls webpack` in my existing project:
```
├─┬ @storybook/react@5.1.11
│ ├─┬ @storybook/core@5.1.11
│ │ ├─┬ corejs-upgrade-webpack-plugin@2.2.0
│ │ │ └── webpack@4.39.3  deduped
│ │ └── webpack@4.39.3  deduped
│ └── webpack@4.39.3
└─┬ react-scripts@3.1.1
  └── webpack@4.39.1
```

The output of `npm ls webpack` in my new test project:
```
├─┬ @storybook/react@5.1.11
│ ├─┬ @storybook/core@5.1.11
│ │ ├─┬ corejs-upgrade-webpack-plugin@2.2.0
│ │ │ └── webpack@4.39.1  deduped
│ │ └── webpack@4.39.1  deduped
│ └── webpack@4.39.1
└─┬ react-scripts@3.1.1
  └── webpack@4.39.1  deduped
```

As you can see, I'm using the exact same versions of react-scripts and storybook in both projects, yet in my existing project storybook is using `webpack@4.39.3`, whereas it's using `webpack@4.39.1` in the new test project.

**Comment by IvanKovnovic** [comment]
Same issue here... :(

Just tried to add current storybook/react@5.2.1 to my existing CRA-app (react-scripts@3.1.1). Both are _dependencies_, not _devDependencies_. 

Using yarn instead of npm is not possible, so I don't know what to do... (except of unwillingly adding the SKIP_PREFLIGHT_CHECK flag 😒)

Shouldn't be there a mass of people encountering the same problem? Trying to add the current storybook/react version to a CRA-app seems quite common for me

**Comment by ndelangen** [comment]
@mrmckeb could we possibly take a look together, I could use some more information about how CRA does thinks and how we could improve the situation so this happens less often.. 🙇

**Comment by mrmckeb** [comment]
Hi @ndelangen, 100% - but to be honest, this is mostly on the CRA side and I think the issue needs to be resolved there. CRA has very strict version checking, and whilst I understand why the team want that, it means that other tools using the same packages can cause conflicts.

- One solution would be for Storybook to always use CRA's version, and never install such dependencies, but that would require a big change to the way Storybook installs. I don't think that is the right solution either.
- Another possible solution is to have a compatibility table, but this is also something that would - IMO - be a bad fix.

@IvanKovnovic, if you're having the issue, I would suggest that you could a) try to delete your lockfile and `node_modules` and reinstall, or b) use Yarn resolutions to force the project versions of things like Webpack.

Of course, the only other option is to use the `SKIP_PREFLIGHT_CHECK`. This is not a Storybook problem as such, nor a CRA _problem_... it's CRA warning you that the wrong version of a dependency may be picked up during build, and that it may cause you problems. Really, it's a module resolution issue.

**Comment by ndelangen** [comment]
It feels as if there's nothing we can do about this then.

**Comment by IvanKovnovic** [comment]
Hi @mrmckeb , thanks for your detailed answer.

a) doesn't help, if the current dependency versions don't match, like it was the case last week.
(Last week the latest `@storybook/react@5.2.1` resolved webpack to 4.40.2, the latest `react-scripts@3.1.1` resolved it to 4.39.1 -> Issue. In the meanwhile, on Sunday a newly released `react-scripts@3.1.2` dumped webpack to 4.40.2 -> No issue anymore.  So in general its kind of 'luck' regarding the time of trying.

b) is not possible because in my corporate environment the usage of NPM is mandatory

So at the moment I either use the `SKIP_PREFLIGHT_CHECK` or just try to update the packages delayed, after having a look at their current webpack resolutions...

Anyway, I totally understand your arguments and agree on closing this issue because there's nothing that can be done here.
But what about mentioning this problem on the storybook's doc page? I think I'm by far not the only one, because adding a current storybook/react version to a up-to-date CRA-app seems quite common and potentially confusing, especially for beginners.

**Comment by ndelangen** [comment]
@IvanKovnovic Yes, a section explaining this problem on the docs size would be welcome!

Would you be able to make a PR for that? Let me know if you need any help. 🙇

**Comment by mrmckeb** [comment]
Agreed @ndelangen, it would be great to get a PR up.

@IvanKovnovic we are trying to address some of this with the new Storybook preset for CRA... but that's a work in progress.

**Comment by IvanKovnovic** [comment]
Sure, I will attend to it within the next few days

**Comment by siffash** [comment]
Same problem here.

**Comment by shilman** [comment]
@mrmckeb Is there any provision for this in the preset?

**Comment by mrmckeb** [comment]
The new preset (with 5.3.0-alpha) should work better than before, but frankly this is a hard problem to solve without CRA unpinning dependencies.

I'd suggest those affected use Yarn's resolutions feature to control dependencies.

@shilman, let's take a look at this together during the next few days and see if there's anything else we can come up with.

**Comment by marcandrews** [comment]
What about setting `webpack` as a peer dependency?

**Comment by ndelangen** [comment]
That would impact thousands of users of storybook that are not CRA users.
And CRA users don't have a dependency to webpack in their package.json, so they'd get a warning when installing

**Comment by marcandrews** [comment]
> That would impact thousands of users of storybook that are not CRA users.

Maybe, but this could potentially impact [1.4 million CRA users](https://github.com/facebook/create-react-app/network/dependents?package_id=UGFja2FnZS00OTM3NzgxNzc%3D).

> And CRA users don't have a dependency to webpack in their package.json, so they'd get a warning when installing

Are you sure this is how peer dependencies work? I am almost certain that webpack as a peer dependency would resolve to the webpack under CRA.

**Comment by mrmckeb** [comment]
@marcandrews, this is a tricky situation. Storybook definitely needs Webpack, but CRA has a traditionally had pinned versions of everything which is what causes the issue.

I'm on both teams, and I believe this is an issue on the CRA side more than Storybook. However, I've worked with @ndelangen and @shilman on this for a while now, and we've been trying to find the right solution. 

The peer dependency fix would break usage for other users, as they would then need to install Webpack themselves (they may be using a competing build system).

Out of interest, what is the version difference you're seeing @marcandrews?

**Comment by marcandrews** [comment]
Yes, I agree; this is a challenging problem, especially when the team has done an amazing job reducing the amount of setup/overhead required to get Storybook up and running.

I am currently using `react-scripts@3.2.0` and it has `webpack@4.41.0` as a dependency. `@storybook/core@5.2.6` depends on `webpack@^4.33.0`, so the latest `webpack@4.41.2` gets installed, resulting in a conflict.

What if `webpack`, and other, build-like dependencies, were moved to the individual platform packages? For quick starts, the `@storybook/cli` can install `webpack`, while for slow starts (individual platforms), the user can be instructed to install `webpack`. For example, the docs `@storybook/react` already ask you to install `react`, `react-dom`, `@babel/core`, and `babel-loader`; `webpack` can be added to list. This also opens up the possibility to bring my own build system (parcel, rollup, TypeScript, etc.).

I'm just hypothesizing here.

**Comment by mrmckeb** [comment]
@marcandrews, I think that's a great idea. My only concern is that Storybook itself may then have potential issues - as it would rely on versions set by the user.

But this may be the only sensible path forward. We're also trying to loosen ranges on the CRA side.

**Comment by marcandrews** [comment]
There are a few teams I never question with respect to SemVer and `webpack` is one of them 😀

... but yes, when setting `webpack` as a peer dependency, a minimum major version should be specified. `npm` should be smart enough to install the version of `webpack` specified by CRA as it should satisfy the peer dependency.

**Comment by shilman** [comment]
@mrmckeb @ndelangen @marcandrews Do we have a path forward here?

**Comment by mrmckeb** [comment]
I'm not sure what the right path is @shilman, it would be risky for Storybook to rely on CRA's version of Webpack, but on the CRA side we're loosening dependencies.

**Comment by steveoh** [comment]
Should this be closed? It's still unresolved and an issue that I just searched for.

**Comment by snyderhaus** [comment]
I've still got issues with my system as well. No resolve since April of last year just suggestions? And none of those suggestions seem to be working..

**Comment by ndelangen** [comment]
@mrmckeb did CRA end up allowing for more loose versions of its dependencies?

Can we tell users that upgrading to the latest CRA + Storybook resolves the issue?

**Comment by nmiddleweek** [comment]
@ndelangen - I'm currently experiencing this issue with an old repo running ```"react-scripts": "^3.3.0",``` and ```"@storybook/react": "^5.2.6",```. 

Storybook is loading 4.41.5
react-scripts is loading 4.41.2

But they conflict.

I'm being told the workaround is to manually ```npm i webpack@4.41.2``` as Storybook works fine with it.

However I'm reluctant and I'm wondering if you know what version of Storybook is bound to webpack@4.41.2 ?

I will try a fresh CRA + Storybook this evening and let you know if the outcome but in the meantime it would be great to get your feedback on adding webpack as a root dependancy?

Thanks

**Comment by ndelangen** [comment]
@nmiddleweek storybook will work with either `4.41.5` or `4.41.2` no problem. So will CRA.

We do not release a new version of storybook for every patch version of webpack, so there's no version of storybook that exactly depends on webpack `4.41.2`.

My assumption is that if you indeed install the exact version CRA wants, storybook will start using that, nor problem.

**Comment by mrmckeb** [comment]
Sorry @ndelangen, this is happening gradually.

Users of Yarn can use resolutions to lock the version of Webpack to a specific version (across both Storybook and CRA), and there is a package for npm which can emulate that (https://www.npmjs.com/package/npm-force-resolutions).

You can also, as Norbert mentioned, install the dependency to your project directly - at the version CRA is requesting.

**Comment by rob-edgescan** [comment]
I was getting this same issue, my yarn was out of date. 
Running `sudo apt-get update` was failing to update yarn. 
Turns out I was using an old GPG key, to get the updated key I ran:

```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
sudo apt-get update
```

And it fixed my yarn.

Credit:
https://github.com/yarnpkg/yarn/issues/7866

**Comment by hunterxxx** [comment]
Create a `.env` file in the root directory of the project and add this line `SKIP_PREFLIGHT_CHECK=true` inside the file.

then try to run `yarn start`.

**Comment by arjansingh** [comment]
> Sorry @ndelangen, this is happening gradually.
> 
> Users of Yarn can use resolutions to lock the version of Webpack to a specific version (across both Storybook and CRA), and there is a package for npm which can emulate that (https://www.npmjs.com/package/npm-force-resolutions).
> 
> You can also, as Norbert mentioned, install the dependency to your project directly - at the version CRA is requesting.

[Yarn resolutions documentation](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)

**Comment by marcandrews** [comment]
Is this still happening?

I am on `react-scripts@3.3.0`, `@storybook/react@^5.3.14` with `@storybook/preset-create-react-app@^1.5.2` and I can compile without warnings.

By the way, I think this _preset option_ is an excellent solution; it's definitely better than modifying the _slow-start_ instructions. After upgrading from 5.2, I was back up and running in about 10 minutes ❤️

**Comment by mrmckeb** [comment]
Thanks for the feedback @marcandrews!

**Comment by key-joshua** [comment]
> SKIP_PREFLIGHT_CHECK=true


> Create a `.env` file in the root directory of the project and add this line `SKIP_PREFLIGHT_CHECK=true` inside the file.
> 
> then try to run `yarn start`.

Huge shout to you man and great thanks.

**Comment by jNormaster** [comment]
I experienced this issue today.
Workaround with .env file solved it

```
+-- @storybook/react@5.3.18
| +-- @storybook/core@5.3.18
| | +-- corejs-upgrade-webpack-plugin@2.2.0
| | | `-- webpack@4.42.1  deduped
| | `-- webpack@4.42.1  deduped
| `-- webpack@4.42.1
`-- react-scripts@3.4.1
  `-- webpack@4.42.0
```

**Comment by montogeek** [comment]
I stil get the error with:
react-scripts@3.4.1
@storybook/preset-create-react-app@2.1.2
@storybook/react@5.3.18

**Comment by Vqtran15** [comment]
> Create a `.env` file in the root directory of the project and add this line `SKIP_PREFLIGHT_CHECK=true` inside the file.
> 
> then try to run `yarn start`.

This has been the only way for me so far to work around the erroe

**Comment by TeoTN** [comment]
I've opened an issue with CRA: https://github.com/facebook/create-react-app/issues/9010
I think this is a platform design problem

**Comment by TeoTN** [comment]
Were there any changes applied to Storybook that would resolve that problem?

**Comment by ndelangen** [comment]
@TeoTN A lot of work has been done to make storybook work much much better with CRA out of the box & typescript.

You mostly have @mrmckeb to thanks for it

**Comment by IrmantasM** [comment]
Also facing this issue:

```sh
├─┬ @storybook/react@5.1.9
│ ├─┬ @storybook/core@5.1.9
│ │ ├─┬ corejs-upgrade-webpack-plugin@2.2.0
│ │ │ └── webpack@4.41.5  deduped
│ │ └── webpack@4.41.5  deduped
│ └── webpack@4.41.5 
└─┬ react-scripts@3.4.1
  └── webpack@4.42.0 
```

I am troubleshooting build performance issues and now I am not sure if this can be causing it or I can simply ignore it using `SKIP_PREFLIGHT_CHECK=true`.

**Comment by RoeelCohen** [comment]
Same issue:
```
+-- @storybook/addon-storyshots@5.3.18
| `-- @storybook/core@5.3.18
|   +-- corejs-upgrade-webpack-plugin@2.2.0
|   | `-- webpack@4.44.1  deduped
|   `-- webpack@4.44.1  deduped
+-- @storybook/react@5.3.18
| `-- webpack@4.44.1
`-- react-scripts@3.4.2
  `-- webpack@4.42.0
```

The funny thing is that I copied the template of another CRA project where the correct version of storybook was installed

```
├─┬ @storybook/addon-storyshots@5.3.18
│ └─┬ @storybook/core@5.3.18
│   ├─┬ corejs-upgrade-webpack-plugin@2.2.0
│   │ └── webpack@4.40.2  deduped
│   └── webpack@4.40.2  deduped
├─┬ @storybook/react@5.3.18
│ └── webpack@4.40.2 
└─┬ react-scripts@3.1.2
  └── webpack@4.40.2  deduped
```
currently the whole org. works with npm so moving to yan might be an issue.

**Comment by aleph-naught2tog** [comment]
Me too:

```
├─┬ @storybook/addon-docs@6.0.4
│ └─┬ @storybook/core@6.0.4
│   └── webpack@4.44.1  deduped
├─┬ @storybook/react@6.0.4
│ └── webpack@4.44.1
└─┬ react-scripts@3.4.2
  └── webpack@4.42.0
```

**Comment by Alellujah** [comment]
I had the same problem and the only thing that solved was putting storybook in the devDependencies (which I guess it's fine as it is only used for development purposes by us)

```
"devDependencies": {
    "storybook": "^6.0.3",
    "@storybook/react": "^6.0.4",
    "@types/storybook__react": "^5.2.1",
    "@storybook/addon-actions": "^6.0.4",
    "@storybook/addon-knobs": "^6.0.4",
    "@types/storybook__addon-knobs": "^5.2.1"
}
```

**Comment by shilman** [comment]
@Alellujah You'll probably want to get rid of those `@types/storybook__` packages. Storybook now has built-in types

**Comment by julesvirallinen** [comment]
Still happening to me

```
├─ react-scripts@3.4.3
│  └─ webpack@4.42.0
└─ webpack@4.44.2
```

```   
 "@storybook/addon-actions": "^6.0.26",
    "@storybook/addon-essentials": "^6.0.26",
    "@storybook/addon-links": "^6.0.26",
    "@storybook/node-logger": "^6.0.26",
    "@storybook/preset-create-react-app": "^3.1.4",
    "@storybook/react": "^6.0.26",
    "react-scripts": "3.4.3",

```

**Comment by brahmdev** [comment]
Storybook has `"webpack": "^4.44.2"` dependency and react-scripts has `"webpack": "4.44.2"`  dependency in my case (difference in ^).
And the recent release from `webpack` was 4.44.6 and that gave me blow issue.

```
The react-scripts package provided by Create React App requires a dependency:
  "webpack": "4.44.2"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  /<my-directory-path>/node_modules/webpack (version: 4.46.0) 
```
When I did `yarn why webpack` 
then there was 2 version of webpack, `4.44.2 `and `4.46.0`

After some search, I added below in my package.json file to have the exact version of `webpack`
```
"resolutions": {
  "webpack": "4.44.2"
},
  
```
It worked for me and hope there is no issue with this solution.
I hope that helps you guys.
Thanks!

**Comment by shomukai** [comment]
By adding `"webpack": "4.44.2"` explicitly into devDependencies and run `npm i` fixed the issue.
For yarn, not sure whether it works the same way as npm or not, but add resolutions should be fine.

**Comment by johnnyoshika** [comment]
@shomukai's technique worked like a charm for me.

**Comment by maxgfr** [comment]
Problem solved with this version : https://github.com/storybookjs/storybook/releases/tag/v6.3.11

**Comment by AlmogBaku** [comment]
Unfortunately, neither the versions `6.3.12`, `6.3.11` nor @shomukai works for me :(

I'm trying every time again from scratch (no `node_modules` and no lock file)...

**Comment by iamgutz** [comment]
For me the fix was the one suggested by @outdoteth 
Add the packages to the `resolutions` in `package.json`, in my case the issue was 2 packages, `babel-loader` and `webpack`. So my resolutions look like:

```
"resolutions": {
    "babel-loader": "8.1.0",
    "webpack": "4.42.0"
  },
```

**IMPORTANT** after adding this to the `package.json` you MUST run `yarn install` otherwise it won't work.

**Comment by AlmogBaku** [comment]
this is still not fixed.

**Comment by andy7love** [comment]
Hi :wave: , this is still not fixed. 
After doing a `npx sb@latest upgrade` and a `npm ls webpack`
I got the following: 
```
├─┬ @storybook/addon-essentials@6.4.12
│ └─┬ @storybook/addon-docs@6.4.12
│   ├─┬ @storybook/builder-webpack4@6.4.12
│   │ ├─┬ html-webpack-plugin@4.5.2
│   │ │ └── webpack@4.46.0  extraneous
│   │ ├── webpack@4.46.0 
│   │ └─┬ webpack-dev-middleware@3.7.3
│   │   └── webpack@4.46.0  extraneous
│   └─┬ @storybook/core@6.4.12
│     └── webpack@4.46.0  extraneous
├─┬ @storybook/builder-webpack5@6.4.12
│ └─┬ @storybook/core-common@6.4.12
│   ├─┬ fork-ts-checker-webpack-plugin@6.5.0
│   │ └── webpack@5.66.0  extraneous
│   └── webpack@4.46.0 
└─┬ @storybook/react@6.4.12
  ├─┬ @storybook/core@6.4.12
  │ └─┬ @storybook/core-server@6.4.12
  │   ├─┬ @storybook/manager-webpack4@6.4.12
  │   │ └── webpack@4.46.0 
  │   └── webpack@4.46.0 
  └── webpack@4.46.0 
```

It seems that `addons/docs`
https://github.com/storybookjs/storybook/blob/ad0dc42b24f89e1c34b6e826734c8bf1d38adf48/addons/docs/package.json#L68

And `core-server`
https://github.com/storybookjs/storybook/blob/ad0dc42b24f89e1c34b6e826734c8bf1d38adf48/lib/core-server/package.json#L50

Are forced to use `manager-webpack4`, which of course is going to use webpack4.
https://github.com/storybookjs/storybook/blob/ad0dc42b24f89e1c34b6e826734c8bf1d38adf48/lib/manager-webpack4/package.json#L78

**Comment by aricma** [comment]
thx @johnnyoshika 
`npx sb@latest upgrade && rm -rf node_modules && yarn` worked for me 
@AlmogBaku removing the `node_modules` was necessary ... it was still crashing before reinstalling everything "clean"

**Comment by misterlocations** [comment]
For me, either using `yarn` OR moving `react-scripts` back to regular dependencies solves the issue. Though, I don't totally understand why the default location of `react-scripts` is dependencies by default in CRA.

**Comment by ndelangen** [comment]
Is this still an issue in 7.0 beta?
