### ISSUE TITLE
[addon-knobs] Issue with select `options` type, does not support array of objects

### ISSUE THREAD

**Issue by jasongerbes** [storybookjs/storybook#9751]
### Bug or support request summary

The `select` knob's type is incorrect, as it does not support using an array of option objects, as per the [example in the readme file](https://github.com/storybookjs/storybook/tree/master/addons/knobs#select).

```ts
const label = 'Dogs';
const arrayOfObjects = [
  {
    label: 'Sparky',
    dogParent: 'Matthew',
    location: 'Austin',
  },
  {
    label: 'Juniper',
    dogParent: 'Joshua',
    location: 'Austin',
  },
];
const defaultValue = arrayOfObjects[0];
const groupId = 'GROUP-ID3';
const value = select(label, options, defaultValue, groupId);
```

> Side note: the example needs to be fixed
> `options` needs to be changed to `arrayOfObjects`.

Typescript complains with the following error:

```
Argument of type '{ label: string; dogParent: string; location: string; }[]' is not assignable to parameter of type 'SelectTypeOptionsProp<SelectTypeKnobValue>'.
  Type '{ label: string; dogParent: string; location: string; }[]' is not assignable to type 'ReactText[]'.
    Type '{ label: string; dogParent: string; location: string; }' is not assignable to type 'ReactText'.
      Type '{ label: string; dogParent: string; location: string; }' is not assignable to type 'number'.ts(2345)
``` 

### Steps to reproduce

Try the above example.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 5.3.10 (as 5.3.11 has an [open issue](https://github.com/storybookjs/storybook/issues/9749))
- @storybook/addon-knob 5.3.11

### Affected platforms 

- VSCode with Typescript v3.7.3

**Comment by jasongerbes** [comment]
@shilman do you think this issue will be resolved?

**Comment by shilman** [comment]
@jasongerbes it will if somebody from the community picks it up

**Comment by gausie** [comment]
This is still an issue, can we keep it open?

**Comment by shilman** [comment]
We've just released zero-config typescript support in 6.0-beta. Please upgrade and test it!

- [Release 6.0.0-beta.12+](https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.12)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript)
- [Updated docs](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md)

Thanks for your help and support getting this stable for release!

**Comment by rohan-paul** [comment]
Facing the same problem after upgrading to `6.0-beta`.

So I first upgraded to `6.0.0-beta.13` and then followed [this part of the doc for `main.js` configuration](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md#default-configuration) and now my .`storybook/main.js` looks like below, but the same problem persists.

```js
module.exports = {
  stories: ["../stories/**/*.stories.[tj]s"],
  addons: [
    "@storybook/addon-knobs/register",   
  ],
  typescript: {
    check: false,
    checkOptions: {}
  }
};
```

And was trying to implement a simple Angular storybook component with `[ng-select](https://ng-select.github.io/ng-select#/data-sources)` using [storybookjs/addons/knobs](https://github.com/storybookjs/storybook/tree/master/addons/knobs)


So here's the prop data I am passing 

```js
const countries = [
  { id: 1, countryId: "L", name: "Lithuania" },
  { id: 2, countryId: "U", name: "USA" },
  { id: 3, countryId: "A", name: "Australia" }
];
```
to be consumed by the **knobs** with the below line

```js
props: {
    items: select("items", countries, countries[0], groupId)
  }
```

And getting 

```js
Argument of type '{ id: number; countryId: string; name: string; }[]' is not assignable to parameter of type 'SelectTypeOptionsProp<SelectTypeKnobValue>'.
  Type '{ id: number; countryId: string; name: string; }[]' is not assignable to type '(string | number)[]'.
    Type '{ id: number; countryId: string; name: string; }' is not assignable to type 'string | number'.
      Type '{ id: number; countryId: string; name: string; }' is not assignable to type 'number'.

   items: select("items", countries, countries, groupId),                              

```
Was not sure, if there's some implementation details that I am missing here, so have already raised a [StackOverflow question](https://stackoverflow.com/questions/61953648/angular-storybook-withknobs-storybookjs-addons-knobs-array-of-objects-with-sel).

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

**Comment by piemasters** [comment]
@shilman I don't think controls currently supports a list of objects as a select type. Whenever I've tried it only displays one option listed as `[object Object]`. Eg setup:

```
  argTypes: {
    color: {
      control: {
        type: "select",
        options: [
          { main: "#00B869", background: "#F5FFFB" },
          { main: "#4FB800", background: "#F9FFF5" },
          { main: "#EB7600", background: "#FFFAF5" },
        ],
      },
    },
  },
```

I could be wrong but I think knobs added support for this earlier in the year, although it could have been only in the 6.0-beta.

**Comment by shilman** [comment]
@piemasters controls does not support an array of objects. You can pass it an object whose keys are the labels and whose values are the corresponding data (in any form). Or an array of strings.

**Comment by piemasters** [comment]
@shamin yup that's how I'm doing it. I've found it's generally better practice to pass primitives rather than objects where possible when creating reusable components and using controls has helped me stick with that. 

I just thought i'd note that because of that using controls over knobs doesn't really help the original problem, although I still recommend switching over because controls is much nicer to use than knobs. Maybe support will be added in a future update?

**Comment by shilman** [comment]
@piemasters yeah. I posted that notice to all open `addon-knobs` issues regardless of whether controls solves the problem, and will continue to do so. I want everybody who uses knobs to knob about controls and upgrade as soon as it's convenient. The sooner people upgrade, the sooner we can deprecate knobs, which doesn't have any maintainers.

**Comment by akshaykn-bh** [comment]
> @piemasters controls does not support an array of objects. You can pass it an object whose keys are the labels and whose values are the corresponding data (in any form). Or an array of strings.

thanks bro
